# Generated by Django 6.0 on 2026-01-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raytaskexecution',
            name='timeout_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum execution time in seconds (None = no timeout)', null=True),
        ),
    ]
