# Generated by Django 6.0.7 on 2026-07-19 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0005_raytaskexecution_cancellation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("CANCELLING", "Cancelling"),
                            ("LOST", "Lost"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_traceback", models.TextField(blank=True, null=True)),
                ("result_data", models.TextField(blank=True, null=True)),
                ("result_reference", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="django_ray.raytaskexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["attempt_number"],
                "indexes": [
                    models.Index(
                        fields=["execution", "attempt_number"],
                        name="django_ray__executi_31dfd4_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("execution", "attempt_number"),
                        name="ray_task_attempt_unique_number",
                    )
                ],
            },
        ),
    ]
