# Generated by Django 6.0.7 on 2026-07-19 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0006_taskattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="raytaskexecution",
            name="priority",
            field=models.SmallIntegerField(
                default=0,
                help_text="Django task priority (-100 to 100; larger values run sooner)",
                validators=[
                    django.core.validators.MinValueValidator(-100),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
