# Generated by Django 6.0.7 on 2026-07-19 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0008_raytaskexecution_priority_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskInputPayload",
            fields=[
                (
                    "reference",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("backend", models.CharField(max_length=32)),
                ("digest", models.CharField(db_index=True, max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("envelope_version", models.PositiveSmallIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("PURGED", "Purged")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_used_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                ("cleanup_error", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Task Input Payload",
                "verbose_name_plural": "Task Input Payloads",
                "ordering": ["created_at", "reference"],
                "indexes": [
                    models.Index(
                        fields=["state", "last_used_at"],
                        name="ray_input_cleanup_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="raytaskexecution",
            name="input_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Reference to a durable external task-input envelope",
                max_length=500,
                null=True,
            ),
        ),
    ]
