# Generated by Django 6.0.7 on 2026-07-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0009_taskinputpayload_and_input_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="raytaskexecution",
            name="workflow_run_id",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Current workflow invocation allowed to persist progress",
                null=True,
            ),
        ),
    ]
