# Generated by Django 6.0.7 on 2026-07-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0010_raytaskexecution_workflow_run_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="raytaskexecution",
            name="workflow_plan_fingerprint",
            field=models.CharField(
                blank=True,
                help_text="Pinned secret-free effective workflow plan identity",
                max_length=71,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="raytaskexecution",
            name="workflow_plan_json",
            field=models.TextField(
                blank=True,
                help_text="Bounded canonical secret-free effective workflow plan",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="raytaskexecution",
            name="workflow_plan_pinned_attempt",
            field=models.PositiveIntegerField(
                blank=True,
                editable=False,
                help_text="Attempt that first pinned the effective workflow plan identity",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="raytaskexecution",
            name="workflow_plan_selection",
            field=models.TextField(
                blank=True,
                help_text="Bounded strategy eligibility and selection metadata",
                null=True,
            ),
        ),
    ]
