# Generated by Django 6.0.7 on 2026-07-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0011_raytaskexecution_workflow_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="raytaskexecution",
            name="workflow_progress_summary_json",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="Bounded canonical schema-v3 workflow progress summary",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="workflow_progress_summary_json",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="Bounded terminal workflow progress summary for this attempt",
                null=True,
            ),
        ),
    ]
