# Generated by Django 6.0.7 on 2026-07-20 00:00

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0012_workflow_progress_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowProgressRunStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("execution_generation", models.PositiveBigIntegerField()),
                ("run_id", models.UUIDField()),
                (
                    "detail_revision",
                    models.PositiveBigIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "detail_node_count",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(25000)],
                    ),
                ),
                (
                    "detail_pending_count",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(25000)],
                    ),
                ),
                (
                    "detail_running_count",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(25000)],
                    ),
                ),
                (
                    "detail_succeeded_count",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(25000)],
                    ),
                ),
                (
                    "detail_failed_count",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(25000)],
                    ),
                ),
                (
                    "detail_truncated_count",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(25000)],
                    ),
                ),
                (
                    "detail_event_count",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(32)],
                    ),
                ),
                (
                    "detail_truncation_reasons",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "detail_encoded_bytes",
                    models.PositiveBigIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(8388608)],
                    ),
                ),
                (
                    "detail_decoded_bytes",
                    models.PositiveBigIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(16777216)],
                    ),
                ),
                (
                    "detail_retention_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                ("detail_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cleanup_error",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=2000,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_progress_runs",
                        to="django_ray.raytaskexecution",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["detail_expires_at", "id"],
                        name="ray_wf_run_expiry_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "execution",
                            "attempt_number",
                            "execution_generation",
                            "run_id",
                        ),
                        name="ray_wf_run_identity_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(attempt_number__gte=1),
                        name="ray_wf_run_attempt_pos",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(detail_revision__isnull=True)
                            | models.Q(detail_revision__gte=1)
                        ),
                        name="ray_wf_run_detail_rev_pos",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(detail_node_count__lte=25000),
                        name="ray_wf_run_detail_count_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            detail_failed_count__lte=25000,
                            detail_pending_count__lte=25000,
                            detail_running_count__lte=25000,
                            detail_succeeded_count__lte=25000,
                        ),
                        name="ray_wf_run_state_counts_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            detail_node_count=(
                                models.F("detail_pending_count")
                                + models.F("detail_running_count")
                                + models.F("detail_succeeded_count")
                                + models.F("detail_failed_count")
                            )
                        ),
                        name="ray_wf_run_state_counts_sum",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            detail_truncated_count__lte=models.F("detail_node_count")
                        ),
                        name="ray_wf_run_truncated_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(detail_event_count__lte=32),
                        name="ray_wf_run_event_count_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(detail_encoded_bytes__lte=8388608),
                        name="ray_wf_run_encoded_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(detail_decoded_bytes__lte=16777216),
                        name="ray_wf_run_decoded_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(detail_decoded_bytes=models.F("detail_encoded_bytes")),
                        name="ray_wf_run_detail_size_eq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            detail_retention_days__gte=0,
                            detail_retention_days__lte=30,
                        ),
                        name="ray_wf_run_retention_days",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                detail_node_count=0,
                                detail_pending_count=0,
                                detail_running_count=0,
                                detail_succeeded_count=0,
                                detail_failed_count=0,
                                detail_truncated_count=0,
                                detail_event_count=0,
                                detail_encoded_bytes=0,
                                detail_decoded_bytes=0,
                            )
                            | models.Q(
                                detail_node_count__gte=1,
                                detail_encoded_bytes__gte=1,
                                detail_decoded_bytes__gte=1,
                            )
                        ),
                        name="ray_wf_run_detail_totals",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(detail_revision__isnull=False)
                            | models.Q(
                                detail_node_count=0,
                                detail_pending_count=0,
                                detail_running_count=0,
                                detail_succeeded_count=0,
                                detail_failed_count=0,
                                detail_truncated_count=0,
                                detail_event_count=0,
                                detail_truncation_reasons="",
                                detail_encoded_bytes=0,
                                detail_decoded_bytes=0,
                            )
                        ),
                        name="ray_wf_run_unpub_empty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowProgressNodeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_key",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=("Value must be a lowercase hexadecimal SHA-256 digest."),
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("node_id", models.CharField(max_length=256)),
                (
                    "invocation_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "event_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(32)],
                    ),
                ),
                ("truncated", models.BooleanField(default=False)),
                ("payload", models.BinaryField(max_length=16384)),
                (
                    "digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=("Value must be a lowercase hexadecimal SHA-256 digest."),
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "encoded_bytes",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(16384),
                        ]
                    ),
                ),
                (
                    "decoded_bytes",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(16384),
                        ]
                    ),
                ),
                (
                    "last_topology_version",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "last_detail_revision",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "run_storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_details",
                        to="django_ray.workflowprogressrunstorage",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["run_storage", "state", "node_key"],
                        name="ray_wf_node_state_idx",
                    ),
                    models.Index(
                        fields=["run_storage", "event_count"],
                        name="ray_wf_node_event_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_storage", "node_key"),
                        name="ray_wf_node_key_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(event_count__lte=32),
                        name="ray_wf_node_event_count_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(encoded_bytes__gte=1, encoded_bytes__lte=16384),
                        name="ray_wf_node_encoded_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(decoded_bytes__gte=1, decoded_bytes__lte=16384),
                        name="ray_wf_node_decoded_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(decoded_bytes=models.F("encoded_bytes")),
                        name="ray_wf_node_identity_size",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(last_topology_version__gte=1),
                        name="ray_wf_node_topology_pos",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(last_detail_revision__gte=1),
                        name="ray_wf_node_detail_pos",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowProgressTopologyManifest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topology_version",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[("CURRENT", "Current"), ("PENDING", "Pending")],
                        max_length=7,
                    ),
                ),
                (
                    "manifest_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=("Value must be a lowercase hexadecimal SHA-256 digest."),
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "truncation_reasons",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("payload", models.BinaryField(max_length=262144)),
                (
                    "node_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(25000)]
                    ),
                ),
                (
                    "edge_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100000)]
                    ),
                ),
                (
                    "node_page_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(25000)]
                    ),
                ),
                (
                    "edge_page_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100000)]
                    ),
                ),
                (
                    "encoded_bytes",
                    models.PositiveBigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(16777216),
                        ]
                    ),
                ),
                (
                    "decoded_bytes",
                    models.PositiveBigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(33554432),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cleanup_error",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    "run_storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topology_manifests",
                        to="django_ray.workflowprogressrunstorage",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["slot", "created_at"],
                        name="ray_wf_manifest_gc_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_storage", "topology_version"),
                        name="ray_wf_manifest_ver_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("run_storage", "slot"),
                        name="ray_wf_manifest_slot_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(topology_version__gte=1),
                        name="ray_wf_manifest_ver_pos",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(node_count__lte=25000),
                        name="ray_wf_manifest_node_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(edge_count__lte=100000),
                        name="ray_wf_manifest_edge_cap",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(node_count=0, node_page_count=0)
                            | models.Q(
                                node_count__gte=1,
                                node_page_count__gte=1,
                                node_page_count__lte=models.F("node_count"),
                            )
                        ),
                        name="ray_wf_manifest_node_pages",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(edge_count=0, edge_page_count=0)
                            | models.Q(
                                edge_count__gte=1,
                                edge_page_count__gte=1,
                                edge_page_count__lte=models.F("edge_count"),
                            )
                        ),
                        name="ray_wf_manifest_edge_pages",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(encoded_bytes__gte=1, encoded_bytes__lte=16777216),
                        name="ray_wf_manifest_encoded_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(decoded_bytes__gte=1, decoded_bytes__lte=33554432),
                        name="ray_wf_manifest_decoded_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(decoded_bytes=models.F("encoded_bytes")),
                        name="ray_wf_manifest_size_eq",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(slot="PENDING", published_at__isnull=True)
                            | models.Q(slot="CURRENT", published_at__isnull=False)
                        ),
                        name="ray_wf_manifest_slot_state",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowProgressTopologyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=("Value must be a lowercase hexadecimal SHA-256 digest."),
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "collection",
                    models.CharField(
                        choices=[("NODE", "Node"), ("EDGE", "Edge")],
                        max_length=4,
                    ),
                ),
                (
                    "encoding",
                    models.CharField(
                        choices=[("identity", "Identity")],
                        default="identity",
                        max_length=16,
                    ),
                ),
                ("payload", models.BinaryField(max_length=262144)),
                (
                    "item_count",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(256),
                        ]
                    ),
                ),
                (
                    "encoded_bytes",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(262144),
                        ]
                    ),
                ),
                (
                    "decoded_bytes",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1048576),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "run_storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topology_pages",
                        to="django_ray.workflowprogressrunstorage",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at", "id"],
                        name="ray_wf_page_gc_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_storage", "digest"),
                        name="ray_wf_page_digest_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(item_count__gte=1, item_count__lte=256),
                        name="ray_wf_page_item_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(encoded_bytes__gte=1, encoded_bytes__lte=262144),
                        name="ray_wf_page_encoded_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(decoded_bytes__gte=1, decoded_bytes__lte=1048576),
                        name="ray_wf_page_decoded_cap",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(decoded_bytes=models.F("encoded_bytes")),
                        name="ray_wf_page_identity_size",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowProgressTopologyManifestPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection",
                    models.CharField(
                        choices=[("NODE", "Node"), ("EDGE", "Edge")],
                        max_length=4,
                    ),
                ),
                ("page_index", models.PositiveIntegerField()),
                (
                    "manifest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_links",
                        to="django_ray.workflowprogresstopologymanifest",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="manifest_links",
                        to="django_ray.workflowprogresstopologypage",
                    ),
                ),
            ],
            options={
                "ordering": ["collection", "page_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("manifest", "collection", "page_index"),
                        name="ray_wf_link_position_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("manifest", "page"),
                        name="ray_wf_link_page_uniq",
                    ),
                ],
            },
        ),
    ]
