# Generated by Django 6.0.7 on 2026-07-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0013_workflow_progress_detail_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="raytaskexecution",
            name="ray_target_address",
            field=models.CharField(
                blank=True,
                help_text="Immutable Ray cluster target selected when this task was enqueued",
                max_length=255,
                null=True,
            ),
        ),
    ]
