# Generated by Django 6.0.7 on 2026-08-01 00:00

from django.db import migrations, models
from django.db.models import Count, Min

_DUPLICATE_SAMPLE_LIMIT = 5


def reject_duplicate_task_ids(apps, schema_editor) -> None:
    """Fail without choosing an owner when legacy task IDs are ambiguous."""
    execution = apps.get_model("django_ray", "RayTaskExecution")
    duplicate_groups = (
        execution.objects.using(schema_editor.connection.alias)
        .values("task_id")
        .annotate(row_count=Count("pk"), first_pk=Min("pk"))
        .filter(row_count__gt=1)
        .order_by("first_pk")
    )
    duplicate_group_count = duplicate_groups.count()
    if duplicate_group_count == 0:
        return

    examples = ", ".join(
        f"first_pk={item['first_pk']} rows={item['row_count']}"
        for item in duplicate_groups[:_DUPLICATE_SAMPLE_LIMIT]
    )
    raise RuntimeError(
        "django-ray migration 0015 cannot enforce unique task result IDs: "
        f"found {duplicate_group_count} duplicate identity group(s). "
        f"Bounded examples: {examples}. Resolve every duplicate group explicitly "
        "before rerunning this migration; no owner was selected and no rows were changed."
    )


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0014_raytaskexecution_ray_target_address"),
    ]

    operations = [
        migrations.RunPython(
            reject_duplicate_task_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="raytaskexecution",
            name="task_id",
            field=models.CharField(
                help_text="ID from Django Tasks",
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="raytaskexecution",
            constraint=models.UniqueConstraint(
                fields=("task_id",),
                name="ray_task_id_unique",
            ),
        ),
    ]
