# Generated by Django 6.0.7 on 2026-08-03 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0017_raytaskexecution_sensitive_data_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="raytaskexecution",
            name="workflow_run_namespace",
            field=models.PositiveBigIntegerField(
                blank=True,
                editable=False,
                help_text="Database-unique opaque namespace for workflow run IDs",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9223372036854775807),
                ],
            ),
        ),
        migrations.AddField(
            model_name="raytaskexecution",
            name="workflow_run_sequence",
            field=models.PositiveBigIntegerField(
                default=0,
                db_default=0,
                editable=False,
                help_text="Monotonic database allocation sequence for workflow run IDs",
                validators=[django.core.validators.MaxValueValidator(576460752303423487)],
            ),
        ),
        migrations.AddConstraint(
            model_name="raytaskexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("workflow_run_sequence__gte", 0),
                    ("workflow_run_sequence__lte", 576460752303423487),
                ),
                name="ray_task_wf_run_seq_cap",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytaskexecution",
            constraint=models.UniqueConstraint(
                fields=("workflow_run_namespace",), name="ray_task_wf_run_ns_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="raytaskexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("workflow_run_namespace__isnull", True),
                    models.Q(
                        ("workflow_run_namespace__gte", 1),
                        ("workflow_run_namespace__lte", 9223372036854775807),
                    ),
                    _connector="OR",
                ),
                name="ray_task_wf_run_ns_range",
            ),
        ),
    ]
