# Generated by Django 6.0.7 on 2026-08-09 17:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _seed_protocol_rollout_state(apps, schema_editor) -> None:
    legacy_token = apps.get_model("django_ray", "LegacyWorkerAdmissionToken")
    protocol_policy = apps.get_model("django_ray", "TaskExecutionProtocolPolicy")
    legacy_token.objects.using(schema_editor.connection.alias).create(singleton_key=1)
    protocol_policy.objects.using(schema_editor.connection.alias).create(
        singleton_key=1,
        schema_version=1,
        active_write_protocol_version=1,
        legacy_worker_admission_enabled=True,
        revision=1,
        updated_at=django.utils.timezone.now(),
    )


def _unseed_protocol_rollout_state(apps, schema_editor) -> None:
    protocol_policy = apps.get_model("django_ray", "TaskExecutionProtocolPolicy")
    legacy_token = apps.get_model("django_ray", "LegacyWorkerAdmissionToken")
    protocol_policy.objects.using(schema_editor.connection.alias).filter(singleton_key=1).delete()
    legacy_token.objects.using(schema_editor.connection.alias).filter(singleton_key=1).delete()


def _install_postgresql_protocol_fences(schema_editor) -> None:
    quote = schema_editor.quote_name
    execution_table = quote("django_ray_raytaskexecution")
    attempt_table = quote("django_ray_taskattempt")
    lease_table = quote("django_ray_taskworkerlease")
    policy_table = quote("django_ray_taskexecutionprotocolpolicy")
    token_table = quote("django_ray_legacyworkeradmissiontoken")

    statements = (
        f"""
        CREATE FUNCTION django_ray_guard_legacy_execution_0019()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF NEW.metadata_schema_version = 0 THEN
                PERFORM 1
                FROM {policy_table}
                WHERE singleton_key = 1
                  AND schema_version = 1
                  AND legacy_worker_admission_enabled
                FOR SHARE;
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'django-ray legacy execution admission is closed'
                        USING ERRCODE = '23514';
                END IF;

                PERFORM 1
                FROM {token_table}
                WHERE singleton_key = 1
                FOR KEY SHARE;
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'django-ray legacy execution admission token is missing'
                        USING ERRCODE = '23514';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        """
        CREATE FUNCTION django_ray_guard_execution_immutable_0019()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF NEW.metadata_schema_version IS DISTINCT FROM OLD.metadata_schema_version
               OR NEW.execution_protocol_version IS DISTINCT FROM OLD.execution_protocol_version
               OR NEW.created_with_django_ray_version
                  IS DISTINCT FROM OLD.created_with_django_ray_version THEN
                RAISE EXCEPTION 'django-ray execution protocol metadata is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        """
        CREATE FUNCTION django_ray_guard_attempt_immutable_0019()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF NEW.execution_protocol_version IS DISTINCT FROM OLD.execution_protocol_version
               OR NEW.managed_with_django_ray_version
                  IS DISTINCT FROM OLD.managed_with_django_ray_version
               OR NEW.executor_django_ray_version
                  IS DISTINCT FROM OLD.executor_django_ray_version THEN
                RAISE EXCEPTION 'django-ray archived attempt protocol provenance is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE FUNCTION django_ray_guard_legacy_lease_0019()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF NEW.capability_schema_version = 0 AND NEW.is_active THEN
                PERFORM 1
                FROM {policy_table}
                WHERE singleton_key = 1
                  AND schema_version = 1
                  AND legacy_worker_admission_enabled
                FOR SHARE;
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'django-ray legacy worker admission is closed'
                        USING ERRCODE = '23514';
                END IF;

                IF NEW.legacy_admission_token_id IS DISTINCT FROM 1 THEN
                    RAISE EXCEPTION 'django-ray active legacy worker lacks its admission token'
                        USING ERRCODE = '23514';
                END IF;
                PERFORM 1
                FROM {token_table}
                WHERE singleton_key = NEW.legacy_admission_token_id
                FOR KEY SHARE;
                IF NOT FOUND THEN
                    RAISE EXCEPTION 'django-ray legacy worker admission token is missing'
                        USING ERRCODE = '23514';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        """
        CREATE FUNCTION django_ray_guard_lease_capability_0019()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF NEW.capability_schema_version IS DISTINCT FROM OLD.capability_schema_version
               OR NEW.django_ray_version IS DISTINCT FROM OLD.django_ray_version
               OR NEW.min_supported_execution_protocol_version
                  IS DISTINCT FROM OLD.min_supported_execution_protocol_version
               OR NEW.max_supported_execution_protocol_version
                  IS DISTINCT FROM OLD.max_supported_execution_protocol_version THEN
                RAISE EXCEPTION 'django-ray worker lease capability is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE FUNCTION django_ray_guard_task_owner_0019()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF NEW.claimed_by_worker IS NULL
               OR NEW.state NOT IN ('RUNNING', 'CANCELLING') THEN
                RETURN NEW;
            END IF;

            IF OLD.state IN ('RUNNING', 'CANCELLING')
               AND NEW.claimed_by_worker IS NOT DISTINCT FROM OLD.claimed_by_worker THEN
                RETURN NEW;
            END IF;

            PERFORM 1
            FROM {policy_table}
            WHERE singleton_key = 1
              AND schema_version = 1
            FOR SHARE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'django-ray execution protocol policy is unavailable'
                    USING ERRCODE = '23514';
            END IF;

            -- Keep the initial v1/open rollout behaviorally dormant. Existing
            -- recovery paths may rewrite intentionally stale owner identities;
            -- the capability fence becomes normative for future protocols or
            -- after legacy admission closes.
            IF NEW.execution_protocol_version = 1 AND EXISTS (
                SELECT 1
                FROM {policy_table}
                WHERE singleton_key = 1
                  AND schema_version = 1
                  AND legacy_worker_admission_enabled
            ) THEN
                RETURN NEW;
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM {lease_table} AS lease
                JOIN {policy_table} AS policy
                  ON policy.singleton_key = 1
                 AND policy.schema_version = 1
                WHERE lease.worker_id = NEW.claimed_by_worker
                  AND lease.is_active
                  AND (
                      (
                          lease.capability_schema_version = 0
                          AND lease.legacy_admission_token_id = 1
                          AND policy.legacy_worker_admission_enabled
                          AND NEW.execution_protocol_version = 1
                      )
                      OR (
                          lease.capability_schema_version = 1
                          AND lease.legacy_admission_token_id IS NULL
                          AND lease.min_supported_execution_protocol_version
                              <= NEW.execution_protocol_version
                          AND lease.max_supported_execution_protocol_version
                              >= NEW.execution_protocol_version
                      )
                  )
            ) THEN
                RAISE EXCEPTION 'django-ray task owner does not support the execution protocol'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE TRIGGER ray_exec_legacy_insert_0019
        BEFORE INSERT ON {execution_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_legacy_execution_0019()
        """,
        f"""
        CREATE TRIGGER ray_exec_immutable_0019
        BEFORE UPDATE OF metadata_schema_version,
                         execution_protocol_version,
                         created_with_django_ray_version
        ON {execution_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_execution_immutable_0019()
        """,
        f"""
        CREATE TRIGGER ray_exec_owner_update_0019
        BEFORE UPDATE OF state, claimed_by_worker, execution_protocol_version
        ON {execution_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_task_owner_0019()
        """,
        f"""
        CREATE TRIGGER ray_attempt_immutable_0019
        BEFORE UPDATE OF execution_protocol_version,
                         managed_with_django_ray_version,
                         executor_django_ray_version
        ON {attempt_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_attempt_immutable_0019()
        """,
        f"""
        CREATE TRIGGER ray_lease_admission_insert_0019
        BEFORE INSERT ON {lease_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_legacy_lease_0019()
        """,
        f"""
        CREATE TRIGGER ray_lease_admission_update_0019
        BEFORE UPDATE ON {lease_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_legacy_lease_0019()
        """,
        f"""
        CREATE TRIGGER ray_lease_capability_immutable_0019
        BEFORE UPDATE OF capability_schema_version,
                         django_ray_version,
                         min_supported_execution_protocol_version,
                         max_supported_execution_protocol_version
        ON {lease_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_lease_capability_0019()
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _install_sqlite_protocol_fences(schema_editor) -> None:
    quote = schema_editor.quote_name
    execution_table = quote("django_ray_raytaskexecution")
    attempt_table = quote("django_ray_taskattempt")
    lease_table = quote("django_ray_taskworkerlease")
    policy_table = quote("django_ray_taskexecutionprotocolpolicy")
    token_table = quote("django_ray_legacyworkeradmissiontoken")

    statements = (
        f"""
        CREATE TRIGGER ray_exec_legacy_insert_0019
        BEFORE INSERT ON {execution_table}
        FOR EACH ROW
        WHEN NEW.metadata_schema_version = 0
         AND NOT EXISTS (
             SELECT 1
             FROM {policy_table} AS policy
             JOIN {token_table} AS token ON token.singleton_key = 1
             WHERE policy.singleton_key = 1
               AND policy.schema_version = 1
               AND policy.legacy_worker_admission_enabled = 1
         )
        BEGIN
            SELECT RAISE(ABORT, 'django-ray legacy execution admission is closed');
        END
        """,
        f"""
        CREATE TRIGGER ray_exec_immutable_0019
        BEFORE UPDATE OF metadata_schema_version,
                         execution_protocol_version,
                         created_with_django_ray_version
        ON {execution_table}
        FOR EACH ROW
        WHEN NEW.metadata_schema_version IS NOT OLD.metadata_schema_version
          OR NEW.execution_protocol_version IS NOT OLD.execution_protocol_version
          OR NEW.created_with_django_ray_version IS NOT OLD.created_with_django_ray_version
        BEGIN
            SELECT RAISE(
                ABORT,
                'django-ray execution protocol metadata is immutable'
            );
        END
        """,
        f"""
        CREATE TRIGGER ray_attempt_immutable_0019
        BEFORE UPDATE OF execution_protocol_version,
                         managed_with_django_ray_version,
                         executor_django_ray_version
        ON {attempt_table}
        FOR EACH ROW
        WHEN NEW.execution_protocol_version IS NOT OLD.execution_protocol_version
          OR NEW.managed_with_django_ray_version IS NOT OLD.managed_with_django_ray_version
          OR NEW.executor_django_ray_version IS NOT OLD.executor_django_ray_version
        BEGIN
            SELECT RAISE(ABORT, 'django-ray archived attempt protocol provenance is immutable');
        END
        """,
        f"""
        CREATE TRIGGER ray_lease_admission_insert_0019
        BEFORE INSERT ON {lease_table}
        FOR EACH ROW
        WHEN NEW.capability_schema_version = 0
         AND NEW.is_active = 1
         AND NOT EXISTS (
             SELECT 1
             FROM {policy_table} AS policy
             JOIN {token_table} AS token
               ON token.singleton_key = NEW.legacy_admission_token_id
             WHERE policy.singleton_key = 1
               AND policy.schema_version = 1
               AND policy.legacy_worker_admission_enabled = 1
               AND NEW.legacy_admission_token_id = 1
         )
        BEGIN
            SELECT RAISE(ABORT, 'django-ray legacy worker admission is closed');
        END
        """,
        f"""
        CREATE TRIGGER ray_lease_admission_update_0019
        BEFORE UPDATE ON {lease_table}
        FOR EACH ROW
        WHEN NEW.capability_schema_version = 0
         AND NEW.is_active = 1
         AND NOT EXISTS (
             SELECT 1
             FROM {policy_table} AS policy
             JOIN {token_table} AS token
               ON token.singleton_key = NEW.legacy_admission_token_id
             WHERE policy.singleton_key = 1
               AND policy.schema_version = 1
               AND policy.legacy_worker_admission_enabled = 1
               AND NEW.legacy_admission_token_id = 1
         )
        BEGIN
            SELECT RAISE(ABORT, 'django-ray legacy worker admission is closed');
        END
        """,
        f"""
        CREATE TRIGGER ray_lease_capability_immutable_0019
        BEFORE UPDATE OF capability_schema_version,
                         django_ray_version,
                         min_supported_execution_protocol_version,
                         max_supported_execution_protocol_version
        ON {lease_table}
        FOR EACH ROW
        WHEN NEW.capability_schema_version IS NOT OLD.capability_schema_version
          OR NEW.django_ray_version IS NOT OLD.django_ray_version
          OR NEW.min_supported_execution_protocol_version
             IS NOT OLD.min_supported_execution_protocol_version
          OR NEW.max_supported_execution_protocol_version
             IS NOT OLD.max_supported_execution_protocol_version
        BEGIN
            SELECT RAISE(ABORT, 'django-ray worker lease capability is immutable');
        END
        """,
        f"""
        CREATE TRIGGER ray_exec_owner_update_0019
        BEFORE UPDATE OF state, claimed_by_worker, execution_protocol_version
        ON {execution_table}
        FOR EACH ROW
        WHEN NEW.claimed_by_worker IS NOT NULL
         AND NEW.state IN ('RUNNING', 'CANCELLING')
         AND (
             OLD.state NOT IN ('RUNNING', 'CANCELLING')
             OR NEW.claimed_by_worker IS NOT OLD.claimed_by_worker
         )
         AND NOT (
             NEW.execution_protocol_version = 1
             AND EXISTS (
                 SELECT 1
                 FROM {policy_table}
                 WHERE singleton_key = 1
                   AND schema_version = 1
                   AND legacy_worker_admission_enabled = 1
             )
         )
         AND NOT EXISTS (
             SELECT 1
             FROM {lease_table} AS lease
             JOIN {policy_table} AS policy
               ON policy.singleton_key = 1
              AND policy.schema_version = 1
             WHERE lease.worker_id = NEW.claimed_by_worker
               AND lease.is_active = 1
               AND (
                   (
                       lease.capability_schema_version = 0
                       AND lease.legacy_admission_token_id = 1
                       AND policy.legacy_worker_admission_enabled = 1
                       AND NEW.execution_protocol_version = 1
                   )
                   OR (
                       lease.capability_schema_version = 1
                       AND lease.legacy_admission_token_id IS NULL
                       AND lease.min_supported_execution_protocol_version
                           <= NEW.execution_protocol_version
                       AND lease.max_supported_execution_protocol_version
                           >= NEW.execution_protocol_version
                   )
               )
         )
        BEGIN
            SELECT RAISE(
                ABORT,
                'django-ray task owner does not support the execution protocol'
            );
        END
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _install_protocol_fences(apps, schema_editor) -> None:
    del apps
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        _install_postgresql_protocol_fences(schema_editor)
    elif vendor == "sqlite":
        _install_sqlite_protocol_fences(schema_editor)
    else:
        raise RuntimeError(
            "django-ray execution-protocol fencing supports only SQLite and PostgreSQL"
        )


def _remove_protocol_fences(apps, schema_editor) -> None:
    del apps
    quote = schema_editor.quote_name
    execution_table = quote("django_ray_raytaskexecution")
    attempt_table = quote("django_ray_taskattempt")
    lease_table = quote("django_ray_taskworkerlease")
    trigger_tables = {
        "ray_exec_legacy_insert_0019": execution_table,
        "ray_exec_immutable_0019": execution_table,
        "ray_exec_owner_update_0019": execution_table,
        "ray_attempt_immutable_0019": attempt_table,
        "ray_lease_admission_insert_0019": lease_table,
        "ray_lease_admission_update_0019": lease_table,
        "ray_lease_capability_immutable_0019": lease_table,
    }
    if schema_editor.connection.vendor == "postgresql":
        for trigger, table in trigger_tables.items():
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {quote(trigger)} ON {table}")
        for function in (
            "django_ray_guard_legacy_execution_0019",
            "django_ray_guard_execution_immutable_0019",
            "django_ray_guard_attempt_immutable_0019",
            "django_ray_guard_legacy_lease_0019",
            "django_ray_guard_lease_capability_0019",
            "django_ray_guard_task_owner_0019",
        ):
            schema_editor.execute(f"DROP FUNCTION IF EXISTS {quote(function)}()")
    elif schema_editor.connection.vendor == "sqlite":
        for trigger in trigger_tables:
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {quote(trigger)}")
    else:
        raise RuntimeError(
            "django-ray execution-protocol fencing supports only SQLite and PostgreSQL"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0018_workflow_run_allocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyWorkerAdmissionToken",
            fields=[
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        db_default=1, default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Legacy Worker Admission Token",
                "verbose_name_plural": "Legacy Worker Admission Tokens",
            },
        ),
        migrations.CreateModel(
            name="TaskExecutionProtocolPolicy",
            fields=[
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        db_default=1, default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(
                        db_default=1,
                        default=1,
                        editable=False,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "active_write_protocol_version",
                    models.PositiveSmallIntegerField(
                        db_default=1,
                        default=1,
                        editable=False,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "legacy_worker_admission_enabled",
                    models.BooleanField(db_default=True, default=True, editable=False),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        db_default=1,
                        default=1,
                        editable=False,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            options={
                "verbose_name": "Task Execution Protocol Policy",
                "verbose_name_plural": "Task Execution Protocol Policies",
            },
        ),
        migrations.AddField(
            model_name="raytaskexecution",
            name="created_with_django_ray_version",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Diagnostic django-ray package version that created this task",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="raytaskexecution",
            name="execution_protocol_version",
            field=models.PositiveSmallIntegerField(
                db_default=1,
                db_index=True,
                default=1,
                editable=False,
                help_text="Immutable durable execution protocol selected when the task was created",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="raytaskexecution",
            name="executor_django_ray_version",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Diagnostic django-ray package version that executed the current attempt",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="raytaskexecution",
            name="managed_with_django_ray_version",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Diagnostic django-ray package version managing the current attempt",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="raytaskexecution",
            name="metadata_schema_version",
            field=models.PositiveSmallIntegerField(
                db_default=0,
                default=1,
                editable=False,
                help_text="Schema version for execution metadata stored on this row",
                validators=[django.core.validators.MaxValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="execution_protocol_version",
            field=models.PositiveSmallIntegerField(
                db_default=1,
                default=1,
                editable=False,
                help_text="Durable execution protocol archived for this attempt",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="executor_django_ray_version",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Diagnostic django-ray package version that executed this attempt",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="managed_with_django_ray_version",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Diagnostic django-ray package version that managed this attempt",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taskworkerlease",
            name="capability_schema_version",
            field=models.PositiveSmallIntegerField(
                db_default=0,
                default=0,
                editable=False,
                help_text="Worker capability advertisement schema; zero identifies a legacy lease",
            ),
        ),
        migrations.AddField(
            model_name="taskworkerlease",
            name="django_ray_version",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Diagnostic django-ray package version advertised by this worker",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taskworkerlease",
            name="max_supported_execution_protocol_version",
            field=models.PositiveSmallIntegerField(
                blank=True,
                editable=False,
                help_text="Highest durable execution protocol explicitly supported by this worker",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="taskworkerlease",
            name="min_supported_execution_protocol_version",
            field=models.PositiveSmallIntegerField(
                blank=True,
                editable=False,
                help_text="Lowest durable execution protocol explicitly supported by this worker",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddConstraint(
            model_name="raytaskexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("metadata_schema_version__in", (0, 1))),
                name="ray_task_metadata_schema_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytaskexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("execution_protocol_version__gte", 1)),
                name="ray_task_protocol_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("execution_protocol_version__gte", 1)),
                name="ray_attempt_protocol_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyworkeradmissiontoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("singleton_key", 1)), name="ray_legacy_admission_singleton"
            ),
        ),
        migrations.RunPython(
            _seed_protocol_rollout_state,
            _unseed_protocol_rollout_state,
        ),
        migrations.AddField(
            model_name="taskworkerlease",
            name="legacy_admission_token",
            field=models.ForeignKey(
                blank=True,
                db_default=1,
                default=1,
                editable=False,
                help_text="Admission token held only by a legacy capability-unaware worker lease",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="worker_leases",
                to="django_ray.legacyworkeradmissiontoken",
            ),
        ),
        migrations.AddIndex(
            model_name="taskworkerlease",
            index=models.Index(
                fields=[
                    "is_active",
                    "capability_schema_version",
                    "min_supported_execution_protocol_version",
                    "max_supported_execution_protocol_version",
                ],
                name="ray_worker_protocol_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskworkerlease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("capability_schema_version", 0),
                        ("django_ray_version__isnull", True),
                        ("max_supported_execution_protocol_version__isnull", True),
                        ("min_supported_execution_protocol_version__isnull", True),
                        models.Q(
                            ("is_active", False),
                            ("legacy_admission_token__isnull", False),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        ("capability_schema_version", 1),
                        ("legacy_admission_token__isnull", True),
                        (
                            "max_supported_execution_protocol_version__gte",
                            models.F("min_supported_execution_protocol_version"),
                        ),
                        ("max_supported_execution_protocol_version__isnull", False),
                        ("min_supported_execution_protocol_version__gte", 1),
                        ("min_supported_execution_protocol_version__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ray_worker_capability_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskexecutionprotocolpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("singleton_key", 1)), name="ray_protocol_policy_singleton"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskexecutionprotocolpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version", 1)), name="ray_protocol_policy_schema"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskexecutionprotocolpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("active_write_protocol_version__gte", 1)),
                name="ray_protocol_policy_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskexecutionprotocolpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="ray_protocol_policy_revision"
            ),
        ),
        migrations.RunPython(
            _install_protocol_fences,
            _remove_protocol_fences,
        ),
    ]
