# Generated by Django 6.0.7 on 2026-08-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0020_legacy_open_rollback_fence"),
    ]

    operations = [
        migrations.AddField(
            model_name="raytaskexecution",
            name="ray_job_request_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Reference to the durable Ray Job submission request",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taskinputpayload",
            name="payload_kind",
            field=models.CharField(
                choices=[
                    ("task_input", "Task input"),
                    ("ray_job_request", "Ray Job request"),
                ],
                db_default="task_input",
                default="task_input",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="taskinputpayload",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_kind__in", ("task_input", "ray_job_request"))),
                name="ray_input_payload_kind_valid",
            ),
        ),
    ]
