# Generated by Django 6.0.7 on 2026-08-15 09:32

import datetime

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models

_EXPECTATION_MAX_BYTES = 16 * 1024
_ATTESTATION_MAX_BYTES = 1024 * 1024
_DIGEST_SUFFIX_GLOB = "*[^0-9a-f]*"


def _target_tables(apps, schema_editor) -> tuple[str, str, str]:
    quote = schema_editor.quote_name
    target = apps.get_model("django_ray", "RayTarget")
    policy = apps.get_model("django_ray", "RayTargetPolicyRevision")
    attestation = apps.get_model("django_ray", "RayTargetAttestationRevision")
    return (
        quote(target._meta.db_table),
        quote(policy._meta.db_table),
        quote(attestation._meta.db_table),
    )


def _install_postgresql_fences(apps, schema_editor) -> None:
    target_table, policy_table, attestation_table = _target_tables(apps, schema_editor)
    statements = (
        """
        CREATE FUNCTION django_ray_guard_target_0022()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF char_length(NEW.target_key) NOT BETWEEN 1 AND 128
               OR substring(NEW.target_key FROM 1 FOR 1) !~ '^[a-z0-9]$'
               OR NEW.target_key ~ '[^a-z0-9_.-]'
               OR char_length(NEW.cluster_session) NOT BETWEEN 9 AND 256
               OR left(NEW.cluster_session, 8) <> 'session_'
               OR substring(NEW.cluster_session FROM 9 FOR 1) !~ '^[A-Za-z0-9]$'
               OR substring(NEW.cluster_session FROM 9) ~ '[^A-Za-z0-9_.-]'
               OR char_length(NEW.python_implementation) NOT BETWEEN 1 AND 64
               OR substring(NEW.python_implementation FROM 1 FOR 1) !~ '^[a-z]$'
               OR NEW.python_implementation ~ '[^a-z0-9_.-]' THEN
                RAISE EXCEPTION 'django-ray Ray target identity is invalid'
                    USING ERRCODE = '23514';
            END IF;
            IF TG_OP = 'UPDATE' AND NEW IS DISTINCT FROM OLD THEN
                RAISE EXCEPTION 'django-ray Ray target is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        """
        CREATE FUNCTION django_ray_guard_tpolicy_0022()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF octet_length(NEW.expectation_json) NOT BETWEEN 1 AND 16384
               OR char_length(NEW.expectation_digest) <> 71
               OR left(NEW.expectation_digest, 7) <> 'sha256:'
               OR substring(NEW.expectation_digest FROM 8) ~ '[^0-9a-f]' THEN
                RAISE EXCEPTION 'django-ray Ray target policy payload is invalid'
                    USING ERRCODE = '23514';
            END IF;
            IF TG_OP = 'UPDATE' AND NEW IS DISTINCT FROM OLD THEN
                RAISE EXCEPTION 'django-ray Ray target policy revision is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        """
        CREATE FUNCTION django_ray_guard_tattest_0022()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF octet_length(NEW.attestation_json) NOT BETWEEN 1 AND 1048576
               OR char_length(NEW.expectation_digest) <> 71
               OR left(NEW.expectation_digest, 7) <> 'sha256:'
               OR substring(NEW.expectation_digest FROM 8) ~ '[^0-9a-f]'
               OR char_length(NEW.membership_digest) <> 71
               OR left(NEW.membership_digest, 7) <> 'sha256:'
               OR substring(NEW.membership_digest FROM 8) ~ '[^0-9a-f]'
               OR char_length(NEW.attestation_digest) <> 71
               OR left(NEW.attestation_digest, 7) <> 'sha256:'
               OR substring(NEW.attestation_digest FROM 8) ~ '[^0-9a-f]' THEN
                RAISE EXCEPTION 'django-ray Ray target attestation payload is invalid'
                    USING ERRCODE = '23514';
            END IF;
            IF TG_OP = 'UPDATE' AND NEW IS DISTINCT FROM OLD THEN
                RAISE EXCEPTION 'django-ray Ray target attestation revision is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE TRIGGER ray_target_guard_0022
        BEFORE INSERT OR UPDATE ON {target_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_target_0022()
        """,
        f"""
        CREATE TRIGGER ray_tpolicy_guard_0022
        BEFORE INSERT OR UPDATE ON {policy_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_tpolicy_0022()
        """,
        f"""
        CREATE TRIGGER ray_tattest_guard_0022
        BEFORE INSERT OR UPDATE ON {attestation_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_tattest_0022()
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _sqlite_material_change(columns: tuple[str, ...]) -> str:
    return "\n          OR ".join(f"NEW.{column} IS NOT OLD.{column}" for column in columns)


def _sqlite_digest_invalid(column: str) -> str:
    return (
        f"typeof(NEW.{column}) != 'text'\n"
        f"          OR instr(NEW.{column}, char(0)) != 0\n"
        f"          OR length(NEW.{column}) != 71\n"
        f"          OR substr(NEW.{column}, 1, 7) != 'sha256:'\n"
        f"          OR substr(NEW.{column}, 8) GLOB '{_DIGEST_SUFFIX_GLOB}'"
    )


def _sqlite_datetime_invalid(column: str) -> str:
    value = f"NEW.{column}"
    base = f"substr({value}, 1, 19)"
    return (
        f"typeof({value}) != 'text'\n"
        f"          OR instr({value}, char(0)) != 0\n"
        f"          OR length({value}) NOT IN (19, 26)\n"
        f"          OR substr({value}, 5, 1) != '-'\n"
        f"          OR substr({value}, 8, 1) != '-'\n"
        f"          OR substr({value}, 11, 1) != ' '\n"
        f"          OR substr({value}, 14, 1) != ':'\n"
        f"          OR substr({value}, 17, 1) != ':'\n"
        f"          OR substr({value}, 1, 4) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 6, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 9, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 12, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 15, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 18, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 1, 4) = '0000'\n"
        f"          OR CAST(substr({value}, 12, 2) AS INTEGER) NOT BETWEEN 0 AND 23\n"
        f"          OR datetime({base}) IS NULL\n"
        f"          OR strftime('%Y-%m-%d %H:%M:%S', {base}) != {base}\n"
        f"          OR (length({value}) = 26 AND (\n"
        f"                 substr({value}, 20, 1) != '.'\n"
        f"                 OR substr({value}, 21, 6) GLOB '*[^0-9]*'\n"
        f"             ))"
    )


def _install_sqlite_fences(apps, schema_editor) -> None:
    target_table, policy_table, attestation_table = _target_tables(apps, schema_editor)
    target_changes = _sqlite_material_change(
        (
            "target_key",
            "runner_family",
            "cluster_session",
            "ray_major",
            "ray_minor",
            "ray_patch",
            "python_implementation",
            "python_major",
            "python_minor",
            "python_patch",
            "created_at",
        )
    )
    policy_changes = _sqlite_material_change(
        (
            "id",
            "target_id",
            "revision",
            "desired_state",
            "expectation_schema_version",
            "expectation_json",
            "expectation_digest",
            "created_at",
        )
    )
    attestation_changes = _sqlite_material_change(
        (
            "id",
            "policy_id",
            "revision",
            "attestation_schema_version",
            "attestation_json",
            "expectation_digest",
            "membership_digest",
            "attestation_digest",
            "observed_at",
            "expires_at",
            "recorded_at",
        )
    )
    statements = (
        f"""
        CREATE TRIGGER ray_target_insert_0022
        BEFORE INSERT ON {target_table}
        FOR EACH ROW
        WHEN typeof(NEW.target_key) != 'text'
          OR instr(NEW.target_key, char(0)) != 0
          OR length(NEW.target_key) NOT BETWEEN 1 AND 128
          OR substr(NEW.target_key, 1, 1) NOT GLOB '[a-z0-9]'
          OR NEW.target_key GLOB '*[^a-z0-9_.-]*'
          OR typeof(NEW.runner_family) != 'text'
          OR instr(NEW.runner_family, char(0)) != 0
          OR typeof(NEW.cluster_session) != 'text'
          OR instr(NEW.cluster_session, char(0)) != 0
          OR length(NEW.cluster_session) NOT BETWEEN 9 AND 256
          OR substr(NEW.cluster_session, 1, 8) != 'session_'
          OR substr(NEW.cluster_session, 9, 1) NOT GLOB '[A-Za-z0-9]'
          OR substr(NEW.cluster_session, 9) GLOB '*[^A-Za-z0-9_.-]*'
          OR typeof(NEW.python_implementation) != 'text'
          OR instr(NEW.python_implementation, char(0)) != 0
          OR length(NEW.python_implementation) NOT BETWEEN 1 AND 64
          OR substr(NEW.python_implementation, 1, 1) NOT GLOB '[a-z]'
          OR NEW.python_implementation GLOB '*[^a-z0-9_.-]*'
          OR typeof(NEW.ray_major) != 'integer'
          OR typeof(NEW.ray_minor) != 'integer'
          OR typeof(NEW.ray_patch) != 'integer'
          OR typeof(NEW.python_major) != 'integer'
          OR typeof(NEW.python_minor) != 'integer'
          OR typeof(NEW.python_patch) != 'integer'
          OR {_sqlite_datetime_invalid("created_at")}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray target identity is invalid');
        END
        """,
        f"""
        CREATE TRIGGER ray_target_update_0022
        BEFORE UPDATE ON {target_table}
        FOR EACH ROW
        WHEN {target_changes}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray target is immutable');
        END
        """,
        f"""
        CREATE TRIGGER ray_tpolicy_insert_0022
        BEFORE INSERT ON {policy_table}
        FOR EACH ROW
        WHEN typeof(NEW.target_id) != 'text'
          OR instr(NEW.target_id, char(0)) != 0
          OR typeof(NEW.revision) != 'integer'
          OR typeof(NEW.expectation_schema_version) != 'integer'
          OR typeof(NEW.desired_state) != 'text'
          OR instr(NEW.desired_state, char(0)) != 0
          OR typeof(NEW.expectation_json) != 'text'
          OR instr(NEW.expectation_json, char(0)) != 0
          OR length(CAST(NEW.expectation_json AS BLOB))
             NOT BETWEEN 1 AND {_EXPECTATION_MAX_BYTES}
          OR {_sqlite_digest_invalid("expectation_digest")}
          OR {_sqlite_datetime_invalid("created_at")}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray target policy payload is invalid');
        END
        """,
        f"""
        CREATE TRIGGER ray_tpolicy_update_0022
        BEFORE UPDATE ON {policy_table}
        FOR EACH ROW
        WHEN {policy_changes}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray target policy revision is immutable');
        END
        """,
        f"""
        CREATE TRIGGER ray_tattest_insert_0022
        BEFORE INSERT ON {attestation_table}
        FOR EACH ROW
        WHEN typeof(NEW.policy_id) != 'integer'
          OR typeof(NEW.revision) != 'integer'
          OR typeof(NEW.attestation_schema_version) != 'integer'
          OR typeof(NEW.attestation_json) != 'text'
          OR instr(NEW.attestation_json, char(0)) != 0
          OR length(CAST(NEW.attestation_json AS BLOB))
             NOT BETWEEN 1 AND {_ATTESTATION_MAX_BYTES}
          OR {_sqlite_digest_invalid("expectation_digest")}
          OR {_sqlite_digest_invalid("membership_digest")}
          OR {_sqlite_digest_invalid("attestation_digest")}
          OR {_sqlite_datetime_invalid("observed_at")}
          OR {_sqlite_datetime_invalid("expires_at")}
          OR {_sqlite_datetime_invalid("recorded_at")}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray target attestation payload is invalid');
        END
        """,
        f"""
        CREATE TRIGGER ray_tattest_update_0022
        BEFORE UPDATE ON {attestation_table}
        FOR EACH ROW
        WHEN {attestation_changes}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray target attestation revision is immutable');
        END
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _install_target_persistence_fences(apps, schema_editor) -> None:
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        _install_postgresql_fences(apps, schema_editor)
    elif vendor == "sqlite":
        _install_sqlite_fences(apps, schema_editor)
    else:
        raise RuntimeError("django-ray Ray target persistence supports only SQLite and PostgreSQL")


def _remove_target_persistence_fences(apps, schema_editor) -> None:
    quote = schema_editor.quote_name
    target_table, policy_table, attestation_table = _target_tables(apps, schema_editor)
    trigger_tables = {
        "ray_target_guard_0022": target_table,
        "ray_tpolicy_guard_0022": policy_table,
        "ray_tattest_guard_0022": attestation_table,
    }
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        for trigger, table in trigger_tables.items():
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {quote(trigger)} ON {table}")
        for function in (
            "django_ray_guard_target_0022",
            "django_ray_guard_tpolicy_0022",
            "django_ray_guard_tattest_0022",
        ):
            schema_editor.execute(f"DROP FUNCTION IF EXISTS {quote(function)}()")
    elif vendor == "sqlite":
        for trigger in (
            "ray_target_insert_0022",
            "ray_target_update_0022",
            "ray_tpolicy_insert_0022",
            "ray_tpolicy_update_0022",
            "ray_tattest_insert_0022",
            "ray_tattest_update_0022",
        ):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {quote(trigger)}")
    else:
        raise RuntimeError("django-ray Ray target persistence supports only SQLite and PostgreSQL")


def _guard_empty_target_persistence(apps, schema_editor) -> None:
    target_table, policy_table, attestation_table = _target_tables(apps, schema_editor)
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            f"LOCK TABLE {target_table}, {policy_table}, {attestation_table} "
            "IN ACCESS EXCLUSIVE MODE"
        )
    elif vendor == "sqlite":
        schema_editor.execute(f"UPDATE {target_table} SET target_key = target_key WHERE 0")
    else:
        raise RuntimeError("django-ray Ray target persistence supports only SQLite and PostgreSQL")

    alias = schema_editor.connection.alias
    model_names = (
        "RayTargetAttestationRevision",
        "RayTargetPolicyRevision",
        "RayTarget",
    )
    if any(
        apps.get_model("django_ray", model_name).objects.using(alias).exists()
        for model_name in model_names
    ):
        raise RuntimeError(
            "django-ray Ray target persistence rollback requires all target tables to be empty"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0021_ray_job_request_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="RayTarget",
            fields=[
                (
                    "target_key",
                    models.CharField(
                        editable=False,
                        help_text="Stable operator key for this Ray target",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical Ray target key.",
                                regex="\\A[a-z0-9][a-z0-9_.-]{0,127}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "runner_family",
                    models.CharField(
                        choices=[("ray_core", "ray_core"), ("ray_job", "ray_job")],
                        editable=False,
                        help_text="Ray submission family bound to this target",
                        max_length=16,
                    ),
                ),
                (
                    "cluster_session",
                    models.CharField(
                        editable=False,
                        help_text=(
                            "Public Ray session name identifying the exact cluster instance"
                        ),
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical Ray cluster session name.",
                                regex=("\\Asession_[A-Za-z0-9][A-Za-z0-9_.-]{0,247}\\Z"),
                            )
                        ],
                    ),
                ),
                (
                    "ray_major",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9223372036854775807),
                        ],
                    ),
                ),
                (
                    "ray_minor",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "ray_patch",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "python_implementation",
                    models.CharField(
                        editable=False,
                        help_text="Normalized Python implementation identifier",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Value must be a normalized Python implementation identifier."
                                ),
                                regex="\\A[a-z][a-z0-9_.-]{0,63}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "python_major",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9223372036854775807),
                        ],
                    ),
                ),
                (
                    "python_minor",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "python_patch",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            options={
                "verbose_name": "Ray Target",
                "verbose_name_plural": "Ray Targets",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(runner_family__in=("ray_core", "ray_job")),
                        name="ray_target_runner_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            python_major__gte=1,
                            python_major__lte=9223372036854775807,
                            python_minor__gte=0,
                            python_minor__lte=9223372036854775807,
                            python_patch__gte=0,
                            python_patch__lte=9223372036854775807,
                            ray_major__gte=1,
                            ray_major__lte=9223372036854775807,
                            ray_minor__gte=0,
                            ray_minor__lte=9223372036854775807,
                            ray_patch__gte=0,
                            ray_patch__lte=9223372036854775807,
                        ),
                        name="ray_target_runtime_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("runner_family", "cluster_session"),
                        name="ray_target_instance_uniq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RayTargetPolicyRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9223372036854775807),
                        ],
                    ),
                ),
                (
                    "desired_state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("draining", "Draining"),
                            ("retired", "Retired"),
                        ],
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "expectation_schema_version",
                    models.PositiveSmallIntegerField(
                        editable=False,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "expectation_json",
                    models.TextField(
                        editable=False,
                        help_text="Canonical Ray target expectation JSON",
                        validators=[django.core.validators.MaxLengthValidator(16384)],
                    ),
                ),
                (
                    "expectation_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Value must be a canonical tagged lowercase SHA-256 digest."
                                ),
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "target",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policy_revisions",
                        to="django_ray.raytarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ray Target Policy Revision",
                "verbose_name_plural": "Ray Target Policy Revisions",
            },
        ),
        migrations.CreateModel(
            name="RayTargetAttestationRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9223372036854775807),
                        ],
                    ),
                ),
                (
                    "attestation_schema_version",
                    models.PositiveSmallIntegerField(
                        editable=False,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "attestation_json",
                    models.TextField(
                        editable=False,
                        help_text="Canonical Ray cluster attestation JSON",
                        validators=[django.core.validators.MaxLengthValidator(1048576)],
                    ),
                ),
                (
                    "expectation_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Value must be a canonical tagged lowercase SHA-256 digest."
                                ),
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "membership_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Value must be a canonical tagged lowercase SHA-256 digest."
                                ),
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "attestation_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Value must be a canonical tagged lowercase SHA-256 digest."
                                ),
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("observed_at", models.DateTimeField(editable=False)),
                ("expires_at", models.DateTimeField(editable=False)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attestation_revisions",
                        to="django_ray.raytargetpolicyrevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ray Target Attestation Revision",
                "verbose_name_plural": "Ray Target Attestation Revisions",
            },
        ),
        migrations.AddIndex(
            model_name="raytargetpolicyrevision",
            index=models.Index(fields=["target", "-revision"], name="ray_tpolicy_latest_idx"),
        ),
        migrations.AddConstraint(
            model_name="raytargetpolicyrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(expectation_schema_version=1),
                name="ray_tpolicy_schema_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytargetpolicyrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(desired_state__in=["active", "draining", "retired"]),
                name="ray_tpolicy_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytargetpolicyrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(revision__gte=1, revision__lte=9223372036854775807),
                name="ray_tpolicy_revision_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytargetpolicyrevision",
            constraint=models.UniqueConstraint(
                fields=("target", "revision"),
                name="ray_tpolicy_target_rev_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="raytargetattestationrevision",
            index=models.Index(fields=["policy", "-revision"], name="ray_tattest_latest_idx"),
        ),
        migrations.AddIndex(
            model_name="raytargetattestationrevision",
            index=models.Index(fields=["expires_at"], name="ray_tattest_expiry_idx"),
        ),
        migrations.AddConstraint(
            model_name="raytargetattestationrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(attestation_schema_version=1),
                name="ray_tattest_schema_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytargetattestationrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(revision__gte=1, revision__lte=9223372036854775807),
                name="ray_tattest_revision_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytargetattestationrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    expires_at__gt=models.F("observed_at"),
                    expires_at__lte=django.db.models.expressions.CombinedExpression(
                        models.F("observed_at"),
                        "+",
                        models.Value(datetime.timedelta(seconds=3600)),
                    ),
                    recorded_at__gte=models.F("observed_at"),
                    recorded_at__lt=models.F("expires_at"),
                ),
                name="ray_tattest_window_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytargetattestationrevision",
            constraint=models.UniqueConstraint(
                fields=("policy", "revision"),
                name="ray_tattest_policy_rev_uniq",
            ),
        ),
        migrations.RunPython(
            _install_target_persistence_fences,
            _remove_target_persistence_fences,
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            _guard_empty_target_persistence,
        ),
    ]
