# Generated by Django 6.0.7 on 2026-08-15 13:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _binding_table(apps, schema_editor) -> str:
    binding = apps.get_model("django_ray", "RayTaskTargetBinding")
    return schema_editor.quote_name(binding._meta.db_table)


def _sqlite_datetime_invalid(column: str) -> str:
    value = f"NEW.{column}"
    base = f"substr({value}, 1, 19)"
    return (
        f"typeof({value}) != 'text'\n"
        f"          OR instr({value}, char(0)) != 0\n"
        f"          OR length({value}) NOT IN (19, 26)\n"
        f"          OR substr({value}, 5, 1) != '-'\n"
        f"          OR substr({value}, 8, 1) != '-'\n"
        f"          OR substr({value}, 11, 1) != ' '\n"
        f"          OR substr({value}, 14, 1) != ':'\n"
        f"          OR substr({value}, 17, 1) != ':'\n"
        f"          OR substr({value}, 1, 4) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 6, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 9, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 12, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 15, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 18, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 1, 4) = '0000'\n"
        f"          OR CAST(substr({value}, 12, 2) AS INTEGER) NOT BETWEEN 0 AND 23\n"
        f"          OR datetime({base}) IS NULL\n"
        f"          OR strftime('%Y-%m-%d %H:%M:%S', {base}) != {base}\n"
        f"          OR (length({value}) = 26 AND (\n"
        f"                 substr({value}, 20, 1) != '.'\n"
        f"                 OR substr({value}, 21, 6) GLOB '*[^0-9]*'\n"
        f"             ))"
    )


def _install_postgresql_fence(apps, schema_editor) -> None:
    binding_table = _binding_table(apps, schema_editor)
    statements = (
        """
        CREATE FUNCTION django_ray_guard_tbinding_0023()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF NEW.execution_id < 1
               OR NEW.target_policy_id < 1
               OR NEW.schema_version <> 1
               OR NOT isfinite(NEW.created_at)
               OR EXTRACT(YEAR FROM NEW.created_at AT TIME ZONE 'UTC')
                  NOT BETWEEN 1 AND 9999 THEN
                RAISE EXCEPTION 'django-ray Ray task target binding is invalid'
                    USING ERRCODE = '23514';
            END IF;
            IF TG_OP = 'UPDATE' AND NEW IS DISTINCT FROM OLD THEN
                RAISE EXCEPTION 'django-ray Ray task target binding is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE TRIGGER ray_tbinding_guard_0023
        BEFORE INSERT OR UPDATE ON {binding_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_tbinding_0023()
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _install_sqlite_fences(apps, schema_editor) -> None:
    binding_table = _binding_table(apps, schema_editor)
    statements = (
        f"""
        CREATE TRIGGER ray_tbinding_insert_0023
        BEFORE INSERT ON {binding_table}
        FOR EACH ROW
        WHEN typeof(NEW.execution_id) != 'integer'
          OR NEW.execution_id < 1
          OR typeof(NEW.target_policy_id) != 'integer'
          OR NEW.target_policy_id < 1
          OR typeof(NEW.schema_version) != 'integer'
          OR NEW.schema_version != 1
          OR {_sqlite_datetime_invalid("created_at")}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray task target binding is invalid');
        END
        """,
        f"""
        CREATE TRIGGER ray_tbinding_update_0023
        BEFORE UPDATE ON {binding_table}
        FOR EACH ROW
        WHEN NEW.execution_id IS NOT OLD.execution_id
          OR NEW.target_policy_id IS NOT OLD.target_policy_id
          OR NEW.schema_version IS NOT OLD.schema_version
          OR NEW.created_at IS NOT OLD.created_at
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray task target binding is immutable');
        END
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _install_task_target_binding_fences(apps, schema_editor) -> None:
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        _install_postgresql_fence(apps, schema_editor)
    elif vendor == "sqlite":
        _install_sqlite_fences(apps, schema_editor)
    else:
        raise RuntimeError("django-ray Ray task target binding supports only SQLite and PostgreSQL")


def _remove_task_target_binding_fences(apps, schema_editor) -> None:
    quote = schema_editor.quote_name
    binding_table = _binding_table(apps, schema_editor)
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            f"DROP TRIGGER IF EXISTS {quote('ray_tbinding_guard_0023')} ON {binding_table}"
        )
        schema_editor.execute(
            f"DROP FUNCTION IF EXISTS {quote('django_ray_guard_tbinding_0023')}()"
        )
    elif vendor == "sqlite":
        for trigger in (
            "ray_tbinding_insert_0023",
            "ray_tbinding_update_0023",
        ):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {quote(trigger)}")
    else:
        raise RuntimeError("django-ray Ray task target binding supports only SQLite and PostgreSQL")


def _guard_empty_task_target_binding(apps, schema_editor) -> None:
    binding_table = _binding_table(apps, schema_editor)
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(f"LOCK TABLE {binding_table} IN ACCESS EXCLUSIVE MODE")
    elif vendor == "sqlite":
        schema_editor.execute(f"UPDATE {binding_table} SET execution_id = execution_id WHERE 0")
    else:
        raise RuntimeError("django-ray Ray task target binding supports only SQLite and PostgreSQL")

    alias = schema_editor.connection.alias
    binding = apps.get_model("django_ray", "RayTaskTargetBinding")
    if binding.objects.using(alias).exists():
        raise RuntimeError(
            "django-ray Ray task target binding rollback requires the binding table to be empty"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0022_ray_target_persistence"),
    ]

    operations = [
        migrations.CreateModel(
            name="RayTaskTargetBinding",
            fields=[
                (
                    "execution",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="ray_target_binding",
                        serialize=False,
                        to="django_ray.raytaskexecution",
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(
                        db_default=1,
                        default=1,
                        editable=False,
                        help_text="Schema version for this dormant task target binding",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "target_policy",
                    models.ForeignKey(
                        editable=False,
                        help_text=("Immutable Ray target policy revision selected for this task"),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_target_bindings",
                        to="django_ray.raytargetpolicyrevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ray Task Target Binding",
                "verbose_name_plural": "Ray Task Target Bindings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(schema_version=1),
                        name="ray_tbinding_schema_valid",
                    )
                ],
            },
        ),
        migrations.RunPython(
            _install_task_target_binding_fences,
            _remove_task_target_binding_fences,
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            _guard_empty_task_target_binding,
        ),
    ]
