# Generated by Django 6.0.7 on 2026-08-15 12:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

_MAX_COUNTER = 9223372036854775807


def _routing_tables(apps, schema_editor) -> tuple[str, str, str, str]:
    quote = schema_editor.quote_name
    route = apps.get_model("django_ray", "RayTargetRoute")
    revision = apps.get_model("django_ray", "RayTargetRouteRevision")
    selection = apps.get_model("django_ray", "RayTaskTargetRouteSelection")
    binding = apps.get_model("django_ray", "RayTaskTargetBinding")
    return (
        quote(route._meta.db_table),
        quote(revision._meta.db_table),
        quote(selection._meta.db_table),
        quote(binding._meta.db_table),
    )


def _install_postgresql_fences(apps, schema_editor) -> None:
    route_table, revision_table, selection_table, binding_table = _routing_tables(
        apps, schema_editor
    )
    statements = (
        """
        CREATE FUNCTION django_ray_guard_troute_0024()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF char_length(NEW.backend_alias) NOT BETWEEN 1 AND 128
               OR substring(NEW.backend_alias FROM 1 FOR 1) !~ '^[a-z0-9]$'
               OR NEW.backend_alias ~ '[^a-z0-9_.-]'
               OR NOT isfinite(NEW.created_at)
               OR EXTRACT(YEAR FROM NEW.created_at AT TIME ZONE 'UTC')
                  NOT BETWEEN 1 AND 9999 THEN
                RAISE EXCEPTION 'django-ray Ray target route is invalid'
                    USING ERRCODE = '23514';
            END IF;
            IF TG_OP = 'UPDATE' AND NEW IS DISTINCT FROM OLD THEN
                RAISE EXCEPTION 'django-ray Ray target route is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        """
        CREATE FUNCTION django_ray_guard_troute_rev_0024()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF NEW.id < 1
               OR char_length(NEW.route_id) NOT BETWEEN 1 AND 128
               OR substring(NEW.route_id FROM 1 FOR 1) !~ '^[a-z0-9]$'
               OR NEW.route_id ~ '[^a-z0-9_.-]'
               OR NEW.revision NOT BETWEEN 1 AND 9223372036854775807
               OR NEW.target_policy_id < 1
               OR NOT isfinite(NEW.created_at)
               OR EXTRACT(YEAR FROM NEW.created_at AT TIME ZONE 'UTC')
                  NOT BETWEEN 1 AND 9999 THEN
                RAISE EXCEPTION 'django-ray Ray target route revision is invalid'
                    USING ERRCODE = '23514';
            END IF;
            IF TG_OP = 'UPDATE' AND NEW IS DISTINCT FROM OLD THEN
                RAISE EXCEPTION 'django-ray Ray target route revision is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE FUNCTION django_ray_guard_trsel_0024()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF NEW.binding_id < 1
               OR NEW.route_revision_id < 1
               OR NEW.schema_version <> 1
               OR NOT isfinite(NEW.created_at)
               OR EXTRACT(YEAR FROM NEW.created_at AT TIME ZONE 'UTC')
                  NOT BETWEEN 1 AND 9999 THEN
                RAISE EXCEPTION 'django-ray Ray task target route selection is invalid'
                    USING ERRCODE = '23514';
            END IF;
            IF NOT EXISTS (
                SELECT 1
                FROM {binding_table} AS binding
                JOIN {revision_table} AS route_revision
                  ON route_revision.id = NEW.route_revision_id
                WHERE binding.execution_id = NEW.binding_id
                  AND binding.target_policy_id = route_revision.target_policy_id
            ) THEN
                RAISE EXCEPTION 'django-ray Ray task target route selection policy mismatch'
                    USING ERRCODE = '23514';
            END IF;
            IF TG_OP = 'UPDATE' AND NEW IS DISTINCT FROM OLD THEN
                RAISE EXCEPTION 'django-ray Ray task target route selection is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE TRIGGER ray_troute_guard_0024
        BEFORE INSERT OR UPDATE ON {route_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_troute_0024()
        """,
        f"""
        CREATE TRIGGER ray_troute_rev_guard_0024
        BEFORE INSERT OR UPDATE ON {revision_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_troute_rev_0024()
        """,
        f"""
        CREATE TRIGGER ray_trsel_guard_0024
        BEFORE INSERT OR UPDATE ON {selection_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_trsel_0024()
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _sqlite_material_change(columns: tuple[str, ...]) -> str:
    return "\n          OR ".join(f"NEW.{column} IS NOT OLD.{column}" for column in columns)


def _sqlite_datetime_invalid(column: str) -> str:
    value = f"NEW.{column}"
    base = f"substr({value}, 1, 19)"
    return (
        f"typeof({value}) != 'text'\n"
        f"          OR instr({value}, char(0)) != 0\n"
        f"          OR length({value}) NOT IN (19, 26)\n"
        f"          OR substr({value}, 5, 1) != '-'\n"
        f"          OR substr({value}, 8, 1) != '-'\n"
        f"          OR substr({value}, 11, 1) != ' '\n"
        f"          OR substr({value}, 14, 1) != ':'\n"
        f"          OR substr({value}, 17, 1) != ':'\n"
        f"          OR substr({value}, 1, 4) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 6, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 9, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 12, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 15, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 18, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 1, 4) = '0000'\n"
        f"          OR CAST(substr({value}, 12, 2) AS INTEGER) NOT BETWEEN 0 AND 23\n"
        f"          OR datetime({base}) IS NULL\n"
        f"          OR strftime('%Y-%m-%d %H:%M:%S', {base}) != {base}\n"
        f"          OR (length({value}) = 26 AND (\n"
        f"                 substr({value}, 20, 1) != '.'\n"
        f"                 OR substr({value}, 21, 6) GLOB '*[^0-9]*'\n"
        f"             ))"
    )


def _sqlite_alias_invalid(value: str) -> str:
    return (
        f"typeof({value}) != 'text'\n"
        f"          OR instr({value}, char(0)) != 0\n"
        f"          OR length({value}) NOT BETWEEN 1 AND 128\n"
        f"          OR substr({value}, 1, 1) NOT GLOB '[a-z0-9]'\n"
        f"          OR {value} GLOB '*[^a-z0-9_.-]*'"
    )


def _install_sqlite_fences(apps, schema_editor) -> None:
    route_table, revision_table, selection_table, binding_table = _routing_tables(
        apps, schema_editor
    )
    route_changes = _sqlite_material_change(("backend_alias", "created_at"))
    revision_changes = _sqlite_material_change(
        ("id", "route_id", "revision", "target_policy_id", "created_at")
    )
    selection_changes = _sqlite_material_change(
        ("binding_id", "route_revision_id", "schema_version", "created_at")
    )
    statements = (
        f"""
        CREATE TRIGGER ray_troute_insert_0024
        BEFORE INSERT ON {route_table}
        FOR EACH ROW
        WHEN {_sqlite_alias_invalid("NEW.backend_alias")}
          OR {_sqlite_datetime_invalid("created_at")}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray target route is invalid');
        END
        """,
        f"""
        CREATE TRIGGER ray_troute_update_0024
        BEFORE UPDATE ON {route_table}
        FOR EACH ROW
        WHEN {route_changes}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray target route is immutable');
        END
        """,
        f"""
        CREATE TRIGGER ray_troute_rev_insert_0024
        BEFORE INSERT ON {revision_table}
        FOR EACH ROW
        WHEN typeof(NEW.id) != 'integer'
          OR (NEW.id != -1 AND NEW.id < 1)
          OR {_sqlite_alias_invalid("NEW.route_id")}
          OR typeof(NEW.revision) != 'integer'
          OR NEW.revision NOT BETWEEN 1 AND {_MAX_COUNTER}
          OR typeof(NEW.target_policy_id) != 'integer'
          OR NEW.target_policy_id < 1
          OR {_sqlite_datetime_invalid("created_at")}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray target route revision is invalid');
        END
        """,
        f"""
        CREATE TRIGGER ray_troute_rev_update_0024
        BEFORE UPDATE ON {revision_table}
        FOR EACH ROW
        WHEN {revision_changes}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray target route revision is immutable');
        END
        """,
        f"""
        CREATE TRIGGER ray_trsel_insert_0024
        BEFORE INSERT ON {selection_table}
        FOR EACH ROW
        WHEN typeof(NEW.binding_id) != 'integer'
          OR NEW.binding_id < 1
          OR typeof(NEW.route_revision_id) != 'integer'
          OR NEW.route_revision_id < 1
          OR typeof(NEW.schema_version) != 'integer'
          OR NEW.schema_version != 1
          OR {_sqlite_datetime_invalid("created_at")}
          OR NOT EXISTS (
                 SELECT 1
                 FROM {binding_table} AS binding
                 JOIN {revision_table} AS route_revision
                   ON route_revision.id = NEW.route_revision_id
                 WHERE binding.execution_id = NEW.binding_id
                   AND binding.target_policy_id = route_revision.target_policy_id
             )
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray task target route selection is invalid');
        END
        """,
        f"""
        CREATE TRIGGER ray_trsel_update_0024
        BEFORE UPDATE ON {selection_table}
        FOR EACH ROW
        WHEN {selection_changes}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray task target route selection is immutable');
        END
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _install_target_routing_fences(apps, schema_editor) -> None:
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        _install_postgresql_fences(apps, schema_editor)
    elif vendor == "sqlite":
        _install_sqlite_fences(apps, schema_editor)
    else:
        raise RuntimeError("django-ray Ray target routing supports only SQLite and PostgreSQL")


def _remove_target_routing_fences(apps, schema_editor) -> None:
    quote = schema_editor.quote_name
    route_table, revision_table, selection_table, _binding_table = _routing_tables(
        apps, schema_editor
    )
    trigger_tables = {
        "ray_troute_guard_0024": route_table,
        "ray_troute_rev_guard_0024": revision_table,
        "ray_trsel_guard_0024": selection_table,
    }
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        for trigger, table in trigger_tables.items():
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {quote(trigger)} ON {table}")
        for function in (
            "django_ray_guard_troute_0024",
            "django_ray_guard_troute_rev_0024",
            "django_ray_guard_trsel_0024",
        ):
            schema_editor.execute(f"DROP FUNCTION IF EXISTS {quote(function)}()")
    elif vendor == "sqlite":
        for trigger in (
            "ray_troute_insert_0024",
            "ray_troute_update_0024",
            "ray_troute_rev_insert_0024",
            "ray_troute_rev_update_0024",
            "ray_trsel_insert_0024",
            "ray_trsel_update_0024",
        ):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {quote(trigger)}")
    else:
        raise RuntimeError("django-ray Ray target routing supports only SQLite and PostgreSQL")


def _guard_empty_target_routing(apps, schema_editor) -> None:
    route_table, revision_table, selection_table, _binding_table = _routing_tables(
        apps, schema_editor
    )
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            f"LOCK TABLE {route_table}, {revision_table}, {selection_table} "
            "IN ACCESS EXCLUSIVE MODE"
        )
    elif vendor == "sqlite":
        schema_editor.execute(f"UPDATE {route_table} SET backend_alias = backend_alias WHERE 0")
    else:
        raise RuntimeError("django-ray Ray target routing supports only SQLite and PostgreSQL")

    alias = schema_editor.connection.alias
    model_names = (
        "RayTaskTargetRouteSelection",
        "RayTargetRouteRevision",
        "RayTargetRoute",
    )
    if any(
        apps.get_model("django_ray", model_name).objects.using(alias).exists()
        for model_name in model_names
    ):
        raise RuntimeError(
            "django-ray Ray target routing rollback requires all routing tables to be empty"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0023_ray_task_target_binding"),
    ]

    operations = [
        migrations.CreateModel(
            name="RayTargetRoute",
            fields=[
                (
                    "backend_alias",
                    models.CharField(
                        editable=False,
                        help_text=(
                            "Stable Django task backend alias for dormant Ray target routing"
                        ),
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical Ray backend alias.",
                                regex="\\A[a-z0-9][a-z0-9_.-]{0,127}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            options={
                "verbose_name": "Ray Target Route",
                "verbose_name_plural": "Ray Target Routes",
            },
        ),
        migrations.CreateModel(
            name="RayTargetRouteRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(_MAX_COUNTER),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "route",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="django_ray.raytargetroute",
                    ),
                ),
                (
                    "target_policy",
                    models.ForeignKey(
                        editable=False,
                        help_text=("Exact immutable target policy selected by this route revision"),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="route_revisions",
                        to="django_ray.raytargetpolicyrevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ray Target Route Revision",
                "verbose_name_plural": "Ray Target Route Revisions",
            },
        ),
        migrations.CreateModel(
            name="RayTaskTargetRouteSelection",
            fields=[
                (
                    "binding",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="route_selection",
                        serialize=False,
                        to="django_ray.raytasktargetbinding",
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(
                        db_default=1,
                        default=1,
                        editable=False,
                        help_text=("Schema version for this dormant task target route selection"),
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "route_revision",
                    models.ForeignKey(
                        editable=False,
                        help_text=(
                            "Exact immutable backend-route revision selected for this binding"
                        ),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_selections",
                        to="django_ray.raytargetrouterevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ray Task Target Route Selection",
                "verbose_name_plural": "Ray Task Target Route Selections",
            },
        ),
        migrations.AddIndex(
            model_name="raytargetrouterevision",
            index=models.Index(fields=["route", "-revision"], name="ray_troute_latest_idx"),
        ),
        migrations.AddConstraint(
            model_name="raytargetrouterevision",
            constraint=models.CheckConstraint(
                condition=models.Q(id__gte=1),
                name="ray_troute_id_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytargetrouterevision",
            constraint=models.CheckConstraint(
                condition=models.Q(revision__gte=1, revision__lte=_MAX_COUNTER),
                name="ray_troute_revision_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytargetrouterevision",
            constraint=models.UniqueConstraint(
                fields=("route", "revision"),
                name="ray_troute_route_rev_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytasktargetrouteselection",
            constraint=models.CheckConstraint(
                condition=models.Q(schema_version=1),
                name="ray_trsel_schema_valid",
            ),
        ),
        migrations.RunPython(
            _install_target_routing_fences,
            _remove_target_routing_fences,
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            _guard_empty_target_routing,
        ),
    ]
