# Generated by Django 6.0.7 on 2026-08-15 13:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

_MAX_COUNTER = 9223372036854775807
_MAX_PID = 2147483647
_MAX_SMALLINT = 32767
_RAY_JOB_CAPABILITY_LIMIT = 64


def _capability_tables(apps, schema_editor) -> tuple[str, str, str, str, str]:
    quote = schema_editor.quote_name
    capability = apps.get_model("django_ray", "RayWorkerTargetCapability")
    lease = apps.get_model("django_ray", "TaskWorkerLease")
    target = apps.get_model("django_ray", "RayTarget")
    policy = apps.get_model("django_ray", "RayTargetPolicyRevision")
    attestation = apps.get_model("django_ray", "RayTargetAttestationRevision")
    return (
        quote(capability._meta.db_table),
        quote(lease._meta.db_table),
        quote(target._meta.db_table),
        quote(policy._meta.db_table),
        quote(attestation._meta.db_table),
    )


def _install_postgresql_fences(apps, schema_editor) -> None:
    capability_table, lease_table, target_table, policy_table, attestation_table = (
        _capability_tables(apps, schema_editor)
    )
    statements = (
        f"""
        CREATE FUNCTION django_ray_guard_wtcap_0025()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        DECLARE
            existing_count bigint;
            existing_core boolean;
        BEGIN
            IF NEW.id < 1
               OR char_length(NEW.lease_id) NOT BETWEEN 1 AND 255
               OR char_length(NEW.lease_hostname) NOT BETWEEN 1 AND 255
               OR NEW.lease_pid NOT BETWEEN 1 AND {_MAX_PID}
               OR NOT isfinite(NEW.lease_started_at)
               OR EXTRACT(YEAR FROM NEW.lease_started_at AT TIME ZONE 'UTC')
                  NOT BETWEEN 1 AND 9999
               OR char_length(NEW.target_id) NOT BETWEEN 1 AND 128
               OR substring(NEW.target_id FROM 1 FOR 1) !~ '^[a-z0-9]$'
               OR NEW.target_id ~ '[^a-z0-9_.-]'
               OR NEW.target_policy_id < 1
               OR NEW.attestation_id < 1
               OR NEW.runner_family NOT IN ('ray_core', 'ray_job')
               OR NEW.manager_ray_major NOT BETWEEN 1 AND {_MAX_COUNTER}
               OR NEW.manager_ray_minor NOT BETWEEN 0 AND {_MAX_COUNTER}
               OR NEW.manager_ray_patch NOT BETWEEN 0 AND {_MAX_COUNTER}
               OR char_length(NEW.manager_python_implementation) NOT BETWEEN 1 AND 64
               OR substring(NEW.manager_python_implementation FROM 1 FOR 1) !~ '^[a-z]$'
               OR NEW.manager_python_implementation ~ '[^a-z0-9_.-]'
               OR NEW.manager_python_major NOT BETWEEN 1 AND {_MAX_COUNTER}
               OR NEW.manager_python_minor NOT BETWEEN 0 AND {_MAX_COUNTER}
               OR NEW.manager_python_patch NOT BETWEEN 0 AND {_MAX_COUNTER}
               OR NEW.schema_version <> 1
               OR NEW.revision NOT BETWEEN 1 AND {_MAX_COUNTER}
               OR NOT isfinite(NEW.created_at)
               OR EXTRACT(YEAR FROM NEW.created_at AT TIME ZONE 'UTC')
                  NOT BETWEEN 1 AND 9999
               OR NOT isfinite(NEW.advertised_at)
               OR EXTRACT(YEAR FROM NEW.advertised_at AT TIME ZONE 'UTC')
                  NOT BETWEEN 1 AND 9999
               OR NEW.advertised_at < NEW.created_at THEN
                RAISE EXCEPTION 'django-ray Ray worker target capability is invalid'
                    USING ERRCODE = '23514';
            END IF;

            IF TG_OP = 'INSERT' AND NEW.revision <> 1 THEN
                RAISE EXCEPTION 'django-ray Ray worker target capability is invalid'
                    USING ERRCODE = '23514';
            END IF;
            IF TG_OP = 'UPDATE' AND NEW IS NOT DISTINCT FROM OLD THEN
                RETURN NEW;
            END IF;
            IF TG_OP = 'UPDATE' AND (
                NEW.id IS DISTINCT FROM OLD.id
                OR NEW.lease_id IS DISTINCT FROM OLD.lease_id
                OR NEW.lease_hostname IS DISTINCT FROM OLD.lease_hostname
                OR NEW.lease_pid IS DISTINCT FROM OLD.lease_pid
                OR NEW.lease_started_at IS DISTINCT FROM OLD.lease_started_at
                OR NEW.target_id IS DISTINCT FROM OLD.target_id
                OR NEW.runner_family IS DISTINCT FROM OLD.runner_family
                OR NEW.manager_ray_major IS DISTINCT FROM OLD.manager_ray_major
                OR NEW.manager_ray_minor IS DISTINCT FROM OLD.manager_ray_minor
                OR NEW.manager_ray_patch IS DISTINCT FROM OLD.manager_ray_patch
                OR NEW.manager_python_implementation
                   IS DISTINCT FROM OLD.manager_python_implementation
                OR NEW.manager_python_major IS DISTINCT FROM OLD.manager_python_major
                OR NEW.manager_python_minor IS DISTINCT FROM OLD.manager_python_minor
                OR NEW.manager_python_patch IS DISTINCT FROM OLD.manager_python_patch
                OR NEW.schema_version IS DISTINCT FROM OLD.schema_version
                OR NEW.created_at IS DISTINCT FROM OLD.created_at
                OR OLD.revision >= {_MAX_COUNTER}
                OR NEW.revision <> OLD.revision + 1
                OR NEW.advertised_at <= OLD.advertised_at
            ) THEN
                RAISE EXCEPTION 'django-ray Ray worker target capability CAS update is invalid'
                    USING ERRCODE = '23514';
            END IF;

            -- Serialize every capability mutation by exact lease incarnation,
            -- then by stable target.  Later policy/attestation appends take the
            -- target lock and therefore cannot race this latest-history check.
            PERFORM 1
            FROM {lease_table}
            WHERE worker_id = NEW.lease_id
            FOR UPDATE;
            PERFORM 1
            FROM {target_table}
            WHERE target_key = NEW.target_id
            FOR SHARE;

            IF NOT EXISTS (
                SELECT 1
                FROM {lease_table} AS lease
                JOIN {target_table} AS target
                  ON target.target_key = NEW.target_id
                JOIN {policy_table} AS policy
                  ON policy.id = NEW.target_policy_id
                 AND policy.target_id = target.target_key
                JOIN {attestation_table} AS attestation
                  ON attestation.id = NEW.attestation_id
                 AND attestation.policy_id = policy.id
                WHERE lease.worker_id = NEW.lease_id
                  AND lease.hostname = NEW.lease_hostname
                  AND lease.pid = NEW.lease_pid
                  AND lease.started_at = NEW.lease_started_at
                  AND lease.is_active
                  AND lease.stopped_at IS NULL
                  AND lease.capability_schema_version = 1
                  AND lease.legacy_admission_token_id IS NULL
                  AND lease.min_supported_execution_protocol_version
                      BETWEEN 1 AND {_MAX_SMALLINT}
                  AND lease.max_supported_execution_protocol_version
                      BETWEEN lease.min_supported_execution_protocol_version
                          AND {_MAX_SMALLINT}
                  AND target.runner_family = NEW.runner_family
                  AND target.ray_major = NEW.manager_ray_major
                  AND target.ray_minor = NEW.manager_ray_minor
                  AND target.ray_patch = NEW.manager_ray_patch
                  AND target.python_implementation = NEW.manager_python_implementation
                  AND target.python_major = NEW.manager_python_major
                  AND target.python_minor = NEW.manager_python_minor
                  AND target.python_patch = NEW.manager_python_patch
                  AND policy.desired_state IN ('active', 'draining')
                  AND policy.revision = (
                      SELECT MAX(candidate.revision)
                      FROM {policy_table} AS candidate
                      WHERE candidate.target_id = target.target_key
                  )
                  AND policy.revision = (
                      SELECT COUNT(*)
                      FROM {policy_table} AS candidate
                      WHERE candidate.target_id = target.target_key
                  )
                  AND attestation.revision = (
                      SELECT MAX(candidate.revision)
                      FROM {attestation_table} AS candidate
                      WHERE candidate.policy_id = policy.id
                  )
                  AND attestation.revision = (
                      SELECT COUNT(*)
                      FROM {attestation_table} AS candidate
                      WHERE candidate.policy_id = policy.id
                  )
                  AND NEW.advertised_at >= attestation.recorded_at
                  AND NEW.advertised_at < attestation.expires_at
            ) THEN
                RAISE EXCEPTION 'django-ray Ray worker target capability is invalid'
                    USING ERRCODE = '23514';
            END IF;

            IF TG_OP = 'INSERT' THEN
                SELECT COUNT(*), COALESCE(BOOL_OR(runner_family = 'ray_core'), FALSE)
                INTO existing_count, existing_core
                FROM {capability_table}
                WHERE lease_id = NEW.lease_id;
            ELSE
                SELECT COUNT(*), COALESCE(BOOL_OR(runner_family = 'ray_core'), FALSE)
                INTO existing_count, existing_core
                FROM {capability_table}
                WHERE lease_id = NEW.lease_id
                  AND id <> OLD.id;
            END IF;
            IF (NEW.runner_family = 'ray_core' AND existing_count <> 0)
               OR (NEW.runner_family = 'ray_job' AND existing_core)
               OR (NEW.runner_family = 'ray_job'
                   AND existing_count >= {_RAY_JOB_CAPABILITY_LIMIT}) THEN
                RAISE EXCEPTION 'django-ray Ray worker target capability limit exceeded'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE FUNCTION django_ray_guard_wtcap_lease_0025()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF (
                NEW.worker_id IS DISTINCT FROM OLD.worker_id
                OR NEW.hostname IS DISTINCT FROM OLD.hostname
                OR NEW.pid IS DISTINCT FROM OLD.pid
                OR NEW.started_at IS DISTINCT FROM OLD.started_at
            ) AND EXISTS (
                SELECT 1
                FROM {capability_table}
                WHERE lease_id = OLD.worker_id
            ) THEN
                RAISE EXCEPTION 'django-ray worker lease identity is protected by target capability'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE TRIGGER ray_wtcap_guard_0025
        BEFORE INSERT OR UPDATE ON {capability_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_wtcap_0025()
        """,
        f"""
        CREATE TRIGGER ray_wtcap_lease_guard_0025
        BEFORE UPDATE OF worker_id, hostname, pid, started_at ON {lease_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_wtcap_lease_0025()
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _sqlite_material_change(columns: tuple[str, ...]) -> str:
    return "\n          OR ".join(f"NEW.{column} IS NOT OLD.{column}" for column in columns)


def _sqlite_datetime_invalid(column: str) -> str:
    value = f"NEW.{column}"
    base = f"substr({value}, 1, 19)"
    return (
        f"typeof({value}) != 'text'\n"
        f"          OR instr({value}, char(0)) != 0\n"
        f"          OR length({value}) NOT IN (19, 26)\n"
        f"          OR substr({value}, 5, 1) != '-'\n"
        f"          OR substr({value}, 8, 1) != '-'\n"
        f"          OR substr({value}, 11, 1) != ' '\n"
        f"          OR substr({value}, 14, 1) != ':'\n"
        f"          OR substr({value}, 17, 1) != ':'\n"
        f"          OR substr({value}, 1, 4) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 6, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 9, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 12, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 15, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 18, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 1, 4) = '0000'\n"
        f"          OR CAST(substr({value}, 12, 2) AS INTEGER) NOT BETWEEN 0 AND 23\n"
        f"          OR datetime({base}) IS NULL\n"
        f"          OR strftime('%Y-%m-%d %H:%M:%S', {base}) != {base}\n"
        f"          OR (length({value}) = 26 AND (\n"
        f"                 substr({value}, 20, 1) != '.'\n"
        f"                 OR substr({value}, 21, 6) GLOB '*[^0-9]*'\n"
        f"             ))"
    )


def _sqlite_bounded_text_invalid(value: str, *, maximum: int) -> str:
    return (
        f"typeof({value}) != 'text'\n"
        f"          OR instr({value}, char(0)) != 0\n"
        f"          OR length({value}) NOT BETWEEN 1 AND {maximum}"
    )


def _sqlite_target_key_invalid(value: str) -> str:
    return (
        f"{_sqlite_bounded_text_invalid(value, maximum=128)}\n"
        f"          OR substr({value}, 1, 1) NOT GLOB '[a-z0-9]'\n"
        f"          OR {value} GLOB '*[^a-z0-9_.-]*'"
    )


def _sqlite_python_implementation_invalid(value: str) -> str:
    return (
        f"{_sqlite_bounded_text_invalid(value, maximum=64)}\n"
        f"          OR substr({value}, 1, 1) NOT GLOB '[a-z]'\n"
        f"          OR {value} GLOB '*[^a-z0-9_.-]*'"
    )


def _install_sqlite_fences(apps, schema_editor) -> None:
    capability_table, lease_table, target_table, policy_table, attestation_table = (
        _capability_tables(apps, schema_editor)
    )
    columns = (
        "id",
        "lease_id",
        "lease_hostname",
        "lease_pid",
        "lease_started_at",
        "target_id",
        "target_policy_id",
        "attestation_id",
        "runner_family",
        "manager_ray_major",
        "manager_ray_minor",
        "manager_ray_patch",
        "manager_python_implementation",
        "manager_python_major",
        "manager_python_minor",
        "manager_python_patch",
        "schema_version",
        "revision",
        "created_at",
        "advertised_at",
    )
    immutable_columns = (
        "id",
        "lease_id",
        "lease_hostname",
        "lease_pid",
        "lease_started_at",
        "target_id",
        "runner_family",
        "manager_ray_major",
        "manager_ray_minor",
        "manager_ray_patch",
        "manager_python_implementation",
        "manager_python_major",
        "manager_python_minor",
        "manager_python_patch",
        "schema_version",
        "created_at",
    )
    base_invalid = f"""
          typeof(NEW.id) != 'integer'
          OR (NEW.id != -1 AND NEW.id < 1)
          OR {_sqlite_bounded_text_invalid("NEW.lease_id", maximum=255)}
          OR {_sqlite_bounded_text_invalid("NEW.lease_hostname", maximum=255)}
          OR typeof(NEW.lease_pid) != 'integer'
          OR NEW.lease_pid NOT BETWEEN 1 AND {_MAX_PID}
          OR {_sqlite_datetime_invalid("lease_started_at")}
          OR {_sqlite_target_key_invalid("NEW.target_id")}
          OR typeof(NEW.target_policy_id) != 'integer'
          OR NEW.target_policy_id < 1
          OR typeof(NEW.attestation_id) != 'integer'
          OR NEW.attestation_id < 1
          OR typeof(NEW.runner_family) != 'text'
          OR NEW.runner_family NOT IN ('ray_core', 'ray_job')
          OR typeof(NEW.manager_ray_major) != 'integer'
          OR NEW.manager_ray_major NOT BETWEEN 1 AND {_MAX_COUNTER}
          OR typeof(NEW.manager_ray_minor) != 'integer'
          OR NEW.manager_ray_minor NOT BETWEEN 0 AND {_MAX_COUNTER}
          OR typeof(NEW.manager_ray_patch) != 'integer'
          OR NEW.manager_ray_patch NOT BETWEEN 0 AND {_MAX_COUNTER}
          OR {_sqlite_python_implementation_invalid("NEW.manager_python_implementation")}
          OR typeof(NEW.manager_python_major) != 'integer'
          OR NEW.manager_python_major NOT BETWEEN 1 AND {_MAX_COUNTER}
          OR typeof(NEW.manager_python_minor) != 'integer'
          OR NEW.manager_python_minor NOT BETWEEN 0 AND {_MAX_COUNTER}
          OR typeof(NEW.manager_python_patch) != 'integer'
          OR NEW.manager_python_patch NOT BETWEEN 0 AND {_MAX_COUNTER}
          OR typeof(NEW.schema_version) != 'integer'
          OR NEW.schema_version != 1
          OR typeof(NEW.revision) != 'integer'
          OR NEW.revision NOT BETWEEN 1 AND {_MAX_COUNTER}
          OR {_sqlite_datetime_invalid("created_at")}
          OR {_sqlite_datetime_invalid("advertised_at")}
          OR NEW.advertised_at < NEW.created_at
    """.strip()
    state_invalid = f"""
          NOT EXISTS (
              SELECT 1
              FROM {lease_table} AS lease
              JOIN {target_table} AS target
                ON target.target_key = NEW.target_id
              JOIN {policy_table} AS policy
                ON policy.id = NEW.target_policy_id
               AND policy.target_id = target.target_key
              JOIN {attestation_table} AS attestation
                ON attestation.id = NEW.attestation_id
               AND attestation.policy_id = policy.id
              WHERE lease.worker_id = NEW.lease_id
                AND typeof(lease.worker_id) = 'text'
                AND lease.hostname = NEW.lease_hostname
                AND typeof(lease.hostname) = 'text'
                AND lease.pid = NEW.lease_pid
                AND typeof(lease.pid) = 'integer'
                AND lease.started_at = NEW.lease_started_at
                AND typeof(lease.started_at) = 'text'
                AND lease.is_active = 1
                AND typeof(lease.is_active) = 'integer'
                AND lease.stopped_at IS NULL
                AND lease.capability_schema_version = 1
                AND typeof(lease.capability_schema_version) = 'integer'
                AND lease.legacy_admission_token_id IS NULL
                AND typeof(lease.min_supported_execution_protocol_version) = 'integer'
                AND lease.min_supported_execution_protocol_version
                    BETWEEN 1 AND {_MAX_SMALLINT}
                AND typeof(lease.max_supported_execution_protocol_version) = 'integer'
                AND lease.max_supported_execution_protocol_version
                    BETWEEN lease.min_supported_execution_protocol_version
                        AND {_MAX_SMALLINT}
                AND target.runner_family = NEW.runner_family
                AND target.ray_major = NEW.manager_ray_major
                AND target.ray_minor = NEW.manager_ray_minor
                AND target.ray_patch = NEW.manager_ray_patch
                AND target.python_implementation = NEW.manager_python_implementation
                AND target.python_major = NEW.manager_python_major
                AND target.python_minor = NEW.manager_python_minor
                AND target.python_patch = NEW.manager_python_patch
                AND policy.desired_state IN ('active', 'draining')
                AND policy.revision = (
                    SELECT MAX(candidate.revision)
                    FROM {policy_table} AS candidate
                    WHERE candidate.target_id = target.target_key
                )
                AND policy.revision = (
                    SELECT COUNT(*)
                    FROM {policy_table} AS candidate
                    WHERE candidate.target_id = target.target_key
                )
                AND attestation.revision = (
                    SELECT MAX(candidate.revision)
                    FROM {attestation_table} AS candidate
                    WHERE candidate.policy_id = policy.id
                )
                AND attestation.revision = (
                    SELECT COUNT(*)
                    FROM {attestation_table} AS candidate
                    WHERE candidate.policy_id = policy.id
                )
                AND NEW.advertised_at >= attestation.recorded_at
                AND NEW.advertised_at < attestation.expires_at
          )
    """.strip()
    insert_cardinality_invalid = f"""
          (NEW.runner_family = 'ray_core' AND EXISTS (
              SELECT 1 FROM {capability_table} WHERE lease_id = NEW.lease_id
          ))
          OR (NEW.runner_family = 'ray_job' AND EXISTS (
              SELECT 1
              FROM {capability_table}
              WHERE lease_id = NEW.lease_id
                AND runner_family = 'ray_core'
          ))
          OR (NEW.runner_family = 'ray_job' AND (
              SELECT COUNT(*) FROM {capability_table} WHERE lease_id = NEW.lease_id
          ) >= {_RAY_JOB_CAPABILITY_LIMIT})
    """.strip()
    update_cardinality_invalid = f"""
          (NEW.runner_family = 'ray_core' AND EXISTS (
              SELECT 1
              FROM {capability_table}
              WHERE lease_id = NEW.lease_id
                AND id != OLD.id
          ))
          OR (NEW.runner_family = 'ray_job' AND EXISTS (
              SELECT 1
              FROM {capability_table}
              WHERE lease_id = NEW.lease_id
                AND id != OLD.id
                AND runner_family = 'ray_core'
          ))
          OR (NEW.runner_family = 'ray_job' AND (
              SELECT COUNT(*)
              FROM {capability_table}
              WHERE lease_id = NEW.lease_id
                AND id != OLD.id
          ) >= {_RAY_JOB_CAPABILITY_LIMIT})
    """.strip()
    statements = (
        f"""
        CREATE TRIGGER ray_wtcap_insert_0025
        BEFORE INSERT ON {capability_table}
        FOR EACH ROW
        WHEN {base_invalid}
          OR NEW.revision != 1
          OR {state_invalid}
          OR {insert_cardinality_invalid}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray worker target capability is invalid');
        END
        """,
        f"""
        CREATE TRIGGER ray_wtcap_update_0025
        BEFORE UPDATE ON {capability_table}
        FOR EACH ROW
        WHEN (
             {_sqlite_material_change(columns)}
        ) AND (
             {base_invalid}
             OR {_sqlite_material_change(immutable_columns)}
             OR OLD.revision >= {_MAX_COUNTER}
             OR NEW.revision != OLD.revision + 1
             OR NEW.advertised_at <= OLD.advertised_at
             OR {state_invalid}
             OR {update_cardinality_invalid}
         )
        BEGIN
            SELECT RAISE(ABORT, 'django-ray Ray worker target capability CAS update is invalid');
        END
        """,
        f"""
        CREATE TRIGGER ray_wtcap_lease_update_0025
        BEFORE UPDATE OF worker_id, hostname, pid, started_at ON {lease_table}
        FOR EACH ROW
        WHEN (
            NEW.worker_id IS NOT OLD.worker_id
            OR NEW.hostname IS NOT OLD.hostname
            OR NEW.pid IS NOT OLD.pid
            OR NEW.started_at IS NOT OLD.started_at
        ) AND EXISTS (
            SELECT 1
            FROM {capability_table}
            WHERE lease_id = OLD.worker_id
        )
        BEGIN
            SELECT RAISE(
                ABORT,
                'django-ray worker lease identity is protected by target capability'
            );
        END
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _install_capability_fences(apps, schema_editor) -> None:
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        _install_postgresql_fences(apps, schema_editor)
    elif vendor == "sqlite":
        _install_sqlite_fences(apps, schema_editor)
    else:
        raise RuntimeError(
            "django-ray Ray worker target capabilities support only SQLite and PostgreSQL"
        )


def _remove_capability_fences(apps, schema_editor) -> None:
    capability_table, lease_table, _target_table, _policy_table, _attestation_table = (
        _capability_tables(apps, schema_editor)
    )
    quote = schema_editor.quote_name
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        for trigger, table in (
            ("ray_wtcap_guard_0025", capability_table),
            ("ray_wtcap_lease_guard_0025", lease_table),
        ):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {quote(trigger)} ON {table}")
        for function in (
            "django_ray_guard_wtcap_0025",
            "django_ray_guard_wtcap_lease_0025",
        ):
            schema_editor.execute(f"DROP FUNCTION IF EXISTS {quote(function)}()")
    elif vendor == "sqlite":
        for trigger in (
            "ray_wtcap_insert_0025",
            "ray_wtcap_update_0025",
            "ray_wtcap_lease_update_0025",
        ):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {quote(trigger)}")
    else:
        raise RuntimeError(
            "django-ray Ray worker target capabilities support only SQLite and PostgreSQL"
        )


def _guard_empty_capabilities(apps, schema_editor) -> None:
    capability_table, _lease_table, _target_table, _policy_table, _attestation_table = (
        _capability_tables(apps, schema_editor)
    )
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(f"LOCK TABLE {capability_table} IN ACCESS EXCLUSIVE MODE")
    elif vendor == "sqlite":
        schema_editor.execute(f"UPDATE {capability_table} SET revision = revision WHERE 0")
    else:
        raise RuntimeError(
            "django-ray Ray worker target capabilities support only SQLite and PostgreSQL"
        )
    alias = schema_editor.connection.alias
    capability = apps.get_model("django_ray", "RayWorkerTargetCapability")
    if capability.objects.using(alias).exists():
        raise RuntimeError(
            "django-ray Ray worker target capability rollback requires the table to be empty"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0024_ray_target_routes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RayWorkerTargetCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("lease_hostname", models.CharField(editable=False, max_length=255)),
                (
                    "lease_pid",
                    models.PositiveIntegerField(
                        editable=False, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("lease_started_at", models.DateTimeField(editable=False)),
                (
                    "runner_family",
                    models.CharField(
                        choices=[("ray_core", "ray_core"), ("ray_job", "ray_job")],
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "manager_ray_major",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9223372036854775807),
                        ],
                    ),
                ),
                (
                    "manager_ray_minor",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "manager_ray_patch",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "manager_python_implementation",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a normalized Python implementation identifier.",
                                regex="\\A[a-z][a-z0-9_.-]{0,63}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "manager_python_major",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9223372036854775807),
                        ],
                    ),
                ),
                (
                    "manager_python_minor",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "manager_python_patch",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(
                        db_default=1,
                        default=1,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9223372036854775807),
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "advertised_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "attestation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worker_capabilities",
                        to="django_ray.raytargetattestationrevision",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ray_target_capabilities",
                        to="django_ray.taskworkerlease",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worker_capabilities",
                        to="django_ray.raytarget",
                    ),
                ),
                (
                    "target_policy",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worker_capabilities",
                        to="django_ray.raytargetpolicyrevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ray Worker Target Capability",
                "verbose_name_plural": "Ray Worker Target Capabilities",
                "indexes": [
                    models.Index(fields=["target", "lease"], name="ray_wtcap_target_lease_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id__gte", 1)), name="ray_wtcap_id_valid"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("lease_pid__gte", 1)), name="ray_wtcap_lease_pid_valid"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("runner_family__in", ("ray_core", "ray_job"))),
                        name="ray_wtcap_runner_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("manager_python_major__gte", 1),
                            ("manager_python_major__lte", 9223372036854775807),
                            ("manager_python_minor__gte", 0),
                            ("manager_python_minor__lte", 9223372036854775807),
                            ("manager_python_patch__gte", 0),
                            ("manager_python_patch__lte", 9223372036854775807),
                            ("manager_ray_major__gte", 1),
                            ("manager_ray_major__lte", 9223372036854775807),
                            ("manager_ray_minor__gte", 0),
                            ("manager_ray_minor__lte", 9223372036854775807),
                            ("manager_ray_patch__gte", 0),
                            ("manager_ray_patch__lte", 9223372036854775807),
                        ),
                        name="ray_wtcap_runtime_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_version", 1)), name="ray_wtcap_schema_valid"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("revision__gte", 1), ("revision__lte", 9223372036854775807)
                        ),
                        name="ray_wtcap_revision_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("advertised_at__gte", models.F("created_at"))),
                        name="ray_wtcap_time_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("lease", "target"), name="ray_wtcap_lease_target_uniq"
                    ),
                ],
            },
        ),
        migrations.RunPython(
            _install_capability_fences,
            _remove_capability_fences,
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            _guard_empty_capabilities,
        ),
    ]
