# Generated by Django 6.0.7 on 2026-08-15 15:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

_MAX_COUNTER = 9223372036854775807
_MAX_POSITIVE_INTEGER = 2147483647
_COMPATIBILITY_REASONS = (
    "expired",
    "cluster_session_mismatch",
    "ray_version_mismatch",
    "python_implementation_mismatch",
    "python_version_mismatch",
    "current_node_not_attested",
    "membership_mismatch",
)


def _evidence_tables(apps, schema_editor) -> tuple[str, ...]:
    quote = schema_editor.quote_name
    model_names = (
        "RayTaskTargetExecutionEvidence",
        "RayTaskTargetExecutionOutcome",
        "RayTaskExecution",
        "RayTaskTargetRouteSelection",
        "RayTaskTargetBinding",
        "RayTargetRouteRevision",
        "RayTarget",
        "RayTargetPolicyRevision",
        "RayTargetAttestationRevision",
        "RayWorkerTargetCapability",
        "TaskWorkerLease",
    )
    return tuple(
        quote(apps.get_model("django_ray", model_name)._meta.db_table) for model_name in model_names
    )


def _install_postgresql_fences(apps, schema_editor) -> None:
    (
        evidence_table,
        outcome_table,
        execution_table,
        selection_table,
        binding_table,
        route_revision_table,
        target_table,
        policy_table,
        attestation_table,
        capability_table,
        lease_table,
    ) = _evidence_tables(apps, schema_editor)
    reasons = ", ".join(f"'{reason}'" for reason in _COMPATIBILITY_REASONS)
    statements = (
        f"""
        CREATE FUNCTION django_ray_guard_tevid_0026()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        BEGIN
            IF TG_OP = 'UPDATE' THEN
                RAISE EXCEPTION 'django-ray target execution evidence is immutable'
                    USING ERRCODE = '23514';
            END IF;
            IF NEW.target_execution_evidence_id < 1
               OR NEW.execution_id < 1
               OR char_length(NEW.task_id) NOT BETWEEN 1 AND 255
               OR NEW.route_selection_id < 1
               OR NEW.attempt_number NOT BETWEEN 1 AND {_MAX_POSITIVE_INTEGER}
               OR NEW.execution_generation NOT BETWEEN 1 AND {_MAX_COUNTER}
               OR char_length(NEW.target_id) NOT BETWEEN 1 AND 128
               OR NEW.target_policy_id < 1
               OR NEW.claim_attestation_id < 1
               OR NEW.worker_target_capability_id < 1
               OR NEW.worker_target_capability_schema_version <> 1
               OR NEW.worker_target_capability_revision NOT BETWEEN 1 AND {_MAX_COUNTER}
               OR char_length(NEW.worker_lease_id) NOT BETWEEN 1 AND 255
               OR char_length(NEW.worker_lease_hostname) NOT BETWEEN 1 AND 255
               OR NEW.worker_lease_pid NOT BETWEEN 1 AND {_MAX_POSITIVE_INTEGER}
               OR NEW.runner_family <> 'ray_core'
               OR NEW.manager_ray_major NOT BETWEEN 1 AND {_MAX_COUNTER}
               OR NEW.manager_ray_minor NOT BETWEEN 0 AND {_MAX_COUNTER}
               OR NEW.manager_ray_patch NOT BETWEEN 0 AND {_MAX_COUNTER}
               OR char_length(NEW.manager_python_implementation) NOT BETWEEN 1 AND 64
               OR substring(NEW.manager_python_implementation FROM 1 FOR 1) !~ '[a-z]'
               OR NEW.manager_python_implementation ~ '[^a-z0-9_.-]'
               OR NEW.manager_python_major NOT BETWEEN 1 AND {_MAX_COUNTER}
               OR NEW.manager_python_minor NOT BETWEEN 0 AND {_MAX_COUNTER}
               OR NEW.manager_python_patch NOT BETWEEN 0 AND {_MAX_COUNTER}
               OR char_length(NEW.target_execution_evidence_digest) <> 71
               OR substring(NEW.target_execution_evidence_digest FROM 1 FOR 7) <> 'sha256:'
               OR substring(NEW.target_execution_evidence_digest FROM 8) ~ '[^0-9a-f]'
               OR char_length(NEW.target_expectation_digest) <> 71
               OR substring(NEW.target_expectation_digest FROM 1 FOR 7) <> 'sha256:'
               OR substring(NEW.target_expectation_digest FROM 8) ~ '[^0-9a-f]'
               OR char_length(NEW.claim_attestation_digest) <> 71
               OR substring(NEW.claim_attestation_digest FROM 1 FOR 7) <> 'sha256:'
               OR substring(NEW.claim_attestation_digest FROM 8) ~ '[^0-9a-f]'
               OR NEW.schema_version <> 1
               OR NOT isfinite(NEW.worker_target_capability_advertised_at)
               OR NOT isfinite(NEW.worker_lease_started_at)
               OR NOT isfinite(NEW.claimed_at)
               OR EXTRACT(YEAR FROM NEW.worker_target_capability_advertised_at AT TIME ZONE 'UTC')
                  NOT BETWEEN 1 AND 9999
               OR EXTRACT(YEAR FROM NEW.worker_lease_started_at AT TIME ZONE 'UTC')
                  NOT BETWEEN 1 AND 9999
               OR EXTRACT(YEAR FROM NEW.claimed_at AT TIME ZONE 'UTC')
                  NOT BETWEEN 1 AND 9999
               OR NEW.worker_target_capability_advertised_at <
                  NEW.worker_lease_started_at THEN
                RAISE EXCEPTION 'django-ray target execution evidence is invalid'
                    USING ERRCODE = '23514';
            END IF;

            -- This lock sequence is the protocol-2 lifecycle order. It also
            -- closes latest-policy/attestation and capability deletion races.
            PERFORM 1 FROM {lease_table}
             WHERE worker_id = NEW.worker_lease_id FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'django-ray target execution lease is unavailable'
                    USING ERRCODE = '23514';
            END IF;
            PERFORM 1 FROM {target_table}
             WHERE target_key = NEW.target_id FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'django-ray target execution target is unavailable'
                    USING ERRCODE = '23514';
            END IF;
            PERFORM 1 FROM {policy_table}
             WHERE id = NEW.target_policy_id FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'django-ray target execution policy is unavailable'
                    USING ERRCODE = '23514';
            END IF;
            PERFORM 1 FROM {attestation_table}
             WHERE id = NEW.claim_attestation_id FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'django-ray target execution attestation is unavailable'
                    USING ERRCODE = '23514';
            END IF;
            PERFORM 1 FROM {capability_table}
             WHERE id = NEW.worker_target_capability_id FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'django-ray target execution capability is unavailable'
                    USING ERRCODE = '23514';
            END IF;
            PERFORM 1 FROM {execution_table}
             WHERE id = NEW.execution_id FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'django-ray target execution is unavailable'
                    USING ERRCODE = '23514';
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM {execution_table} AS execution
                JOIN {selection_table} AS selection
                  ON selection.binding_id = NEW.route_selection_id
                 AND selection.binding_id = execution.id
                JOIN {binding_table} AS binding
                  ON binding.execution_id = selection.binding_id
                JOIN {route_revision_table} AS route_revision
                  ON route_revision.id = selection.route_revision_id
                 AND route_revision.target_policy_id = binding.target_policy_id
                JOIN {policy_table} AS selected_policy
                  ON selected_policy.id = binding.target_policy_id
                 AND selected_policy.target_id = NEW.target_id
                JOIN {target_table} AS target
                  ON target.target_key = NEW.target_id
                JOIN {policy_table} AS policy
                  ON policy.id = NEW.target_policy_id
                 AND policy.target_id = target.target_key
                JOIN {attestation_table} AS attestation
                  ON attestation.id = NEW.claim_attestation_id
                 AND attestation.policy_id = policy.id
                JOIN {lease_table} AS lease
                  ON lease.worker_id = NEW.worker_lease_id
                JOIN {capability_table} AS capability
                  ON capability.id = NEW.worker_target_capability_id
                 AND capability.lease_id = lease.worker_id
                 AND capability.target_id = target.target_key
                 AND capability.target_policy_id = policy.id
                 AND capability.attestation_id = attestation.id
                WHERE execution.id = NEW.execution_id
                  AND execution.execution_protocol_version = 2
                  AND execution.task_id = NEW.task_id
                  AND execution.state = 'RUNNING'
                  AND execution.attempt_number = NEW.attempt_number
                  AND execution.execution_generation = NEW.execution_generation
                  AND execution.claimed_by_worker = NEW.worker_lease_id
                  AND execution.started_at IS NOT NULL
                  AND execution.started_at <= NEW.claimed_at
                  AND execution.finished_at IS NULL
                  AND lease.hostname = NEW.worker_lease_hostname
                  AND lease.pid = NEW.worker_lease_pid
                  AND lease.started_at = NEW.worker_lease_started_at
                  AND lease.is_active
                  AND lease.stopped_at IS NULL
                  AND lease.capability_schema_version = 1
                  AND lease.legacy_admission_token_id IS NULL
                  AND lease.min_supported_execution_protocol_version <= 2
                  AND lease.max_supported_execution_protocol_version >= 2
                  AND capability.lease_hostname = NEW.worker_lease_hostname
                  AND capability.lease_pid = NEW.worker_lease_pid
                  AND capability.lease_started_at = NEW.worker_lease_started_at
                  AND capability.runner_family = NEW.runner_family
                  AND capability.manager_ray_major = NEW.manager_ray_major
                  AND capability.manager_ray_minor = NEW.manager_ray_minor
                  AND capability.manager_ray_patch = NEW.manager_ray_patch
                  AND capability.manager_python_implementation =
                      NEW.manager_python_implementation
                  AND capability.manager_python_major = NEW.manager_python_major
                  AND capability.manager_python_minor = NEW.manager_python_minor
                  AND capability.manager_python_patch = NEW.manager_python_patch
                  AND capability.schema_version =
                      NEW.worker_target_capability_schema_version
                  AND capability.revision = NEW.worker_target_capability_revision
                  AND capability.advertised_at =
                      NEW.worker_target_capability_advertised_at
                  AND target.runner_family = NEW.runner_family
                  AND target.ray_major = NEW.manager_ray_major
                  AND target.ray_minor = NEW.manager_ray_minor
                  AND target.ray_patch = NEW.manager_ray_patch
                  AND target.python_implementation = NEW.manager_python_implementation
                  AND target.python_major = NEW.manager_python_major
                  AND target.python_minor = NEW.manager_python_minor
                  AND target.python_patch = NEW.manager_python_patch
                  AND policy.desired_state IN ('active', 'draining')
                  AND policy.revision = (
                      SELECT MAX(candidate.revision)
                      FROM {policy_table} AS candidate
                      WHERE candidate.target_id = target.target_key
                  )
                  AND policy.revision = (
                      SELECT COUNT(*)
                      FROM {policy_table} AS candidate
                      WHERE candidate.target_id = target.target_key
                  )
                  AND attestation.revision = (
                      SELECT MAX(candidate.revision)
                      FROM {attestation_table} AS candidate
                      WHERE candidate.policy_id = policy.id
                  )
                  AND attestation.revision = (
                      SELECT COUNT(*)
                      FROM {attestation_table} AS candidate
                      WHERE candidate.policy_id = policy.id
                  )
                  AND policy.expectation_digest = NEW.target_expectation_digest
                  AND attestation.expectation_digest = NEW.target_expectation_digest
                  AND attestation.attestation_digest = NEW.claim_attestation_digest
                  AND NEW.claimed_at >= lease.started_at
                  AND NEW.claimed_at >= capability.advertised_at
                  AND NEW.claimed_at >= attestation.recorded_at
                  AND NEW.claimed_at < attestation.expires_at
            ) THEN
                RAISE EXCEPTION 'django-ray target execution evidence lineage is invalid'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE FUNCTION django_ray_guard_teout_0026()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $django_ray$
        DECLARE
            observation_complete boolean;
            observation_empty boolean;
        BEGIN
            IF TG_OP = 'UPDATE' THEN
                RAISE EXCEPTION 'django-ray target execution outcome is immutable'
                    USING ERRCODE = '23514';
            END IF;
            observation_complete :=
                NEW.observed_cluster_session IS NOT NULL
                AND NEW.observed_node_id IS NOT NULL
                AND NEW.observed_membership_digest IS NOT NULL
                AND NEW.observed_ray_major IS NOT NULL
                AND NEW.observed_ray_minor IS NOT NULL
                AND NEW.observed_ray_patch IS NOT NULL
                AND NEW.observed_python_implementation IS NOT NULL
                AND NEW.observed_python_major IS NOT NULL
                AND NEW.observed_python_minor IS NOT NULL
                AND NEW.observed_python_patch IS NOT NULL
                AND NEW.observed_proof_digest IS NOT NULL
                AND NEW.observed_at IS NOT NULL;
            observation_empty :=
                NEW.observed_cluster_session IS NULL
                AND NEW.observed_node_id IS NULL
                AND NEW.observed_membership_digest IS NULL
                AND NEW.observed_ray_major IS NULL
                AND NEW.observed_ray_minor IS NULL
                AND NEW.observed_ray_patch IS NULL
                AND NEW.observed_python_implementation IS NULL
                AND NEW.observed_python_major IS NULL
                AND NEW.observed_python_minor IS NULL
                AND NEW.observed_python_patch IS NULL
                AND NEW.observed_proof_digest IS NULL
                AND NEW.observed_at IS NULL;
            IF NEW.evidence_id < 1
               OR NEW.status NOT IN ('VERIFIED', 'COMPATIBILITY_REJECTED', 'UNCERTAIN')
               OR char_length(NEW.target_execution_evidence_digest) <> 71
               OR substring(NEW.target_execution_evidence_digest FROM 1 FOR 7) <> 'sha256:'
               OR substring(NEW.target_execution_evidence_digest FROM 8) ~ '[^0-9a-f]'
               OR char_length(NEW.target_expectation_digest) <> 71
               OR substring(NEW.target_expectation_digest FROM 1 FOR 7) <> 'sha256:'
               OR substring(NEW.target_expectation_digest FROM 8) ~ '[^0-9a-f]'
               OR char_length(NEW.claim_attestation_digest) <> 71
               OR substring(NEW.claim_attestation_digest FROM 1 FOR 7) <> 'sha256:'
               OR substring(NEW.claim_attestation_digest FROM 8) ~ '[^0-9a-f]'
               OR NOT isfinite(NEW.recorded_at)
               OR EXTRACT(YEAR FROM NEW.recorded_at AT TIME ZONE 'UTC')
                  NOT BETWEEN 1 AND 9999
               OR NOT (observation_complete OR observation_empty)
               OR (
                   NEW.status = 'VERIFIED'
                   AND (
                       NEW.application_invoked IS DISTINCT FROM TRUE
                       OR NEW.compatibility_reason IS NOT NULL
                       OR NOT observation_complete
                   )
               )
               OR (
                   NEW.status = 'COMPATIBILITY_REJECTED'
                   AND (
                       NEW.application_invoked IS DISTINCT FROM FALSE
                       OR NEW.compatibility_reason NOT IN ({reasons})
                       OR NOT observation_complete
                   )
               )
               OR (
                   NEW.status = 'UNCERTAIN'
                   AND (
                       NEW.application_invoked IS NOT NULL
                       OR NEW.compatibility_reason IS NOT NULL
                       OR NOT observation_empty
                   )
               )
               OR (
                   observation_complete
                   AND (
                       char_length(NEW.observed_cluster_session) NOT BETWEEN 9 AND 256
                       OR substring(NEW.observed_cluster_session FROM 1 FOR 8) <> 'session_'
                       OR substring(NEW.observed_cluster_session FROM 9 FOR 1) !~ '[A-Za-z0-9]'
                       OR substring(NEW.observed_cluster_session FROM 9) ~
                           '[^A-Za-z0-9_.-]'
                       OR char_length(NEW.observed_node_id) <> 56
                       OR NEW.observed_node_id ~ '[^0-9a-f]'
                       OR char_length(NEW.observed_membership_digest) <> 71
                       OR substring(NEW.observed_membership_digest FROM 1 FOR 7) <>
                           'sha256:'
                       OR substring(NEW.observed_membership_digest FROM 8) ~ '[^0-9a-f]'
                       OR NEW.observed_ray_major NOT BETWEEN 1 AND {_MAX_COUNTER}
                       OR NEW.observed_ray_minor NOT BETWEEN 0 AND {_MAX_COUNTER}
                       OR NEW.observed_ray_patch NOT BETWEEN 0 AND {_MAX_COUNTER}
                       OR char_length(NEW.observed_python_implementation) NOT BETWEEN 1 AND 64
                       OR substring(NEW.observed_python_implementation FROM 1 FOR 1) !~ '[a-z]'
                       OR NEW.observed_python_implementation ~ '[^a-z0-9_.-]'
                       OR NEW.observed_python_major NOT BETWEEN 1 AND {_MAX_COUNTER}
                       OR NEW.observed_python_minor NOT BETWEEN 0 AND {_MAX_COUNTER}
                       OR NEW.observed_python_patch NOT BETWEEN 0 AND {_MAX_COUNTER}
                       OR char_length(NEW.observed_proof_digest) <> 71
                       OR substring(NEW.observed_proof_digest FROM 1 FOR 7) <> 'sha256:'
                       OR substring(NEW.observed_proof_digest FROM 8) ~ '[^0-9a-f]'
                       OR NOT isfinite(NEW.observed_at)
                       OR EXTRACT(YEAR FROM NEW.observed_at AT TIME ZONE 'UTC')
                          NOT BETWEEN 1 AND 9999
                       OR NEW.observed_at > NEW.recorded_at
                   )
               ) THEN
                RAISE EXCEPTION 'django-ray target execution outcome is invalid'
                    USING ERRCODE = '23514';
            END IF;

            PERFORM 1 FROM {evidence_table}
             WHERE target_execution_evidence_id = NEW.evidence_id FOR UPDATE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'django-ray target execution evidence is unavailable'
                    USING ERRCODE = '23514';
            END IF;
            IF NOT EXISTS (
                SELECT 1
                FROM {evidence_table} AS evidence
                JOIN {target_table} AS target
                  ON target.target_key = evidence.target_id
                JOIN {attestation_table} AS attestation
                  ON attestation.id = evidence.claim_attestation_id
                WHERE evidence.target_execution_evidence_id = NEW.evidence_id
                  AND evidence.target_execution_evidence_digest =
                      NEW.target_execution_evidence_digest
                  AND evidence.target_expectation_digest = NEW.target_expectation_digest
                  AND evidence.claim_attestation_digest = NEW.claim_attestation_digest
                  AND NEW.recorded_at >= evidence.claimed_at
                  AND (
                      NOT observation_complete
                      OR NEW.observed_at >= evidence.claimed_at
                  )
                  AND (
                      NEW.status <> 'VERIFIED'
                      OR (
                          NEW.observed_cluster_session = target.cluster_session
                          AND NEW.observed_membership_digest = attestation.membership_digest
                          AND NEW.observed_ray_major = target.ray_major
                          AND NEW.observed_ray_minor = target.ray_minor
                          AND NEW.observed_ray_patch = target.ray_patch
                          AND NEW.observed_python_implementation =
                              target.python_implementation
                          AND NEW.observed_python_major = target.python_major
                          AND NEW.observed_python_minor = target.python_minor
                          AND NEW.observed_python_patch = target.python_patch
                          AND NEW.observed_at < attestation.expires_at
                      )
                  )
            ) THEN
                RAISE EXCEPTION 'django-ray target execution outcome lineage is invalid'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE TRIGGER ray_tevid_guard_0026
        BEFORE INSERT OR UPDATE ON {evidence_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_tevid_0026()
        """,
        f"""
        CREATE TRIGGER ray_teout_guard_0026
        BEFORE INSERT OR UPDATE ON {outcome_table}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_teout_0026()
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _sqlite_datetime_invalid(value: str) -> str:
    base = f"substr({value}, 1, 19)"
    return (
        f"typeof({value}) != 'text'\n"
        f"          OR instr({value}, char(0)) != 0\n"
        f"          OR length({value}) NOT IN (19, 26)\n"
        f"          OR substr({value}, 5, 1) != '-'\n"
        f"          OR substr({value}, 8, 1) != '-'\n"
        f"          OR substr({value}, 11, 1) != ' '\n"
        f"          OR substr({value}, 14, 1) != ':'\n"
        f"          OR substr({value}, 17, 1) != ':'\n"
        f"          OR substr({value}, 1, 4) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 6, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 9, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 12, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 15, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 18, 2) GLOB '*[^0-9]*'\n"
        f"          OR substr({value}, 1, 4) = '0000'\n"
        f"          OR CAST(substr({value}, 12, 2) AS INTEGER) NOT BETWEEN 0 AND 23\n"
        f"          OR datetime({base}) IS NULL\n"
        f"          OR strftime('%Y-%m-%d %H:%M:%S', {base}) != {base}\n"
        f"          OR (length({value}) = 26 AND (\n"
        f"                 substr({value}, 20, 1) != '.'\n"
        f"                 OR substr({value}, 21, 6) GLOB '*[^0-9]*'\n"
        f"             ))"
    )


def _sqlite_text_invalid(value: str, *, maximum: int) -> str:
    return (
        f"typeof({value}) != 'text'\n"
        f"          OR instr({value}, char(0)) != 0\n"
        f"          OR length({value}) NOT BETWEEN 1 AND {maximum}"
    )


def _sqlite_digest_invalid(value: str) -> str:
    return (
        f"typeof({value}) != 'text'\n"
        f"          OR instr({value}, char(0)) != 0\n"
        f"          OR length({value}) != 71\n"
        f"          OR substr({value}, 1, 7) != 'sha256:'\n"
        f"          OR substr({value}, 8) GLOB '*[^0-9a-f]*'"
    )


def _sqlite_python_invalid(value: str) -> str:
    return (
        f"{_sqlite_text_invalid(value, maximum=64)}\n"
        f"          OR substr({value}, 1, 1) NOT GLOB '[a-z]'\n"
        f"          OR {value} GLOB '*[^a-z0-9_.-]*'"
    )


def _sqlite_cluster_session_invalid(value: str) -> str:
    return (
        f"{_sqlite_text_invalid(value, maximum=256)}\n"
        f"          OR length({value}) < 9\n"
        f"          OR substr({value}, 1, 8) != 'session_'\n"
        f"          OR substr({value}, 9, 1) NOT GLOB '[A-Za-z0-9]'\n"
        f"          OR substr({value}, 9) GLOB '*[^A-Za-z0-9_.-]*'"
    )


def _install_sqlite_fences(apps, schema_editor) -> None:
    (
        evidence_table,
        outcome_table,
        execution_table,
        selection_table,
        binding_table,
        route_revision_table,
        target_table,
        policy_table,
        attestation_table,
        capability_table,
        lease_table,
    ) = _evidence_tables(apps, schema_editor)
    evidence_base_invalid = f"""
          typeof(NEW.target_execution_evidence_id) != 'integer'
          OR (NEW.target_execution_evidence_id != -1
              AND NEW.target_execution_evidence_id < 1)
          OR typeof(NEW.execution_id) != 'integer'
          OR NEW.execution_id < 1
          OR {_sqlite_text_invalid("NEW.task_id", maximum=255)}
          OR typeof(NEW.route_selection_id) != 'integer'
          OR NEW.route_selection_id < 1
          OR typeof(NEW.attempt_number) != 'integer'
          OR NEW.attempt_number NOT BETWEEN 1 AND {_MAX_POSITIVE_INTEGER}
          OR typeof(NEW.execution_generation) != 'integer'
          OR NEW.execution_generation NOT BETWEEN 1 AND {_MAX_COUNTER}
          OR {_sqlite_text_invalid("NEW.target_id", maximum=128)}
          OR substr(NEW.target_id, 1, 1) NOT GLOB '[a-z0-9]'
          OR NEW.target_id GLOB '*[^a-z0-9_.-]*'
          OR typeof(NEW.target_policy_id) != 'integer'
          OR NEW.target_policy_id < 1
          OR typeof(NEW.claim_attestation_id) != 'integer'
          OR NEW.claim_attestation_id < 1
          OR typeof(NEW.worker_target_capability_id) != 'integer'
          OR NEW.worker_target_capability_id < 1
          OR typeof(NEW.worker_target_capability_schema_version) != 'integer'
          OR NEW.worker_target_capability_schema_version != 1
          OR typeof(NEW.worker_target_capability_revision) != 'integer'
          OR NEW.worker_target_capability_revision NOT BETWEEN 1 AND {_MAX_COUNTER}
          OR {_sqlite_datetime_invalid("NEW.worker_target_capability_advertised_at")}
          OR {_sqlite_text_invalid("NEW.worker_lease_id", maximum=255)}
          OR {_sqlite_text_invalid("NEW.worker_lease_hostname", maximum=255)}
          OR typeof(NEW.worker_lease_pid) != 'integer'
          OR NEW.worker_lease_pid NOT BETWEEN 1 AND {_MAX_POSITIVE_INTEGER}
          OR {_sqlite_datetime_invalid("NEW.worker_lease_started_at")}
          OR typeof(NEW.runner_family) != 'text'
          OR NEW.runner_family != 'ray_core'
          OR typeof(NEW.manager_ray_major) != 'integer'
          OR NEW.manager_ray_major NOT BETWEEN 1 AND {_MAX_COUNTER}
          OR typeof(NEW.manager_ray_minor) != 'integer'
          OR NEW.manager_ray_minor NOT BETWEEN 0 AND {_MAX_COUNTER}
          OR typeof(NEW.manager_ray_patch) != 'integer'
          OR NEW.manager_ray_patch NOT BETWEEN 0 AND {_MAX_COUNTER}
          OR {_sqlite_python_invalid("NEW.manager_python_implementation")}
          OR typeof(NEW.manager_python_major) != 'integer'
          OR NEW.manager_python_major NOT BETWEEN 1 AND {_MAX_COUNTER}
          OR typeof(NEW.manager_python_minor) != 'integer'
          OR NEW.manager_python_minor NOT BETWEEN 0 AND {_MAX_COUNTER}
          OR typeof(NEW.manager_python_patch) != 'integer'
          OR NEW.manager_python_patch NOT BETWEEN 0 AND {_MAX_COUNTER}
          OR {_sqlite_digest_invalid("NEW.target_execution_evidence_digest")}
          OR {_sqlite_digest_invalid("NEW.target_expectation_digest")}
          OR {_sqlite_digest_invalid("NEW.claim_attestation_digest")}
          OR typeof(NEW.schema_version) != 'integer'
          OR NEW.schema_version != 1
          OR {_sqlite_datetime_invalid("NEW.claimed_at")}
          OR NEW.worker_target_capability_advertised_at < NEW.worker_lease_started_at
    """.strip()
    evidence_state_invalid = f"""
          NOT EXISTS (
              SELECT 1
              FROM {execution_table} AS execution
              JOIN {selection_table} AS selection
                ON selection.binding_id = NEW.route_selection_id
               AND selection.binding_id = execution.id
              JOIN {binding_table} AS binding
                ON binding.execution_id = selection.binding_id
              JOIN {route_revision_table} AS route_revision
                ON route_revision.id = selection.route_revision_id
               AND route_revision.target_policy_id = binding.target_policy_id
              JOIN {policy_table} AS selected_policy
                ON selected_policy.id = binding.target_policy_id
               AND selected_policy.target_id = NEW.target_id
              JOIN {target_table} AS target
                ON target.target_key = NEW.target_id
              JOIN {policy_table} AS policy
                ON policy.id = NEW.target_policy_id
               AND policy.target_id = target.target_key
              JOIN {attestation_table} AS attestation
                ON attestation.id = NEW.claim_attestation_id
               AND attestation.policy_id = policy.id
              JOIN {lease_table} AS lease
                ON lease.worker_id = NEW.worker_lease_id
              JOIN {capability_table} AS capability
                ON capability.id = NEW.worker_target_capability_id
               AND capability.lease_id = lease.worker_id
               AND capability.target_id = target.target_key
               AND capability.target_policy_id = policy.id
               AND capability.attestation_id = attestation.id
              WHERE execution.id = NEW.execution_id
                AND execution.execution_protocol_version = 2
                AND typeof(execution.execution_protocol_version) = 'integer'
                AND execution.task_id = NEW.task_id
                AND typeof(execution.task_id) = 'text'
                AND execution.state = 'RUNNING'
                AND typeof(execution.state) = 'text'
                AND execution.attempt_number = NEW.attempt_number
                AND typeof(execution.attempt_number) = 'integer'
                AND execution.execution_generation = NEW.execution_generation
                AND typeof(execution.execution_generation) = 'integer'
                AND execution.claimed_by_worker = NEW.worker_lease_id
                AND typeof(execution.claimed_by_worker) = 'text'
                AND execution.started_at IS NOT NULL
                AND NOT ({_sqlite_datetime_invalid("execution.started_at")})
                AND execution.started_at <= NEW.claimed_at
                AND execution.finished_at IS NULL
                AND lease.hostname = NEW.worker_lease_hostname
                AND lease.pid = NEW.worker_lease_pid
                AND lease.started_at = NEW.worker_lease_started_at
                AND lease.is_active = 1
                AND typeof(lease.is_active) = 'integer'
                AND lease.stopped_at IS NULL
                AND lease.capability_schema_version = 1
                AND typeof(lease.capability_schema_version) = 'integer'
                AND lease.legacy_admission_token_id IS NULL
                AND typeof(lease.min_supported_execution_protocol_version) = 'integer'
                AND lease.min_supported_execution_protocol_version <= 2
                AND typeof(lease.max_supported_execution_protocol_version) = 'integer'
                AND lease.max_supported_execution_protocol_version >= 2
                AND capability.lease_hostname = NEW.worker_lease_hostname
                AND capability.lease_pid = NEW.worker_lease_pid
                AND capability.lease_started_at = NEW.worker_lease_started_at
                AND capability.runner_family = NEW.runner_family
                AND capability.manager_ray_major = NEW.manager_ray_major
                AND capability.manager_ray_minor = NEW.manager_ray_minor
                AND capability.manager_ray_patch = NEW.manager_ray_patch
                AND capability.manager_python_implementation =
                    NEW.manager_python_implementation
                AND capability.manager_python_major = NEW.manager_python_major
                AND capability.manager_python_minor = NEW.manager_python_minor
                AND capability.manager_python_patch = NEW.manager_python_patch
                AND capability.schema_version =
                    NEW.worker_target_capability_schema_version
                AND capability.revision = NEW.worker_target_capability_revision
                AND capability.advertised_at =
                    NEW.worker_target_capability_advertised_at
                AND target.runner_family = NEW.runner_family
                AND target.ray_major = NEW.manager_ray_major
                AND target.ray_minor = NEW.manager_ray_minor
                AND target.ray_patch = NEW.manager_ray_patch
                AND target.python_implementation = NEW.manager_python_implementation
                AND target.python_major = NEW.manager_python_major
                AND target.python_minor = NEW.manager_python_minor
                AND target.python_patch = NEW.manager_python_patch
                AND policy.desired_state IN ('active', 'draining')
                AND policy.revision = (
                    SELECT MAX(candidate.revision)
                    FROM {policy_table} AS candidate
                    WHERE candidate.target_id = target.target_key
                )
                AND policy.revision = (
                    SELECT COUNT(*)
                    FROM {policy_table} AS candidate
                    WHERE candidate.target_id = target.target_key
                )
                AND attestation.revision = (
                    SELECT MAX(candidate.revision)
                    FROM {attestation_table} AS candidate
                    WHERE candidate.policy_id = policy.id
                )
                AND attestation.revision = (
                    SELECT COUNT(*)
                    FROM {attestation_table} AS candidate
                    WHERE candidate.policy_id = policy.id
                )
                AND policy.expectation_digest = NEW.target_expectation_digest
                AND attestation.expectation_digest = NEW.target_expectation_digest
                AND attestation.attestation_digest = NEW.claim_attestation_digest
                AND NEW.claimed_at >= lease.started_at
                AND NEW.claimed_at >= capability.advertised_at
                AND NEW.claimed_at >= attestation.recorded_at
                AND NEW.claimed_at < attestation.expires_at
          )
    """.strip()
    observed_columns = (
        "observed_cluster_session",
        "observed_node_id",
        "observed_membership_digest",
        "observed_ray_major",
        "observed_ray_minor",
        "observed_ray_patch",
        "observed_python_implementation",
        "observed_python_major",
        "observed_python_minor",
        "observed_python_patch",
        "observed_proof_digest",
        "observed_at",
    )
    observation_empty = " AND ".join(f"NEW.{column} IS NULL" for column in observed_columns)
    observation_complete = f"""
          NOT ({observation_empty})
          AND NOT ({_sqlite_cluster_session_invalid("NEW.observed_cluster_session")})
          AND typeof(NEW.observed_node_id) = 'text'
          AND instr(NEW.observed_node_id, char(0)) = 0
          AND length(NEW.observed_node_id) = 56
          AND NEW.observed_node_id NOT GLOB '*[^0-9a-f]*'
          AND NOT ({_sqlite_digest_invalid("NEW.observed_membership_digest")})
          AND typeof(NEW.observed_ray_major) = 'integer'
          AND NEW.observed_ray_major BETWEEN 1 AND {_MAX_COUNTER}
          AND typeof(NEW.observed_ray_minor) = 'integer'
          AND NEW.observed_ray_minor BETWEEN 0 AND {_MAX_COUNTER}
          AND typeof(NEW.observed_ray_patch) = 'integer'
          AND NEW.observed_ray_patch BETWEEN 0 AND {_MAX_COUNTER}
          AND NOT ({_sqlite_python_invalid("NEW.observed_python_implementation")})
          AND typeof(NEW.observed_python_major) = 'integer'
          AND NEW.observed_python_major BETWEEN 1 AND {_MAX_COUNTER}
          AND typeof(NEW.observed_python_minor) = 'integer'
          AND NEW.observed_python_minor BETWEEN 0 AND {_MAX_COUNTER}
          AND typeof(NEW.observed_python_patch) = 'integer'
          AND NEW.observed_python_patch BETWEEN 0 AND {_MAX_COUNTER}
          AND NOT ({_sqlite_digest_invalid("NEW.observed_proof_digest")})
          AND NOT ({_sqlite_datetime_invalid("NEW.observed_at")})
    """.strip()
    reasons = ", ".join(f"'{reason}'" for reason in _COMPATIBILITY_REASONS)
    outcome_base_invalid = f"""
          typeof(NEW.evidence_id) != 'integer'
          OR NEW.evidence_id < 1
          OR typeof(NEW.status) != 'text'
          OR NEW.status NOT IN ('VERIFIED', 'COMPATIBILITY_REJECTED', 'UNCERTAIN')
          OR {_sqlite_digest_invalid("NEW.target_execution_evidence_digest")}
          OR {_sqlite_digest_invalid("NEW.target_expectation_digest")}
          OR {_sqlite_digest_invalid("NEW.claim_attestation_digest")}
          OR {_sqlite_datetime_invalid("NEW.recorded_at")}
          OR NOT (({observation_empty}) OR ({observation_complete}))
          OR (
              NEW.status = 'VERIFIED'
              AND (
                  typeof(NEW.application_invoked) != 'integer'
                  OR NEW.application_invoked != 1
                  OR NEW.compatibility_reason IS NOT NULL
                  OR NOT ({observation_complete})
              )
          )
          OR (
              NEW.status = 'COMPATIBILITY_REJECTED'
              AND (
                  typeof(NEW.application_invoked) != 'integer'
                  OR NEW.application_invoked != 0
                  OR typeof(NEW.compatibility_reason) != 'text'
                  OR NEW.compatibility_reason NOT IN ({reasons})
                  OR NOT ({observation_complete})
              )
          )
          OR (
              NEW.status = 'UNCERTAIN'
              AND (
                  NEW.application_invoked IS NOT NULL
                  OR NEW.compatibility_reason IS NOT NULL
                  OR NOT ({observation_empty})
              )
          )
          OR (({observation_complete}) AND NEW.observed_at > NEW.recorded_at)
    """.strip()
    outcome_state_invalid = f"""
          NOT EXISTS (
              SELECT 1
              FROM {evidence_table} AS evidence
              JOIN {target_table} AS target
                ON target.target_key = evidence.target_id
              JOIN {attestation_table} AS attestation
                ON attestation.id = evidence.claim_attestation_id
              WHERE evidence.target_execution_evidence_id = NEW.evidence_id
                AND evidence.target_execution_evidence_digest =
                    NEW.target_execution_evidence_digest
                AND evidence.target_expectation_digest = NEW.target_expectation_digest
                AND evidence.claim_attestation_digest = NEW.claim_attestation_digest
                AND NEW.recorded_at >= evidence.claimed_at
                AND (
                    NOT ({observation_complete})
                    OR NEW.observed_at >= evidence.claimed_at
                )
                AND (
                    NEW.status != 'VERIFIED'
                    OR (
                        NEW.observed_cluster_session = target.cluster_session
                        AND NEW.observed_membership_digest = attestation.membership_digest
                        AND NEW.observed_ray_major = target.ray_major
                        AND NEW.observed_ray_minor = target.ray_minor
                        AND NEW.observed_ray_patch = target.ray_patch
                        AND NEW.observed_python_implementation =
                            target.python_implementation
                        AND NEW.observed_python_major = target.python_major
                        AND NEW.observed_python_minor = target.python_minor
                        AND NEW.observed_python_patch = target.python_patch
                        AND NEW.observed_at < attestation.expires_at
                    )
                )
          )
    """.strip()
    statements = (
        f"""
        CREATE TRIGGER ray_tevid_insert_0026
        BEFORE INSERT ON {evidence_table}
        FOR EACH ROW
        WHEN {evidence_base_invalid}
          OR {evidence_state_invalid}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray target execution evidence is invalid');
        END
        """,
        f"""
        CREATE TRIGGER ray_tevid_update_0026
        BEFORE UPDATE ON {evidence_table}
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'django-ray target execution evidence is immutable');
        END
        """,
        f"""
        CREATE TRIGGER ray_teout_insert_0026
        BEFORE INSERT ON {outcome_table}
        FOR EACH ROW
        WHEN {outcome_base_invalid}
          OR {outcome_state_invalid}
        BEGIN
            SELECT RAISE(ABORT, 'django-ray target execution outcome is invalid');
        END
        """,
        f"""
        CREATE TRIGGER ray_teout_update_0026
        BEFORE UPDATE ON {outcome_table}
        FOR EACH ROW
        BEGIN
            SELECT RAISE(ABORT, 'django-ray target execution outcome is immutable');
        END
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _install_evidence_fences(apps, schema_editor) -> None:
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        _install_postgresql_fences(apps, schema_editor)
    elif vendor == "sqlite":
        _install_sqlite_fences(apps, schema_editor)
    else:
        raise RuntimeError(
            "django-ray target execution evidence supports only SQLite and PostgreSQL"
        )


def _remove_evidence_fences(apps, schema_editor) -> None:
    evidence_table, outcome_table, *_ = _evidence_tables(apps, schema_editor)
    quote = schema_editor.quote_name
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        for trigger, table in (
            ("ray_tevid_guard_0026", evidence_table),
            ("ray_teout_guard_0026", outcome_table),
        ):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {quote(trigger)} ON {table}")
        for function in (
            "django_ray_guard_tevid_0026",
            "django_ray_guard_teout_0026",
        ):
            schema_editor.execute(f"DROP FUNCTION IF EXISTS {quote(function)}()")
    elif vendor == "sqlite":
        for trigger in (
            "ray_tevid_insert_0026",
            "ray_tevid_update_0026",
            "ray_teout_insert_0026",
            "ray_teout_update_0026",
        ):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {quote(trigger)}")
    else:
        raise RuntimeError(
            "django-ray target execution evidence supports only SQLite and PostgreSQL"
        )


def _guard_empty_evidence(apps, schema_editor) -> None:
    evidence_table, outcome_table, *_ = _evidence_tables(apps, schema_editor)
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            f"LOCK TABLE {evidence_table}, {outcome_table} IN ACCESS EXCLUSIVE MODE"
        )
    elif vendor == "sqlite":
        schema_editor.execute(
            f"UPDATE {evidence_table} "
            "SET target_execution_evidence_id = target_execution_evidence_id WHERE 0"
        )
        schema_editor.execute(f"UPDATE {outcome_table} SET evidence_id = evidence_id WHERE 0")
    else:
        raise RuntimeError(
            "django-ray target execution evidence supports only SQLite and PostgreSQL"
        )
    alias = schema_editor.connection.alias
    if any(
        apps.get_model("django_ray", model_name).objects.using(alias).exists()
        for model_name in (
            "RayTaskTargetExecutionOutcome",
            "RayTaskTargetExecutionEvidence",
        )
    ):
        raise RuntimeError(
            "django-ray target execution evidence rollback requires both tables to be empty"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0025_ray_worker_target_capabilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="RayTaskTargetExecutionEvidence",
            fields=[
                (
                    "target_execution_evidence_id",
                    models.BigAutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "task_id",
                    models.CharField(
                        editable=False,
                        help_text=("Immutable task identity snapshot covered by the claim digest"),
                        max_length=255,
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2147483647),
                        ],
                    ),
                ),
                (
                    "execution_generation",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9223372036854775807),
                        ],
                    ),
                ),
                (
                    "worker_target_capability_id",
                    models.PositiveBigIntegerField(
                        editable=False,
                        help_text="Snapshot only; deliberately not a capability foreign key",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "worker_target_capability_schema_version",
                    models.PositiveSmallIntegerField(
                        editable=False, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "worker_target_capability_revision",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9223372036854775807),
                        ],
                    ),
                ),
                ("worker_target_capability_advertised_at", models.DateTimeField(editable=False)),
                ("worker_lease_id", models.CharField(editable=False, max_length=255)),
                ("worker_lease_hostname", models.CharField(editable=False, max_length=255)),
                (
                    "worker_lease_pid",
                    models.PositiveIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2147483647),
                        ],
                    ),
                ),
                ("worker_lease_started_at", models.DateTimeField(editable=False)),
                (
                    "runner_family",
                    models.CharField(
                        choices=[("ray_core", "ray_core"), ("ray_job", "ray_job")],
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "manager_ray_major",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9223372036854775807),
                        ],
                    ),
                ),
                (
                    "manager_ray_minor",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "manager_ray_patch",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "manager_python_implementation",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a normalized Python implementation identifier.",
                                regex="\\A[a-z][a-z0-9_.-]{0,63}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "manager_python_major",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9223372036854775807),
                        ],
                    ),
                ),
                (
                    "manager_python_minor",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "manager_python_patch",
                    models.PositiveBigIntegerField(
                        editable=False,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "target_execution_evidence_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "target_expectation_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "claim_attestation_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(
                        db_default=1,
                        default=1,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "claim_attestation",
                    models.ForeignKey(
                        editable=False,
                        help_text="Exact latest target attestation accepted at claim time",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_evidence",
                        to="django_ray.raytargetattestationrevision",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ray_target_execution_evidence",
                        to="django_ray.raytaskexecution",
                    ),
                ),
                (
                    "route_selection",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_evidence",
                        to="django_ray.raytasktargetrouteselection",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_evidence",
                        to="django_ray.raytarget",
                    ),
                ),
                (
                    "target_policy",
                    models.ForeignKey(
                        editable=False,
                        help_text="Exact latest target policy accepted at claim time",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_evidence",
                        to="django_ray.raytargetpolicyrevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ray Task Target Execution Evidence",
                "verbose_name_plural": "Ray Task Target Execution Evidence",
            },
        ),
        migrations.CreateModel(
            name="RayTaskTargetExecutionOutcome",
            fields=[
                (
                    "evidence",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="outcome",
                        serialize=False,
                        to="django_ray.raytasktargetexecutionevidence",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified"),
                            ("COMPATIBILITY_REJECTED", "Compatibility rejected"),
                            ("UNCERTAIN", "Uncertain"),
                        ],
                        editable=False,
                        max_length=24,
                    ),
                ),
                (
                    "application_invoked",
                    models.BooleanField(
                        blank=True,
                        editable=False,
                        help_text="True only after verified invocation; null when invocation is uncertain",
                        null=True,
                    ),
                ),
                (
                    "compatibility_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("expired", "Expired"),
                            ("cluster_session_mismatch", "Cluster session mismatch"),
                            ("ray_version_mismatch", "Ray version mismatch"),
                            ("python_implementation_mismatch", "Python implementation mismatch"),
                            ("python_version_mismatch", "Python version mismatch"),
                            ("current_node_not_attested", "Current node not attested"),
                            ("membership_mismatch", "Membership mismatch"),
                        ],
                        editable=False,
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "target_execution_evidence_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "target_expectation_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "claim_attestation_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "observed_cluster_session",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=256,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical Ray cluster session name.",
                                regex="\\Asession_[A-Za-z0-9][A-Za-z0-9_.-]{0,247}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "observed_node_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=56,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical Ray node identifier.",
                                regex="\\A[0-9a-f]{56}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "observed_membership_digest",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=71,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "observed_ray_major",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9223372036854775807),
                        ],
                    ),
                ),
                (
                    "observed_ray_minor",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "observed_ray_patch",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "observed_python_implementation",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a normalized Python implementation identifier.",
                                regex="\\A[a-z][a-z0-9_.-]{0,63}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "observed_python_major",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9223372036854775807),
                        ],
                    ),
                ),
                (
                    "observed_python_minor",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "observed_python_patch",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(9223372036854775807)],
                    ),
                ),
                (
                    "observed_proof_digest",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=71,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("observed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            options={
                "verbose_name": "Ray Task Target Execution Outcome",
                "verbose_name_plural": "Ray Task Target Execution Outcomes",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["VERIFIED", "COMPATIBILITY_REJECTED", "UNCERTAIN"])
                        ),
                        name="ray_teout_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("compatibility_reason__isnull", True),
                            (
                                "compatibility_reason__in",
                                [
                                    "expired",
                                    "cluster_session_mismatch",
                                    "ray_version_mismatch",
                                    "python_implementation_mismatch",
                                    "python_version_mismatch",
                                    "current_node_not_attested",
                                    "membership_mismatch",
                                ],
                            ),
                            _connector="OR",
                        ),
                        name="ray_teout_reason_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("application_invoked", True),
                                ("compatibility_reason__isnull", True),
                                ("status", "VERIFIED"),
                            ),
                            models.Q(
                                ("application_invoked", False),
                                ("compatibility_reason__isnull", False),
                                ("status", "COMPATIBILITY_REJECTED"),
                            ),
                            models.Q(
                                ("application_invoked__isnull", True),
                                ("compatibility_reason__isnull", True),
                                ("status", "UNCERTAIN"),
                            ),
                            _connector="OR",
                        ),
                        name="ray_teout_verdict_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("observed_at__isnull", True),
                                ("observed_cluster_session__isnull", True),
                                ("observed_membership_digest__isnull", True),
                                ("observed_node_id__isnull", True),
                                ("observed_proof_digest__isnull", True),
                                ("observed_python_implementation__isnull", True),
                                ("observed_python_major__isnull", True),
                                ("observed_python_minor__isnull", True),
                                ("observed_python_patch__isnull", True),
                                ("observed_ray_major__isnull", True),
                                ("observed_ray_minor__isnull", True),
                                ("observed_ray_patch__isnull", True),
                            ),
                            models.Q(
                                ("observed_at__isnull", False),
                                ("observed_cluster_session__isnull", False),
                                ("observed_membership_digest__isnull", False),
                                ("observed_node_id__isnull", False),
                                ("observed_proof_digest__isnull", False),
                                ("observed_python_implementation__isnull", False),
                                ("observed_python_major__isnull", False),
                                ("observed_python_minor__isnull", False),
                                ("observed_python_patch__isnull", False),
                                ("observed_ray_major__isnull", False),
                                ("observed_ray_minor__isnull", False),
                                ("observed_ray_patch__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ray_teout_observation_group",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("observed_at__isnull", True), ("status", "UNCERTAIN")),
                            models.Q(
                                models.Q(("status", "UNCERTAIN"), _negated=True),
                                ("observed_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ray_teout_proof_required",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="raytasktargetexecutionevidence",
            index=models.Index(fields=["target", "-claimed_at"], name="ray_tevid_target_claim_idx"),
        ),
        migrations.AddConstraint(
            model_name="raytasktargetexecutionevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_execution_evidence_id__gte", 1)),
                name="ray_tevid_id_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytasktargetexecutionevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attempt_number__gte", 1),
                    ("attempt_number__lte", 2147483647),
                    ("execution_generation__gte", 1),
                ),
                name="ray_tevid_generation_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytasktargetexecutionevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("worker_target_capability_id__gte", 1),
                    ("worker_target_capability_revision__gte", 1),
                    ("worker_target_capability_schema_version", 1),
                ),
                name="ray_tevid_capability_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytasktargetexecutionevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("worker_lease_pid__gte", 1),
                    ("worker_lease_pid__lte", 2147483647),
                ),
                name="ray_tevid_lease_pid_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytasktargetexecutionevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("runner_family", "ray_core")),
                name="ray_tevid_runner_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytasktargetexecutionevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("manager_python_major__gte", 1),
                    ("manager_python_major__lte", 9223372036854775807),
                    ("manager_python_minor__gte", 0),
                    ("manager_python_minor__lte", 9223372036854775807),
                    ("manager_python_patch__gte", 0),
                    ("manager_python_patch__lte", 9223372036854775807),
                    ("manager_ray_major__gte", 1),
                    ("manager_ray_major__lte", 9223372036854775807),
                    ("manager_ray_minor__gte", 0),
                    ("manager_ray_minor__lte", 9223372036854775807),
                    ("manager_ray_patch__gte", 0),
                    ("manager_ray_patch__lte", 9223372036854775807),
                ),
                name="ray_tevid_runtime_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytasktargetexecutionevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version", 1)), name="ray_tevid_schema_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="raytasktargetexecutionevidence",
            constraint=models.UniqueConstraint(
                fields=("execution", "attempt_number", "execution_generation"),
                name="ray_tevid_generation_uniq",
            ),
        ),
        migrations.RunPython(
            _install_evidence_fences,
            _remove_evidence_fences,
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            _guard_empty_evidence,
        ),
    ]
