# Generated by Django 6.1.1 on 2026-09-12 01:49

import datetime

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


def _tables(apps, schema_editor):
    return tuple(
        schema_editor.quote_name(apps.get_model("django_ray", name)._meta.db_table)
        for name in (
            "RayTargetProbeChallenge",
            "TaskWorkerLease",
            "RayTarget",
            "RayTargetPolicyRevision",
        )
    )


_IDENTITY_COLUMNS = (
    "id",
    "lease_id",
    "lease_hostname",
    "lease_pid",
    "lease_started_at",
    "runner_family",
    "schema_version",
)
_PROBE_COLUMNS = (
    "expected_target_policy_id",
    "configuration_digest",
    "nonce_digest",
    "issued_at",
    "expires_at",
)


def _related_valid(tables):
    _challenge, lease, target, policy = tables
    return f"""
        EXISTS (
            SELECT 1 FROM {lease} AS lease
            WHERE lease.worker_id = NEW.lease_id
                AND lease.hostname = NEW.lease_hostname
                AND lease.pid = NEW.lease_pid
                AND lease.started_at = NEW.lease_started_at
                AND lease.is_active AND lease.stopped_at IS NULL
                AND lease.capability_schema_version = 1
                AND lease.legacy_admission_token_id IS NULL
                AND lease.min_supported_execution_protocol_version BETWEEN 1 AND 32767
                AND lease.max_supported_execution_protocol_version
                    BETWEEN lease.min_supported_execution_protocol_version AND 32767
                AND lease.last_heartbeat_at <= COALESCE(NEW.consumed_at, NEW.issued_at)
        ) AND (NEW.expected_target_policy_id IS NULL OR EXISTS (
            SELECT 1 FROM {policy} AS policy
            JOIN {target} AS target ON policy.target_id = target.target_key
            WHERE policy.id = NEW.expected_target_policy_id
                AND target.runner_family = NEW.runner_family
                AND policy.desired_state IN ('active', 'draining')
                AND policy.created_at <= NEW.issued_at
                AND policy.revision = (
                    SELECT MAX(candidate.revision) FROM {policy} AS candidate
                    WHERE candidate.target_id = target.target_key
                )
                AND policy.revision = (
                    SELECT COUNT(*) FROM {policy} AS candidate
                    WHERE candidate.target_id = target.target_key
                )
        ))
    """


def _limit_invalid(challenge, *, exclude):
    return f"""
        (NEW.runner_family = 'ray_core' AND EXISTS (
            SELECT 1 FROM {challenge} WHERE lease_id = NEW.lease_id {exclude}
        )) OR EXISTS (
            SELECT 1 FROM {challenge} WHERE lease_id = NEW.lease_id
                AND runner_family <> NEW.runner_family {exclude}
        ) OR (SELECT COUNT(*) FROM {challenge}
            WHERE lease_id = NEW.lease_id {exclude}) >= 64
    """


def _replacement_policy_valid(policy):
    return f"""
        OLD.expected_target_policy_id IS NULL
        OR NEW.configuration_digest <> OLD.configuration_digest
        OR EXISTS (SELECT 1 FROM {policy} AS old_policy JOIN {policy} AS new_policy
            ON old_policy.target_id = new_policy.target_id
            WHERE old_policy.id = OLD.expected_target_policy_id
                AND new_policy.id = NEW.expected_target_policy_id)
    """


def _postgresql(apps, schema_editor):
    tables = _tables(apps, schema_editor)
    challenge, lease, target, _policy = tables
    identity_changed = " OR ".join(
        f"NEW.{column} IS DISTINCT FROM OLD.{column}" for column in _IDENTITY_COLUMNS
    )
    probe_same = " AND ".join(
        f"NEW.{column} IS NOT DISTINCT FROM OLD.{column}" for column in _PROBE_COLUMNS
    )
    statements = (
        f"""
        CREATE FUNCTION django_ray_guard_tprobe_0027() RETURNS trigger
        LANGUAGE plpgsql AS $django_ray$
        BEGIN
            IF TG_OP = 'UPDATE' AND NEW IS NOT DISTINCT FROM OLD THEN RETURN NEW; END IF;
            IF NEW.schema_version <> 1 OR NEW.revision NOT BETWEEN 1 AND 9223372036854775807
                OR NEW.runner_family NOT IN ('ray_core', 'ray_job')
                OR NEW.configuration_digest !~ '^sha256:[0-9a-f]{{64}}$'
                OR NEW.nonce_digest !~ '^[0-9a-f]{{64}}$'
                OR char_length(NEW.lease_id) NOT BETWEEN 1 AND 255
                OR char_length(NEW.lease_hostname) NOT BETWEEN 1 AND 255
                OR NEW.lease_pid NOT BETWEEN 1 AND 2147483647
                OR NOT isfinite(NEW.issued_at) OR NOT isfinite(NEW.expires_at)
                OR NOT isfinite(NEW.lease_started_at)
                OR NEW.issued_at < NEW.lease_started_at
                OR NEW.expires_at <= NEW.issued_at
                OR NEW.expires_at > NEW.issued_at + INTERVAL '600 seconds'
                OR (NEW.consumed_at IS NOT NULL AND (
                    NOT isfinite(NEW.consumed_at) OR NEW.consumed_at < NEW.issued_at
                    OR NEW.consumed_at >= NEW.expires_at
                )) THEN
                RAISE EXCEPTION 'django-ray target probe challenge is invalid'
                    USING ERRCODE = '23514';
            END IF;
            IF TG_OP = 'INSERT' THEN
                IF NEW.revision <> 1 OR NEW.consumed_at IS NOT NULL THEN
                    RAISE EXCEPTION 'django-ray target probe challenge must begin pending'
                        USING ERRCODE = '23514';
                END IF;
            ELSE
                IF ({identity_changed}) OR OLD.revision >= 9223372036854775807
                    OR NEW.revision <> OLD.revision + 1 OR NOT (
                        (({probe_same}) AND OLD.consumed_at IS NULL
                            AND NEW.consumed_at IS NOT NULL)
                        OR (NEW.nonce_digest <> OLD.nonce_digest AND NEW.consumed_at IS NULL
                            AND NEW.issued_at >= OLD.issued_at
                            AND (OLD.consumed_at IS NULL OR NEW.issued_at >= OLD.consumed_at)
                            AND ({_replacement_policy_valid(_policy)}))
                    ) THEN
                    RAISE EXCEPTION 'django-ray target probe challenge transition is invalid'
                        USING ERRCODE = '23514';
                END IF;
            END IF;
            PERFORM 1 FROM {lease} WHERE worker_id = NEW.lease_id FOR UPDATE;
            PERFORM 1 FROM {target} WHERE target_key = (
                SELECT target_id FROM {_policy} WHERE id = NEW.expected_target_policy_id
            ) FOR SHARE;
            IF NOT ({_related_valid(tables)}) OR ({_limit_invalid(challenge, exclude="AND id <> NEW.id")}) THEN
                RAISE EXCEPTION 'django-ray target probe challenge binding is invalid'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE TRIGGER ray_tprobe_guard_0027 BEFORE INSERT OR UPDATE ON {challenge}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_tprobe_0027()
        """,
        f"""
        CREATE FUNCTION django_ray_clear_tprobe_lease_0027() RETURNS trigger
        LANGUAGE plpgsql AS $django_ray$
        BEGIN
            IF NEW.worker_id IS DISTINCT FROM OLD.worker_id
                OR NEW.hostname IS DISTINCT FROM OLD.hostname
                OR NEW.pid IS DISTINCT FROM OLD.pid
                OR NEW.started_at IS DISTINCT FROM OLD.started_at
                OR NOT NEW.is_active OR NEW.stopped_at IS NOT NULL
                OR NEW.capability_schema_version <> 1
                OR NEW.legacy_admission_token_id IS NOT NULL THEN
                DELETE FROM {challenge} WHERE lease_id = OLD.worker_id;
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE TRIGGER ray_tprobe_lease_0027 AFTER UPDATE ON {lease}
        FOR EACH ROW EXECUTE FUNCTION django_ray_clear_tprobe_lease_0027()
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _sqlite_datetime_invalid(column):
    value = f"NEW.{column}"
    base = f"substr({value}, 1, 19)"
    return f"""
        typeof({value}) != 'text' OR instr({value}, char(0)) != 0
        OR length({value}) NOT IN (19, 26) OR substr({value}, 1, 4) = '0000'
        OR {base} NOT GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]'
        OR datetime({base}) IS NULL OR strftime('%Y-%m-%d %H:%M:%S', {base}) != {base}
        OR CAST(substr({value}, 12, 2) AS INTEGER) NOT BETWEEN 0 AND 23
        OR (length({value}) = 26 AND (
            substr({value}, 20, 1) != '.' OR substr({value}, 21, 6) GLOB '*[^0-9]*'
        ))
    """


def _sqlite(apps, schema_editor):
    tables = _tables(apps, schema_editor)
    challenge, lease, _target, _policy = tables
    changed = " OR ".join(
        f"NEW.{column} IS NOT OLD.{column}"
        for column in (*_IDENTITY_COLUMNS, *_PROBE_COLUMNS, "revision", "consumed_at")
    )
    identity_changed = " OR ".join(
        f"NEW.{column} IS NOT OLD.{column}" for column in _IDENTITY_COLUMNS
    )
    probe_same = " AND ".join(f"NEW.{column} IS OLD.{column}" for column in _PROBE_COLUMNS)
    invalid = f"""
        typeof(NEW.schema_version) != 'integer' OR NEW.schema_version != 1
        OR typeof(NEW.revision) != 'integer' OR NEW.revision NOT BETWEEN 1 AND 9223372036854775807
        OR NEW.runner_family NOT IN ('ray_core', 'ray_job')
        OR typeof(NEW.lease_pid) != 'integer' OR NEW.lease_pid NOT BETWEEN 1 AND 2147483647
        OR typeof(NEW.lease_id) != 'text' OR length(NEW.lease_id) NOT BETWEEN 1 AND 255
        OR instr(NEW.lease_id, char(0)) != 0
        OR typeof(NEW.lease_hostname) != 'text' OR length(NEW.lease_hostname) NOT BETWEEN 1 AND 255
        OR instr(NEW.lease_hostname, char(0)) != 0
        OR typeof(NEW.nonce_digest) != 'text' OR length(NEW.nonce_digest) != 64
        OR instr(NEW.nonce_digest, char(0)) != 0
        OR NEW.nonce_digest GLOB '*[^0-9a-f]*'
        OR typeof(NEW.configuration_digest) != 'text' OR length(NEW.configuration_digest) != 71
        OR instr(NEW.configuration_digest, char(0)) != 0
        OR substr(NEW.configuration_digest, 1, 7) != 'sha256:'
        OR substr(NEW.configuration_digest, 8) GLOB '*[^0-9a-f]*'
        OR ({_sqlite_datetime_invalid("lease_started_at")})
        OR ({_sqlite_datetime_invalid("issued_at")})
        OR ({_sqlite_datetime_invalid("expires_at")})
        OR (NEW.consumed_at IS NOT NULL AND ({_sqlite_datetime_invalid("consumed_at")}))
        OR NOT ({_related_valid(tables)})
    """
    statements = (
        f"""
        CREATE TRIGGER ray_tprobe_insert_0027 BEFORE INSERT ON {challenge}
        FOR EACH ROW WHEN ({invalid}) OR NEW.revision != 1 OR NEW.consumed_at IS NOT NULL
            OR ({_limit_invalid(challenge, exclude="")})
        BEGIN SELECT RAISE(ABORT, 'django-ray target probe challenge is invalid'); END
        """,
        f"""
        CREATE TRIGGER ray_tprobe_update_0027 BEFORE UPDATE ON {challenge}
        FOR EACH ROW WHEN ({changed}) AND (
            ({invalid}) OR ({identity_changed}) OR OLD.revision >= 9223372036854775807
            OR NEW.revision != OLD.revision + 1 OR NOT (
                (({probe_same}) AND OLD.consumed_at IS NULL AND NEW.consumed_at IS NOT NULL)
                OR (NEW.nonce_digest != OLD.nonce_digest AND NEW.consumed_at IS NULL
                    AND NEW.issued_at >= OLD.issued_at
                    AND (OLD.consumed_at IS NULL OR NEW.issued_at >= OLD.consumed_at)
                    AND ({_replacement_policy_valid(_policy)}))
            ) OR ({_limit_invalid(challenge, exclude="AND id <> NEW.id")})
        )
        BEGIN SELECT RAISE(ABORT, 'django-ray target probe challenge transition is invalid'); END
        """,
        f"""
        CREATE TRIGGER ray_tprobe_lease_0027 AFTER UPDATE ON {lease}
        FOR EACH ROW WHEN NEW.worker_id IS NOT OLD.worker_id
            OR NEW.hostname IS NOT OLD.hostname OR NEW.pid IS NOT OLD.pid
            OR NEW.started_at IS NOT OLD.started_at OR NOT NEW.is_active
            OR NEW.stopped_at IS NOT NULL OR NEW.capability_schema_version != 1
            OR NEW.legacy_admission_token_id IS NOT NULL
        BEGIN DELETE FROM {challenge} WHERE lease_id = OLD.worker_id; END
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _install(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        _postgresql(apps, schema_editor)
    elif schema_editor.connection.vendor == "sqlite":
        _sqlite(apps, schema_editor)
    else:
        raise RuntimeError("Ray target probe challenges require SQLite or PostgreSQL")


def _uninstall(apps, schema_editor):
    challenge, lease, _target, _policy = _tables(apps, schema_editor)
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(f"DROP TRIGGER IF EXISTS ray_tprobe_guard_0027 ON {challenge}")
        schema_editor.execute(f"DROP TRIGGER IF EXISTS ray_tprobe_lease_0027 ON {lease}")
        schema_editor.execute("DROP FUNCTION IF EXISTS django_ray_guard_tprobe_0027()")
        schema_editor.execute("DROP FUNCTION IF EXISTS django_ray_clear_tprobe_lease_0027()")
    elif schema_editor.connection.vendor == "sqlite":
        for trigger in (
            "ray_tprobe_insert_0027",
            "ray_tprobe_update_0027",
            "ray_tprobe_lease_0027",
        ):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    else:
        raise RuntimeError("Ray target probe challenges require SQLite or PostgreSQL")


def _guard_empty(apps, schema_editor):
    challenge = apps.get_model("django_ray", "RayTargetProbeChallenge")
    table = schema_editor.quote_name(challenge._meta.db_table)
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(f"LOCK TABLE {table} IN ACCESS EXCLUSIVE MODE")
    elif schema_editor.connection.vendor == "sqlite":
        schema_editor.execute(f"UPDATE {table} SET revision = revision WHERE 0")
    else:
        raise RuntimeError("Ray target probe challenges require SQLite or PostgreSQL")
    if challenge.objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError("Cannot reverse while Ray target probe challenges remain")


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0026_ray_task_target_execution_evidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="RayTargetProbeChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("lease_hostname", models.CharField(editable=False, max_length=255)),
                ("lease_pid", models.PositiveIntegerField(editable=False)),
                ("lease_started_at", models.DateTimeField(editable=False)),
                (
                    "runner_family",
                    models.CharField(
                        choices=[("ray_core", "ray_core"), ("ray_job", "ray_job")],
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "configuration_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "nonce_digest",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a lowercase hexadecimal SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(db_default=1, default=1, editable=False),
                ),
                ("revision", models.PositiveBigIntegerField(editable=False)),
                ("issued_at", models.DateTimeField(editable=False)),
                ("expires_at", models.DateTimeField(editable=False)),
                ("consumed_at", models.DateTimeField(editable=False, null=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ray_target_probe_challenges",
                        to="django_ray.taskworkerlease",
                    ),
                ),
                (
                    "expected_target_policy",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="probe_challenges",
                        to="django_ray.raytargetpolicyrevision",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lease", "configuration_digest"),
                        name="ray_tprobe_lease_config_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_version", 1)), name="ray_tprobe_schema_valid"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("runner_family__in", ("ray_core", "ray_job"))),
                        name="ray_tprobe_family_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("revision__gte", 1), ("revision__lte", 9223372036854775807)
                        ),
                        name="ray_tprobe_revision_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("lease_pid__gte", 1), ("lease_pid__lte", 2147483647)),
                        name="ray_tprobe_pid_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expires_at__gt", models.F("issued_at")),
                            (
                                "expires_at__lte",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("issued_at"),
                                    "+",
                                    models.Value(datetime.timedelta(seconds=600)),
                                ),
                            ),
                            ("issued_at__gte", models.F("lease_started_at")),
                        ),
                        name="ray_tprobe_time_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("consumed_at__isnull", True),
                            models.Q(
                                ("consumed_at__gte", models.F("issued_at")),
                                ("consumed_at__lt", models.F("expires_at")),
                            ),
                            _connector="OR",
                        ),
                        name="ray_tprobe_consumed_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(_install, _uninstall),
        migrations.RunPython(migrations.RunPython.noop, _guard_empty),
    ]
