# Generated by Django 6.1.1 on 2026-09-12 02:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

_PRISTINE_NULL_FIELDS = (
    "claimed_by_worker",
    "started_at",
    "finished_at",
    "last_heartbeat_at",
    "ray_job_id",
    "ray_address",
    "ray_job_request_reference",
    "completion_data",
    "executor_django_ray_version",
    "result_data",
    "result_reference",
    "cancellation_status",
)


def _pristine_execution():
    return " AND ".join(
        ["state = 'QUEUED'", "execution_generation = 0", "attempt_number = 1"]
        + [f"{field} IS NULL" for field in _PRISTINE_NULL_FIELDS]
    )


def _tables(apps, schema_editor):
    return tuple(
        schema_editor.quote_name(apps.get_model("django_ray", name)._meta.db_table)
        for name in ("RayTaskCohortIntent", "RayTaskExecution")
    )


def _postgresql(apps, schema_editor):
    intent, execution = _tables(apps, schema_editor)
    statements = (
        f"""
        CREATE FUNCTION django_ray_guard_cintent_0028() RETURNS trigger
        LANGUAGE plpgsql AS $django_ray$
        BEGIN
            IF TG_OP = 'UPDATE' THEN
                RAISE EXCEPTION 'django-ray cohort intent is immutable' USING ERRCODE = '23514';
            END IF;
            IF NEW.execution_id < 1 OR NEW.schema_version <> 2
                OR NEW.selection_policy NOT IN ('worker_selected', 'jobs_only')
                OR char_length(NEW.package_version) NOT BETWEEN 1 AND 128
                OR substring(NEW.package_version FROM 1 FOR 1) !~ '[0-9]'
                OR NEW.package_version COLLATE "C" ~ '[^a-z0-9.!+]'
                OR char_length(NEW.backend_alias) NOT BETWEEN 1 AND 128
                OR NEW.backend_alias COLLATE "C" ~ '[^!-~]'
                OR char_length(NEW.configuration_digest) <> 71
                OR substring(NEW.configuration_digest FROM 1 FOR 7) <> 'sha256:'
                OR substring(NEW.configuration_digest FROM 8) ~ '[^0-9a-f]'
                OR char_length(NEW.runtime_env_identity_digest) <> 71
                OR substring(NEW.runtime_env_identity_digest FROM 1 FOR 7) <> 'sha256:'
                OR substring(NEW.runtime_env_identity_digest FROM 8) ~ '[^0-9a-f]'
                OR NOT isfinite(NEW.created_at) THEN
                RAISE EXCEPTION 'django-ray cohort intent is invalid' USING ERRCODE = '23514';
            END IF;
            PERFORM 1 FROM {execution} WHERE id = NEW.execution_id FOR UPDATE;
            IF NOT EXISTS (SELECT 1 FROM {execution}
                WHERE id = NEW.execution_id AND execution_protocol_version = 3
                    AND {_pristine_execution()}
                    AND created_at <= NEW.created_at) THEN
                RAISE EXCEPTION 'django-ray cohort intent execution is invalid'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""
        CREATE TRIGGER ray_cintent_guard_0028 BEFORE INSERT OR UPDATE ON {intent}
        FOR EACH ROW EXECUTE FUNCTION django_ray_guard_cintent_0028()
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _sqlite(apps, schema_editor):
    intent, execution = _tables(apps, schema_editor)
    timestamp = "substr(NEW.created_at, 1, 19)"
    statements = (
        f"""
        CREATE TRIGGER ray_cintent_insert_0028 BEFORE INSERT ON {intent}
        FOR EACH ROW WHEN typeof(NEW.execution_id) != 'integer' OR NEW.execution_id < 1
            OR typeof(NEW.schema_version) != 'integer' OR NEW.schema_version != 2
            OR NEW.selection_policy NOT IN ('worker_selected', 'jobs_only')
            OR typeof(NEW.package_version) != 'text'
            OR length(NEW.package_version) NOT BETWEEN 1 AND 128
            OR instr(NEW.package_version, char(0)) != 0
            OR substr(NEW.package_version, 1, 1) NOT GLOB '[0-9]'
            OR NEW.package_version GLOB '*[^a-z0-9.!+]*'
            OR typeof(NEW.backend_alias) != 'text'
            OR length(NEW.backend_alias) NOT BETWEEN 1 AND 128
            OR instr(NEW.backend_alias, char(0)) != 0
            OR NEW.backend_alias GLOB '*[^!-~]*'
            OR typeof(NEW.configuration_digest) != 'text'
            OR instr(NEW.configuration_digest, char(0)) != 0
            OR length(NEW.configuration_digest) != 71
            OR substr(NEW.configuration_digest, 1, 7) != 'sha256:'
            OR substr(NEW.configuration_digest, 8) GLOB '*[^0-9a-f]*'
            OR typeof(NEW.runtime_env_identity_digest) != 'text'
            OR instr(NEW.runtime_env_identity_digest, char(0)) != 0
            OR length(NEW.runtime_env_identity_digest) != 71
            OR substr(NEW.runtime_env_identity_digest, 1, 7) != 'sha256:'
            OR substr(NEW.runtime_env_identity_digest, 8) GLOB '*[^0-9a-f]*'
            OR typeof(NEW.created_at) != 'text' OR instr(NEW.created_at, char(0)) != 0
            OR length(NEW.created_at) NOT IN (19, 26)
            OR substr(NEW.created_at, 1, 4) = '0000'
            OR {timestamp} NOT GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]'
            OR datetime({timestamp}) IS NULL
            OR strftime('%Y-%m-%d %H:%M:%S', {timestamp}) != {timestamp}
            OR CAST(substr(NEW.created_at, 12, 2) AS INTEGER) NOT BETWEEN 0 AND 23
            OR (length(NEW.created_at) = 26 AND (
                substr(NEW.created_at, 20, 1) != '.'
                OR substr(NEW.created_at, 21, 6) GLOB '*[^0-9]*'))
            OR NOT EXISTS (SELECT 1 FROM {execution}
                WHERE id = NEW.execution_id AND execution_protocol_version = 3
                    AND typeof(execution_protocol_version) = 'integer'
                    AND {_pristine_execution()}
                    AND created_at <= NEW.created_at)
        BEGIN SELECT RAISE(ABORT, 'django-ray cohort intent is invalid'); END
        """,
        f"""
        CREATE TRIGGER ray_cintent_update_0028 BEFORE UPDATE ON {intent}
        FOR EACH ROW
        BEGIN SELECT RAISE(ABORT, 'django-ray cohort intent is immutable'); END
        """,
    )
    for statement in statements:
        schema_editor.execute(statement)


def _install(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        _postgresql(apps, schema_editor)
    elif schema_editor.connection.vendor == "sqlite":
        _sqlite(apps, schema_editor)
    else:
        raise RuntimeError("Cohort intent requires SQLite or PostgreSQL")


def _uninstall(apps, schema_editor):
    intent, _execution = _tables(apps, schema_editor)
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(f"DROP TRIGGER IF EXISTS ray_cintent_guard_0028 ON {intent}")
        schema_editor.execute("DROP FUNCTION IF EXISTS django_ray_guard_cintent_0028()")
    elif schema_editor.connection.vendor == "sqlite":
        schema_editor.execute("DROP TRIGGER IF EXISTS ray_cintent_insert_0028")
        schema_editor.execute("DROP TRIGGER IF EXISTS ray_cintent_update_0028")
    else:
        raise RuntimeError("Cohort intent requires SQLite or PostgreSQL")


def _guard_empty(apps, schema_editor):
    model = apps.get_model("django_ray", "RayTaskCohortIntent")
    table = schema_editor.quote_name(model._meta.db_table)
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(f"LOCK TABLE {table} IN ACCESS EXCLUSIVE MODE")
    elif schema_editor.connection.vendor == "sqlite":
        schema_editor.execute(f"UPDATE {table} SET execution_id = execution_id WHERE 0")
    else:
        raise RuntimeError("Cohort intent requires SQLite or PostgreSQL")
    if model.objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError("Cannot reverse while cohort intent remains")


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0027_ray_target_probe_challenges"),
    ]

    operations = [
        migrations.CreateModel(
            name="RayTaskCohortIntent",
            fields=[
                (
                    "execution",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="cohort_intent",
                        serialize=False,
                        to="django_ray.raytaskexecution",
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(db_default=2, default=2, editable=False),
                ),
                ("package_version", models.CharField(editable=False, max_length=128)),
                ("backend_alias", models.CharField(editable=False, max_length=128)),
                (
                    "configuration_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "runtime_env_identity_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "selection_policy",
                    models.CharField(
                        choices=[
                            ("worker_selected", "worker_selected"),
                            ("jobs_only", "jobs_only"),
                        ],
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "configuration_digest",
                            "package_version",
                            "backend_alias",
                            "selection_policy",
                        ],
                        name="ray_cintent_claim_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("schema_version", 2)), name="ray_cintent_schema_valid"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("selection_policy__in", ("worker_selected", "jobs_only"))
                        ),
                        name="ray_cintent_selection_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(_install, _uninstall),
        migrations.RunPython(migrations.RunPython.noop, _guard_empty),
    ]
