# Generated by Django 6.1.1 on 2026-09-12 02:50
# Unreleased draft format: request schema two replaces draft schema one.
# Existing draft databases require a fresh database or a reviewed reversal
# while the receipt table is empty. Retained evidence is never coerced/deleted.

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

_RESERVATION_FIELDS = (
    "challenge_id",
    "challenge_revision",
    "request_json",
    "request_digest",
    "ray_address",
    "submission_id",
    "entrypoint_digest",
    "submitted_runtime_env_digest",
    "reserved_at",
)
_REQUEST_KEYS = (
    "schema",
    "schema_version",
    "challenge_id",
    "challenge_revision",
    "lease",
    "configuration_digest",
    "target_key",
    "runner_family",
    "expected_package_version",
    "expected_runtime",
    "expected_cluster_session",
    "expected_target_policy_id",
    "policy_revision",
    "issued_at",
    "expires_at",
)


def _tables(apps, schema_editor):
    return tuple(
        schema_editor.quote_name(apps.get_model("django_ray", name)._meta.db_table)
        for name in ("RayTargetProbeJobReceipt", "RayTargetProbeChallenge", "TaskWorkerLease")
    )


def _related_valid(challenge, lease, *, postgres):
    def item(*path):
        if postgres:
            return "NEW.request_json::jsonb #>> '{" + ",".join(path) + "}'"
        return "json_extract(NEW.request_json, '$." + ".".join(path) + "')"

    def same_time(path, column):
        if postgres:
            return f"({item(*path)}) = to_char({column} AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"')"
        return (
            f"replace(replace({item(*path)}, 'T', ' '), 'Z', '') = "
            f"CASE WHEN length({column}) = 19 THEN {column} || '.000000' ELSE {column} END"
        )

    def kind(name):
        if postgres:
            return f"jsonb_typeof(NEW.request_json::jsonb -> '{name}')"
        return f"json_type(NEW.request_json, '$.{name}')"

    cast = "::text" if postgres else ""
    return f"""
        EXISTS (SELECT 1 FROM {challenge} AS probe JOIN {lease} AS lease
            ON lease.worker_id = probe.lease_id
            WHERE probe.id = NEW.challenge_id AND probe.revision = NEW.challenge_revision
                AND probe.runner_family = 'ray_job' AND probe.consumed_at IS NULL
                AND lease.hostname = probe.lease_hostname AND lease.pid = probe.lease_pid
                AND lease.started_at = probe.lease_started_at
                AND lease.is_active AND lease.stopped_at IS NULL
                AND lease.capability_schema_version = 1
                AND lease.legacy_admission_token_id IS NULL
                AND lease.last_heartbeat_at <= COALESCE(NEW.received_at, NEW.reserved_at)
                AND probe.issued_at <= NEW.reserved_at
                AND COALESCE(NEW.received_at, NEW.reserved_at) < probe.expires_at
                AND {item("schema")} = 'django-ray.cohort-probe-job'
                AND {item("schema_version")} = {"'2'" if postgres else "2"}
                AND {item("runner_family")} = 'ray_job'
                AND {item("challenge_id")} = probe.id{cast}
                AND {item("challenge_revision")} = probe.revision{cast}
                AND {item("configuration_digest")} = probe.configuration_digest
                AND {item("lease", "worker_id")} = probe.lease_id
                AND {item("lease", "hostname")} = probe.lease_hostname
                AND {item("lease", "pid")} = probe.lease_pid{cast}
                AND {same_time(("lease", "started_at"), "probe.lease_started_at")}
                AND {same_time(("issued_at",), "probe.issued_at")}
                AND {same_time(("expires_at",), "probe.expires_at")}
                AND ({item("expected_target_policy_id")}) IS {"NOT DISTINCT FROM" if postgres else ""}
                    probe.expected_target_policy_id{cast}
                AND (
                    (probe.expected_target_policy_id IS NULL
                        AND {kind("target_key")} = 'null'
                        AND {kind("expected_cluster_session")} = 'null'
                        AND {item("policy_revision")} = {"'1'" if postgres else "1"})
                    OR (probe.expected_target_policy_id IS NOT NULL
                        AND {kind("target_key")} = '{"string" if postgres else "text"}'
                        AND length({item("target_key")}) BETWEEN 1 AND 128
                        AND {kind("expected_cluster_session")} = '{"string" if postgres else "text"}'
                        AND length({item("expected_cluster_session")}) BETWEEN 1 AND 256)
                )
        )
    """


def _sqlite_time_invalid(column):
    value = f"NEW.{column}"
    base = f"substr({value}, 1, 19)"
    return f"""typeof({value}) != 'text' OR instr({value}, char(0)) != 0
        OR length({value}) NOT IN (19, 26) OR substr({value}, 1, 4) = '0000'
        OR {base} NOT GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]'
        OR datetime({base}) IS NULL OR strftime('%Y-%m-%d %H:%M:%S', {base}) != {base}
        OR CAST(substr({value}, 12, 2) AS INTEGER) NOT BETWEEN 0 AND 23
        OR (length({value}) = 26 AND (substr({value}, 20, 1) != '.'
            OR substr({value}, 21, 6) GLOB '*[^0-9]*'))"""


def _sqlite_digest_invalid(column):
    return f"""typeof(NEW.{column}) != 'text' OR length(NEW.{column}) != 71
        OR instr(NEW.{column}, char(0)) != 0 OR substr(NEW.{column}, 1, 7) != 'sha256:'
        OR substr(NEW.{column}, 8) GLOB '*[^0-9a-f]*'"""


def _postgresql(apps, schema_editor):
    receipt, challenge, lease = _tables(apps, schema_editor)
    changed = " OR ".join(f"NEW.{name} IS DISTINCT FROM OLD.{name}" for name in _RESERVATION_FIELDS)
    keys = ", ".join(f"'{key}'" for key in _REQUEST_KEYS)
    statements = (
        f"""
        CREATE FUNCTION django_ray_guard_probe_job_0029() RETURNS trigger
        LANGUAGE plpgsql AS $django_ray$
        BEGIN
            IF NEW.challenge_id < 1 OR NEW.challenge_revision NOT BETWEEN 1 AND 9223372036854775807
                OR octet_length(NEW.request_json) NOT BETWEEN 1 AND 8192
                OR NEW.request_json COLLATE "C" ~ '[^ -~]'
                OR NEW.request_digest !~ '^sha256:[0-9a-f]{{64}}$'
                OR NEW.entrypoint_digest !~ '^sha256:[0-9a-f]{{64}}$'
                OR NEW.submitted_runtime_env_digest !~ '^sha256:[0-9a-f]{{64}}$'
                OR char_length(NEW.ray_address) NOT BETWEEN 8 AND 2048
                OR NEW.ray_address !~ '^https?://[^/]'
                OR NEW.ray_address COLLATE "C" ~ '[^!-~]'
                OR NEW.ray_address ~ '[@?#%]' OR position(chr(92) in NEW.ray_address) > 0
                OR NEW.submission_id <> 'django-ray-cohort-probe-' || substring(NEW.request_digest FROM 8)
                OR NOT isfinite(NEW.reserved_at)
                OR (NEW.receipt_json IS NOT NULL AND (
                    octet_length(NEW.receipt_json) NOT BETWEEN 1 AND 1064960
                    OR NEW.receipt_json COLLATE "C" ~ '[^ -~]'
                    OR jsonb_typeof(NEW.receipt_json::jsonb) <> 'object'
                    OR NEW.receipt_digest !~ '^sha256:[0-9a-f]{{64}}$'
                    OR NOT isfinite(NEW.received_at)))
                OR jsonb_typeof(NEW.request_json::jsonb) <> 'object'
                OR (SELECT COUNT(*) FROM jsonb_object_keys(NEW.request_json::jsonb)) <> 15
                OR EXISTS (SELECT 1 FROM jsonb_object_keys(NEW.request_json::jsonb) AS key
                    WHERE key NOT IN ({keys}))
                OR jsonb_typeof(NEW.request_json::jsonb -> 'lease') <> 'object'
                OR (SELECT COUNT(*) FROM jsonb_object_keys(NEW.request_json::jsonb -> 'lease')) <> 4
                OR EXISTS (SELECT 1 FROM jsonb_object_keys(NEW.request_json::jsonb -> 'lease') AS key
                    WHERE key NOT IN ('worker_id', 'hostname', 'pid', 'started_at'))
                OR jsonb_typeof(NEW.request_json::jsonb -> 'expected_runtime') <> 'object'
                OR (SELECT COUNT(*) FROM jsonb_object_keys(NEW.request_json::jsonb -> 'expected_runtime')) <> 7
                OR EXISTS (SELECT 1 FROM jsonb_object_keys(NEW.request_json::jsonb -> 'expected_runtime') AS key
                    WHERE key NOT IN ('ray_major', 'ray_minor', 'ray_patch', 'python_implementation',
                        'python_major', 'python_minor', 'python_patch')) THEN
                RAISE EXCEPTION 'django-ray Jobs probe reservation is invalid' USING ERRCODE = '23514';
            END IF;
            IF (TG_OP = 'INSERT' AND (NEW.receipt_json IS NOT NULL
                    OR NEW.receipt_digest IS NOT NULL OR NEW.received_at IS NOT NULL))
                OR (TG_OP = 'UPDATE' AND (({changed}) OR OLD.receipt_json IS NOT NULL
                    OR NEW.receipt_json IS NULL OR NEW.receipt_digest IS NULL OR NEW.received_at IS NULL)) THEN
                RAISE EXCEPTION 'django-ray Jobs probe reservation is immutable' USING ERRCODE = '23514';
            END IF;
            PERFORM 1 FROM {lease} WHERE worker_id = (SELECT lease_id FROM {challenge}
                WHERE id = NEW.challenge_id) FOR UPDATE;
            PERFORM 1 FROM {challenge} WHERE id = NEW.challenge_id FOR UPDATE;
            IF NOT ({_related_valid(challenge, lease, postgres=True)}) THEN
                RAISE EXCEPTION 'django-ray Jobs probe challenge is stale' USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""CREATE TRIGGER ray_probe_job_guard_0029 BEFORE INSERT OR UPDATE ON {receipt}
            FOR EACH ROW EXECUTE FUNCTION django_ray_guard_probe_job_0029()""",
        f"""
        CREATE FUNCTION django_ray_clear_probe_job_0029() RETURNS trigger
        LANGUAGE plpgsql AS $django_ray$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                DELETE FROM {receipt} WHERE challenge_id = OLD.id;
                RETURN OLD;
            END IF;
            IF NEW.nonce_digest IS DISTINCT FROM OLD.nonce_digest THEN
                IF EXISTS (SELECT 1 FROM {receipt} WHERE challenge_id = OLD.id
                    AND NEW.issued_at < COALESCE(received_at, reserved_at)) THEN
                    RAISE EXCEPTION 'django-ray Jobs probe replacement clock regressed'
                        USING ERRCODE = '23514';
                END IF;
                DELETE FROM {receipt} WHERE challenge_id = OLD.id;
            END IF;
            RETURN NEW;
        END;
        $django_ray$
        """,
        f"""CREATE TRIGGER ray_probe_job_clear_0029 BEFORE DELETE OR UPDATE ON {challenge}
            FOR EACH ROW EXECUTE FUNCTION django_ray_clear_probe_job_0029()""",
        f"""
        CREATE FUNCTION django_ray_clear_probe_lease_0029() RETURNS trigger
        LANGUAGE plpgsql AS $django_ray$
        BEGIN
            DELETE FROM {challenge} WHERE lease_id = OLD.worker_id;
            RETURN OLD;
        END;
        $django_ray$
        """,
        f"""CREATE TRIGGER ray_probe_lease_delete_0029 BEFORE DELETE ON {lease}
            FOR EACH ROW EXECUTE FUNCTION django_ray_clear_probe_lease_0029()""",
    )
    for statement in statements:
        schema_editor.execute(statement, params=None)


def _sqlite(apps, schema_editor):
    receipt, challenge, lease = _tables(apps, schema_editor)
    changed = " OR ".join(f"NEW.{name} IS NOT OLD.{name}" for name in _RESERVATION_FIELDS)
    digests = " OR ".join(
        _sqlite_digest_invalid(name)
        for name in ("request_digest", "entrypoint_digest", "submitted_runtime_env_digest")
    )
    keys = ", ".join(f"'{key}'" for key in _REQUEST_KEYS)
    invalid = f"""
        typeof(NEW.challenge_id) != 'integer' OR NEW.challenge_id < 1
        OR typeof(NEW.challenge_revision) != 'integer'
        OR NEW.challenge_revision NOT BETWEEN 1 AND 9223372036854775807
        OR typeof(NEW.request_json) != 'text' OR length(CAST(NEW.request_json AS BLOB)) NOT BETWEEN 1 AND 8192
        OR instr(NEW.request_json, char(0)) != 0 OR NEW.request_json GLOB '*[^ -~]*'
        OR NOT json_valid(NEW.request_json) OR json_type(NEW.request_json) != 'object'
        OR (SELECT COUNT(*) FROM json_each(NEW.request_json)) != 15
        OR EXISTS (SELECT 1 FROM json_each(NEW.request_json) WHERE key NOT IN ({keys}))
        OR json_type(NEW.request_json, '$.lease') != 'object'
        OR (SELECT COUNT(*) FROM json_each(NEW.request_json, '$.lease')) != 4
        OR EXISTS (SELECT 1 FROM json_each(NEW.request_json, '$.lease')
            WHERE key NOT IN ('worker_id', 'hostname', 'pid', 'started_at'))
        OR json_type(NEW.request_json, '$.expected_runtime') != 'object'
        OR (SELECT COUNT(*) FROM json_each(NEW.request_json, '$.expected_runtime')) != 7
        OR EXISTS (SELECT 1 FROM json_each(NEW.request_json, '$.expected_runtime')
            WHERE key NOT IN ('ray_major', 'ray_minor', 'ray_patch', 'python_implementation',
                'python_major', 'python_minor', 'python_patch'))
        OR json_type(NEW.request_json, '$.schema_version') != 'integer'
        OR json_type(NEW.request_json, '$.challenge_id') != 'integer'
        OR json_type(NEW.request_json, '$.challenge_revision') != 'integer'
        OR json_type(NEW.request_json, '$.lease.pid') != 'integer'
        OR ({digests})
        OR typeof(NEW.ray_address) != 'text' OR length(NEW.ray_address) NOT BETWEEN 8 AND 2048
        OR instr(NEW.ray_address, char(0)) != 0 OR NEW.ray_address GLOB '*[^!-~]*'
        OR NOT (NEW.ray_address GLOB 'http://[^/]*' OR NEW.ray_address GLOB 'https://[^/]*')
        OR NEW.ray_address GLOB '*[@?#%]*' OR instr(NEW.ray_address, char(92)) != 0
        OR typeof(NEW.submission_id) != 'text'
        OR NEW.submission_id != 'django-ray-cohort-probe-' || substr(NEW.request_digest, 8)
        OR ({_sqlite_time_invalid("reserved_at")})
        OR (NEW.receipt_json IS NOT NULL AND (
            typeof(NEW.receipt_json) != 'text' OR length(CAST(NEW.receipt_json AS BLOB)) NOT BETWEEN 1 AND 1064960
            OR instr(NEW.receipt_json, char(0)) != 0 OR NEW.receipt_json GLOB '*[^ -~]*'
            OR NOT json_valid(NEW.receipt_json) OR json_type(NEW.receipt_json) != 'object'
            OR ({_sqlite_digest_invalid("receipt_digest")}) OR ({_sqlite_time_invalid("received_at")})
        ))
        OR NOT ({_related_valid(challenge, lease, postgres=False)})
    """
    statements = (
        f"""CREATE TRIGGER ray_probe_job_insert_0029 BEFORE INSERT ON {receipt}
            FOR EACH ROW WHEN ({invalid}) OR NEW.receipt_json IS NOT NULL
                OR NEW.receipt_digest IS NOT NULL OR NEW.received_at IS NOT NULL
            BEGIN SELECT RAISE(ABORT, 'django-ray Jobs probe reservation is invalid'); END""",
        f"""CREATE TRIGGER ray_probe_job_update_0029 BEFORE UPDATE ON {receipt}
            FOR EACH ROW WHEN ({invalid}) OR ({changed}) OR OLD.receipt_json IS NOT NULL
                OR NEW.receipt_json IS NULL OR NEW.receipt_digest IS NULL OR NEW.received_at IS NULL
            BEGIN SELECT RAISE(ABORT, 'django-ray Jobs probe reservation is immutable'); END""",
        f"""CREATE TRIGGER ray_probe_job_delete_0029 BEFORE DELETE ON {challenge}
            FOR EACH ROW BEGIN DELETE FROM {receipt} WHERE challenge_id = OLD.id; END""",
        f"""CREATE TRIGGER ray_probe_job_replace_0029 BEFORE UPDATE ON {challenge}
            FOR EACH ROW WHEN NEW.nonce_digest IS NOT OLD.nonce_digest
            BEGIN
                SELECT CASE WHEN EXISTS (SELECT 1 FROM {receipt} WHERE challenge_id = OLD.id
                    AND NEW.issued_at < COALESCE(received_at, reserved_at))
                    THEN RAISE(ABORT, 'django-ray Jobs probe replacement clock regressed') END;
                DELETE FROM {receipt} WHERE challenge_id = OLD.id;
            END""",
        f"""CREATE TRIGGER ray_probe_lease_delete_0029 BEFORE DELETE ON {lease}
            FOR EACH ROW BEGIN DELETE FROM {challenge} WHERE lease_id = OLD.worker_id; END""",
    )
    for statement in statements:
        schema_editor.execute(statement)


def _install(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        _postgresql(apps, schema_editor)
    elif schema_editor.connection.vendor == "sqlite":
        _sqlite(apps, schema_editor)
    else:
        raise RuntimeError("Jobs probe receipts require SQLite or PostgreSQL")


def _uninstall(apps, schema_editor):
    receipt, challenge, lease = _tables(apps, schema_editor)
    if schema_editor.connection.vendor == "postgresql":
        for trigger, table in (
            ("ray_probe_job_guard_0029", receipt),
            ("ray_probe_job_clear_0029", challenge),
            ("ray_probe_lease_delete_0029", lease),
        ):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger} ON {table}")
        for name in (
            "django_ray_guard_probe_job_0029",
            "django_ray_clear_probe_job_0029",
            "django_ray_clear_probe_lease_0029",
        ):
            schema_editor.execute(f"DROP FUNCTION IF EXISTS {name}()")
    elif schema_editor.connection.vendor == "sqlite":
        for name in (
            "ray_probe_job_insert_0029",
            "ray_probe_job_update_0029",
            "ray_probe_job_delete_0029",
            "ray_probe_job_replace_0029",
            "ray_probe_lease_delete_0029",
        ):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {name}")
    else:
        raise RuntimeError("Jobs probe receipts require SQLite or PostgreSQL")


def _guard_empty(apps, schema_editor):
    model = apps.get_model("django_ray", "RayTargetProbeJobReceipt")
    table = schema_editor.quote_name(model._meta.db_table)
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(f"LOCK TABLE {table} IN ACCESS EXCLUSIVE MODE")
    elif schema_editor.connection.vendor == "sqlite":
        schema_editor.execute(f"UPDATE {table} SET challenge_id = challenge_id WHERE 0")
    else:
        raise RuntimeError("Jobs probe receipts require SQLite or PostgreSQL")
    if model.objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError("Cannot reverse while Jobs probe receipts remain")


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0028_ray_task_cohort_intent"),
    ]

    operations = [
        migrations.CreateModel(
            name="RayTargetProbeJobReceipt",
            fields=[
                (
                    "challenge",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="job_receipt",
                        serialize=False,
                        to="django_ray.raytargetprobechallenge",
                    ),
                ),
                ("challenge_revision", models.PositiveBigIntegerField(editable=False)),
                (
                    "request_json",
                    models.TextField(
                        editable=False, validators=[django.core.validators.MaxLengthValidator(8192)]
                    ),
                ),
                (
                    "request_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("ray_address", models.CharField(editable=False, max_length=2048)),
                ("submission_id", models.CharField(editable=False, max_length=88)),
                (
                    "entrypoint_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                (
                    "submitted_runtime_env_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("reserved_at", models.DateTimeField(editable=False)),
                (
                    "receipt_json",
                    models.TextField(
                        editable=False,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(1064960)],
                    ),
                ),
                (
                    "receipt_digest",
                    models.CharField(
                        editable=False,
                        max_length=71,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must be a canonical tagged lowercase SHA-256 digest.",
                                regex="\\Asha256:[0-9a-f]{64}\\Z",
                            )
                        ],
                    ),
                ),
                ("received_at", models.DateTimeField(editable=False, null=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("challenge_revision__gte", 1),
                            ("challenge_revision__lte", 9223372036854775807),
                        ),
                        name="ray_tprobe_job_revision_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("receipt_digest__isnull", True),
                                ("receipt_json__isnull", True),
                                ("received_at__isnull", True),
                            ),
                            models.Q(
                                ("receipt_digest__isnull", False),
                                ("receipt_json__isnull", False),
                                ("received_at__gte", models.F("reserved_at")),
                                ("received_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ray_tprobe_job_receipt_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(_install, _uninstall),
        migrations.RunPython(migrations.RunPython.noop, _guard_empty),
    ]
