# Generated by Django 6.1.1 on 2026-09-12 04:22

import importlib
import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

_MAX = 9223372036854775807
_JOB_QUALIFICATION_INTEGERS = ("challenge_id", "request_revision", "consumed_challenge_revision")
_JOB_QUALIFICATION_STRINGS = (
    "configuration_digest",
    "jobs_endpoint",
    "challenge_issued_at",
    "challenge_expires_at",
    "consumed_at",
    "request_digest",
    "receipt_digest",
    "submission_id",
    "native_job_id",
    "entrypoint_digest",
    "submitted_control_runtime_env_digest",
    "endpoint_expectation_digest",
    "endpoint_attestation_digest",
    "endpoint_membership_digest",
    "endpoint_observed_at",
    "endpoint_expires_at",
    "receipt_received_at",
)
_FACTS = (
    "binding_id",
    "attempt_number",
    "execution_generation",
    "facts_json",
    "facts_digest",
    "target_policy_id",
    "claim_attestation_id",
    "claimed_at",
)
_OWNER = ("owner_lease_id", "owner_lease_hostname", "owner_lease_pid", "owner_lease_started_at")
_HOLD = (
    "hold_reason",
    "hold_boundary",
    "hold_application_invoked",
    "hold_evidence_digest",
    "held_at",
)
_RESOLUTION = ("resolution_kind", "resolution_digest", "resolved_at")
_TIMES = (
    "claimed_at",
    "owner_lease_started_at",
    "prepared_at",
    "dispatched_at",
    "held_at",
    "resolved_at",
)
_REASONS = (
    "package_mismatch",
    "runtime_mismatch",
    "session_mismatch",
    "membership_mismatch",
    "invalid_completion",
    "transport_uncertain",
    "owner_lost",
    "dispatch_uncertain",
    "cancellation_uncertain",
)
_KINDS = ("application_completed", "verified_not_invoked", "verified_cancelled")


def _tables(apps, editor):
    return {
        name: editor.quote_name(apps.get_model("django_ray", name)._meta.db_table)
        for name in (
            "RayTaskTargetBinding",
            "RayTaskCohortClaim",
            "RayTaskExecution",
            "RayTaskCohortIntent",
            "TaskWorkerLease",
            "RayTarget",
            "RayTargetPolicyRevision",
            "RayTargetAttestationRevision",
            "RayWorkerTargetCapability",
            "RayTargetProbeChallenge",
            "RayTargetProbeJobReceipt",
        )
    }


def _old_binding_fence(apps, editor, *, install):
    module = importlib.import_module("django_ray.migrations.0023_ray_task_target_binding")
    function = (
        module._install_task_target_binding_fences
        if install
        else module._remove_task_target_binding_fences
    )
    function(apps, editor)


def _remove_old(apps, editor):
    _old_binding_fence(apps, editor, install=False)
    _external_fences(apps, editor, install=False)


def _restore_old(apps, editor):
    _old_binding_fence(apps, editor, install=True)
    _external_fences(apps, editor, install=True)


def _external_fences(apps, editor, *, install):
    # SQLite validates other tables' triggers while rebuilding this binding
    # table. Suspend only those existing fences, then restore them unchanged.
    if editor.connection.vendor != "sqlite":
        return
    for module_name, suffix in (
        ("0024_ray_target_routes", "target_routing_fences"),
        ("0026_ray_task_target_execution_evidence", "evidence_fences"),
    ):
        module = importlib.import_module("django_ray.migrations." + module_name)
        getattr(module, ("_install_" if install else "_remove_") + suffix)(apps, editor)


def _quoted(values):
    return ", ".join("'" + value + "'" for value in values)


def _install(apps, editor):
    vendor = editor.connection.vendor
    if vendor not in {"sqlite", "postgresql"}:
        raise RuntimeError("Cohort claim ledger requires SQLite or PostgreSQL")
    pg = vendor == "postgresql"
    tables = _tables(apps, editor)
    binding = tables["RayTaskTargetBinding"]
    claim = tables["RayTaskCohortClaim"]
    execution = tables["RayTaskExecution"]
    intent = tables["RayTaskCohortIntent"]
    lease = tables["TaskWorkerLease"]
    target = tables["RayTarget"]
    policy = tables["RayTargetPolicyRevision"]
    attestation = tables["RayTargetAttestationRevision"]
    capability = tables["RayWorkerTargetCapability"]
    challenge = tables["RayTargetProbeChallenge"]
    job_receipt = tables["RayTargetProbeJobReceipt"]
    unequal = "IS DISTINCT FROM" if pg else "IS NOT"

    def bytes_length(column):
        return f"octet_length({column})" if pg else f"length(CAST({column} AS BLOB))"

    def j(path, *, integer=False):
        return json_value("NEW.facts_json", path, integer=integer)

    def json_value(source, path, *, integer=False):
        sqlite_path = re.sub(r"\.(\d+)(?=\.|$)", r"[\1]", path)
        expression = (
            f"({source}::jsonb #>> '{{{path.replace('.', ',')}}}')"
            if pg
            else f"json_extract({source}, '$.{sqlite_path}')"
        )
        return f"CAST({expression} AS BIGINT)" if pg and integer else expression

    def wire_time(expression):
        return (
            f"CAST({expression} AS timestamptz)"
            if pg
            else f"replace(substr({expression},1,26),'T',' ')"
        )

    def database_time(column):
        return (
            column
            if pg
            else f"CASE WHEN length({column})=19 THEN {column} || '.000000' ELSE {column} END"
        )

    def q(name, *, integer=False):
        return j("job_qualification." + name, integer=integer)

    def receipt_value(path, *, integer=False):
        return json_value("r.receipt_json", path, integer=integer)

    def request_value(path, *, integer=False):
        return json_value("r.request_json", path, integer=integer)

    def changed(columns):
        return " OR ".join(f"NEW.{column} {unequal} OLD.{column}" for column in columns)

    def intent_value(name):
        source = j("intent_json")
        return f"({source})::jsonb ->> '{name}'" if pg else f"json_extract({source}, '$.{name}')"

    def digest_invalid(column):
        expression = (
            f"{column} !~ '^sha256:[0-9a-f]{{64}}$'"
            if pg
            else f"(length({column}) != 71 OR substr({column},1,7) != 'sha256:' OR substr({column},8) GLOB '*[^0-9a-f]*')"
        )
        return f"({column} IS NOT NULL AND {expression})"

    def time_invalid(column):
        if pg:
            return f"(NEW.{column} IS NOT NULL AND (NOT isfinite(NEW.{column}) OR EXTRACT(YEAR FROM NEW.{column} AT TIME ZONE 'UTC') NOT BETWEEN 1 AND 9999))"
        helper = importlib.import_module(
            "django_ray.migrations.0023_ray_task_target_binding"
        )._sqlite_datetime_invalid
        return f"(NEW.{column} IS NOT NULL AND ({helper(column)}))"

    def timestamp_matches(column, path):
        if pg:
            return f"{column} = CAST({j(path)} AS timestamptz)"
        # Pure transport timestamps use six fractional digits and UTC Z.
        return f"substr({column},1,19) = substr(replace({j(path)}, 'T', ' '),1,19) AND COALESCE(NULLIF(substr({column},21,6),''),'000000') = substr({j(path)},21,6)"

    def trigger(name, table, operation, condition, *, locks=""):
        if pg:
            editor.execute(f"""CREATE FUNCTION django_ray_{name}() RETURNS trigger LANGUAGE plpgsql AS $cohort$
            BEGIN {locks}
              IF {condition} THEN RAISE EXCEPTION 'django-ray cohort ledger fence refused' USING ERRCODE='23514'; END IF;
              RETURN {"OLD" if operation == "DELETE" else "NEW"};
            END; $cohort$""")
            editor.execute(
                f"CREATE TRIGGER {name} BEFORE {operation} ON {table} FOR EACH ROW EXECUTE FUNCTION django_ray_{name}()"
            )
        else:
            timing = "AFTER" if operation == "INSERT" and table == claim else "BEFORE"
            editor.execute(
                f"CREATE TRIGGER {name} {timing} {operation} ON {table} FOR EACH ROW WHEN {condition} BEGIN SELECT RAISE(ABORT, 'django-ray cohort ledger fence refused'); END"
            )

    # Schema 1 retains its old meaning. Schema 2 is first selected only for a
    # queued p3 execution with immutable producer intent; Sync has no Ray FK.
    binding_shape = f"""
      NEW.execution_id < 1 OR NEW.schema_version NOT IN (1,2) OR {time_invalid("created_at")}
      OR (NEW.schema_version=1 AND (NEW.target_policy_id IS NULL OR NEW.runner_family IS NOT NULL OR NEW.package_version IS NOT NULL
          OR NEW.sync_python_implementation IS NOT NULL OR NEW.sync_python_major IS NOT NULL OR NEW.sync_python_minor IS NOT NULL OR NEW.sync_python_patch IS NOT NULL))
      OR (NEW.schema_version=2 AND (
          NEW.runner_family IS NULL OR NEW.package_version IS NULL OR length(NEW.package_version) NOT BETWEEN 1 AND 128
          OR NEW.runner_family NOT IN ('sync','ray_core','ray_job')
          OR (NEW.runner_family='sync' AND (NEW.target_policy_id IS NOT NULL OR NEW.sync_python_implementation IS NULL
              OR length(NEW.sync_python_implementation) NOT BETWEEN 1 AND 64 OR NEW.sync_python_major IS NULL OR NEW.sync_python_major NOT BETWEEN 1 AND {_MAX}
              OR NEW.sync_python_minor IS NULL OR NEW.sync_python_minor NOT BETWEEN 0 AND {_MAX} OR NEW.sync_python_patch IS NULL OR NEW.sync_python_patch NOT BETWEEN 0 AND {_MAX}))
          OR (NEW.runner_family!='sync' AND (NEW.target_policy_id IS NULL OR NEW.sync_python_implementation IS NOT NULL
              OR NEW.sync_python_major IS NOT NULL OR NEW.sync_python_minor IS NOT NULL OR NEW.sync_python_patch IS NOT NULL))
      ))
    """
    binding_lineage = f"""NEW.schema_version=2 AND NOT EXISTS (
      SELECT 1 FROM {execution} e JOIN {intent} i ON i.execution_id=e.id
      WHERE e.id=NEW.execution_id AND e.execution_protocol_version=3 AND e.state='QUEUED'
        AND i.package_version=NEW.package_version AND i.created_at<=NEW.created_at
        AND (i.selection_policy='worker_selected' OR NEW.runner_family='ray_job')
        AND (NEW.runner_family='sync' OR EXISTS (
          SELECT 1 FROM {policy} p JOIN {target} t ON t.target_key=p.target_id
          WHERE p.id=NEW.target_policy_id AND t.runner_family=NEW.runner_family
        ))
    )"""
    if not pg:
        binding_shape += " OR " + " OR ".join(
            f"(NEW.{column} IS NOT NULL AND typeof(NEW.{column})!='integer')"
            for column in (
                "execution_id",
                "schema_version",
                "target_policy_id",
                "sync_python_major",
                "sync_python_minor",
                "sync_python_patch",
            )
        )
    trigger(
        "ray_cbinding_insert_0030", binding, "INSERT", f"({binding_shape}) OR ({binding_lineage})"
    )
    binding_columns = (
        "execution_id",
        "target_policy_id",
        "schema_version",
        "created_at",
        "runner_family",
        "package_version",
        "sync_python_implementation",
        "sync_python_major",
        "sync_python_minor",
        "sync_python_patch",
    )
    trigger("ray_cbinding_update_0030", binding, "UPDATE", changed(binding_columns))

    json_invalid = (
        "jsonb_typeof(NEW.facts_json::jsonb) != 'object'"
        if pg
        else "NOT json_valid(NEW.facts_json) OR json_type(NEW.facts_json) != 'object'"
    )
    shape = f"""
      NEW.id < 1 OR NEW.binding_id < 1 OR NEW.attempt_number NOT BETWEEN 1 AND 2147483647
      OR NEW.execution_generation NOT BETWEEN 1 AND {_MAX} OR NEW.revision NOT BETWEEN 1 AND {_MAX}
      OR {bytes_length("NEW.facts_json")} NOT BETWEEN 1 AND 16384 OR ({json_invalid})
      OR NEW.disposition NOT IN ('OPEN','HELD','RESOLVED')
      OR length(NEW.owner_lease_id) NOT BETWEEN 1 AND 255 OR length(NEW.owner_lease_hostname) NOT BETWEEN 1 AND 255
      OR NEW.owner_lease_pid NOT BETWEEN 1 AND 2147483647
      OR {j("schema")} {unequal} 'django-ray.cohort-claim-facts'
      OR {j("schema_version", integer=True)} {unequal} 2 OR {j("execution_protocol_version", integer=True)} {unequal} 3
      OR {j("binding_id", integer=True)} {unequal} NEW.binding_id
      OR {j("identity.task_execution_pk", integer=True)} {unequal} NEW.binding_id
      OR {j("identity.attempt_number", integer=True)} {unequal} NEW.attempt_number
      OR {j("identity.execution_generation", integer=True)} {unequal} NEW.execution_generation
      OR {j("target_policy_id", integer=True)} {unequal} NEW.target_policy_id
      OR {j("claim_attestation_id", integer=True)} {unequal} NEW.claim_attestation_id
      OR NOT ({timestamp_matches("NEW.claimed_at", "claimed_at")})
      OR ({" OR ".join(time_invalid(column) for column in _TIMES)})
      OR ({" OR ".join(digest_invalid("NEW." + column) for column in ("facts_digest", "prepared_request_digest", "hold_evidence_digest", "resolution_digest"))})
      OR ((NEW.prepared_request_digest IS NULL) != (NEW.prepared_at IS NULL))
      OR (NEW.prepared_at IS NOT NULL AND NEW.prepared_at < NEW.claimed_at)
      OR (NEW.dispatched_at IS NOT NULL AND (NEW.prepared_at IS NULL OR NEW.dispatched_at < NEW.prepared_at))
      OR (NEW.held_at IS NULL AND (NEW.hold_reason IS NOT NULL OR NEW.hold_boundary IS NOT NULL OR NEW.hold_application_invoked IS NOT NULL OR NEW.hold_evidence_digest IS NOT NULL))
      OR (NEW.held_at IS NOT NULL AND (NEW.hold_reason IS NULL OR NEW.hold_reason NOT IN ({_quoted(_REASONS)})
              OR NEW.hold_boundary IS NULL OR NEW.hold_boundary NOT IN ('outer','nested','control') OR NEW.hold_evidence_digest IS NULL OR NEW.held_at < NEW.claimed_at
              OR (NEW.prepared_at IS NOT NULL AND NEW.held_at<NEW.prepared_at)
              OR (NEW.dispatched_at IS NOT NULL AND NEW.held_at<NEW.dispatched_at)))
      OR (NEW.hold_application_invoked = {"FALSE" if pg else "0"} AND (NEW.hold_boundary!='outer' OR NEW.hold_reason NOT IN ('package_mismatch','runtime_mismatch','session_mismatch','membership_mismatch')))
      OR (NEW.disposition='OPEN' AND NEW.held_at IS NOT NULL) OR (NEW.disposition='HELD' AND NEW.held_at IS NULL)
      OR (NEW.disposition!='RESOLVED' AND (NEW.resolution_kind IS NOT NULL OR NEW.resolution_digest IS NOT NULL OR NEW.resolved_at IS NOT NULL))
      OR (NEW.disposition='RESOLVED' AND (NEW.resolution_kind IS NULL OR NEW.resolution_kind NOT IN ({_quoted(_KINDS)})
          OR NEW.resolution_digest IS NULL OR NEW.resolved_at IS NULL OR NEW.resolved_at < NEW.claimed_at
          OR (NEW.held_at IS NOT NULL AND NEW.resolved_at < NEW.held_at)
          OR (NEW.dispatched_at IS NOT NULL AND NEW.resolved_at < NEW.dispatched_at)
          OR (NEW.resolution_kind='application_completed' AND NEW.dispatched_at IS NULL)))
    """
    qualification_kind = (
        "jsonb_typeof(NEW.facts_json::jsonb -> 'job_qualification')"
        if pg
        else "json_type(NEW.facts_json, '$.job_qualification')"
    )
    shape += f""" OR ({j("binding.runner_family")}!='ray_job' AND {qualification_kind} {unequal} 'null')
      OR ({j("binding.runner_family")}='ray_job' AND (
        {qualification_kind} {unequal} 'object'
        OR {q("consumed_challenge_revision", integer=True)}!={q("request_revision", integer=True)}+1
        OR {q("endpoint_expectation_digest")} {unequal} {j("target_expectation_digest")}
        OR {q("configuration_digest")} {unequal} ({intent_value("configuration_digest")})
        OR {database_time("NEW.claimed_at")} < {wire_time(q("consumed_at"))}
        OR {database_time("NEW.claimed_at")} >= {wire_time(q("challenge_expires_at"))}
        OR {database_time("NEW.claimed_at")} >= {wire_time(q("endpoint_expires_at"))}
      ))"""
    qualification_count = (
        "(SELECT COUNT(*) FROM jsonb_object_keys(NEW.facts_json::jsonb -> 'job_qualification'))"
        if pg
        else "(SELECT COUNT(*) FROM json_each(NEW.facts_json, '$.job_qualification'))"
    )
    string_kinds = " OR ".join(
        f"jsonb_typeof(NEW.facts_json::jsonb #> '{{job_qualification,{name}}}') IS DISTINCT FROM 'string'"
        if pg
        else f"json_type(NEW.facts_json, '$.job_qualification.{name}') IS NOT 'text'"
        for name in _JOB_QUALIFICATION_STRINGS
    )
    shape += f" OR ({j('binding.runner_family')}='ray_job' AND ({qualification_count}!=20 OR {string_kinds}))"
    original_owner = f"""NEW.owner_lease_id {unequal} {j("worker_lease_id")}
       OR NEW.owner_lease_hostname {unequal} {j("worker_lease_hostname")}
       OR NEW.owner_lease_pid {unequal} {j("worker_lease_pid", integer=True)}
       OR NOT ({timestamp_matches("NEW.owner_lease_started_at", "worker_lease_started_at")})"""
    if not pg:
        shape += " OR " + " OR ".join(
            f"typeof(NEW.{column})!='integer'"
            for column in (
                "id",
                "binding_id",
                "attempt_number",
                "execution_generation",
                "revision",
                "owner_lease_pid",
            )
        )
        shape += " OR " + " OR ".join(
            f"json_type(NEW.facts_json, '$.{path}') IS NOT 'integer'"
            for path in (
                "schema_version",
                "execution_protocol_version",
                "binding_id",
                "identity.task_execution_pk",
                "identity.attempt_number",
                "identity.execution_generation",
                "worker_lease_pid",
                "manager.python.major",
                "manager.python.minor",
                "manager.python.patch",
            )
        )
        shape += (
            " OR ("
            + j("binding.runner_family")
            + "!='sync' AND ("
            + " OR ".join(
                f"json_type(NEW.facts_json, '$.{path}') IS NOT 'integer'"
                for path in (
                    "target_policy_id",
                    "claim_attestation_id",
                    "capability.capability_id",
                    "capability.schema_version",
                    "capability.revision",
                    "manager.ray_version[0]",
                    "manager.ray_version[1]",
                    "manager.ray_version[2]",
                )
            )
            + "))"
        )
        shape += (
            " OR ("
            + j("binding.runner_family")
            + "='ray_job' AND ("
            + " OR ".join(
                f"json_type(NEW.facts_json, '$.job_qualification.{name}') IS NOT 'integer'"
                for name in _JOB_QUALIFICATION_INTEGERS
            )
            + "))"
        )
    if pg:
        shape += (
            " OR ("
            + j("binding.runner_family")
            + "='ray_job' AND ("
            + " OR ".join(
                f"jsonb_typeof(NEW.facts_json::jsonb #> '{{job_qualification,{name}}}') IS DISTINCT FROM 'number' OR {q(name)} !~ '^[1-9][0-9]{{0,18}}$' OR {q(name, integer=True)} NOT BETWEEN 1 AND {_MAX}"
                for name in _JOB_QUALIFICATION_INTEGERS
            )
            + "))"
        )
    request_in_receipt = (
        "r.receipt_json::jsonb -> 'request' = r.request_json::jsonb"
        if pg
        else "json_extract(r.receipt_json, '$.request') = r.request_json"
    )
    expectation_matches = " AND ".join(
        f"{receipt_value('attestation.expectation.' + name)} = {json_value('p.expectation_json', name)}"
        for name in ("target_key", "runner_family", "cluster_session", "policy_revision")
    )
    runtime_matches = " AND ".join(
        f"{receipt_value('attestation.expectation.runtime.' + name)} = {json_value('p.expectation_json', 'runtime.' + name)} AND {request_value('expected_runtime.' + name)} = {json_value('p.expectation_json', 'runtime.' + name)}"
        for name in (
            "ray_major",
            "ray_minor",
            "ray_patch",
            "python_implementation",
            "python_major",
            "python_minor",
            "python_patch",
        )
    )
    jobs_proof = f"""EXISTS (
      SELECT 1 FROM {challenge} pc JOIN {job_receipt} r ON r.challenge_id=pc.id
      WHERE pc.id={q("challenge_id", integer=True)} AND pc.lease_id=l.worker_id
        AND pc.lease_hostname=l.hostname AND pc.lease_pid=l.pid AND pc.lease_started_at=l.started_at
        AND pc.runner_family='ray_job' AND pc.configuration_digest=i.configuration_digest
        AND pc.configuration_digest={q("configuration_digest")}
        AND pc.revision={q("consumed_challenge_revision", integer=True)}
        AND r.challenge_revision={q("request_revision", integer=True)} AND pc.revision=r.challenge_revision+1
        AND pc.consumed_at IS NOT NULL AND r.receipt_json IS NOT NULL AND r.received_at IS NOT NULL
        AND ({timestamp_matches("pc.issued_at", "job_qualification.challenge_issued_at")})
        AND ({timestamp_matches("pc.expires_at", "job_qualification.challenge_expires_at")})
        AND ({timestamp_matches("pc.consumed_at", "job_qualification.consumed_at")})
        AND ({timestamp_matches("r.received_at", "job_qualification.receipt_received_at")})
        AND r.received_at<=pc.consumed_at AND pc.consumed_at<=NEW.claimed_at AND NEW.claimed_at<pc.expires_at
        AND (pc.expected_target_policy_id IS NULL OR pc.expected_target_policy_id=p.id)
        AND ({request_value("expected_target_policy_id", integer=True)} {("IS NOT DISTINCT FROM" if pg else "IS")} pc.expected_target_policy_id)
        AND r.ray_address={q("jobs_endpoint")} AND r.request_digest={q("request_digest")}
        AND r.receipt_digest={q("receipt_digest")} AND r.submission_id={q("submission_id")}
        AND r.entrypoint_digest={q("entrypoint_digest")} AND r.submitted_runtime_env_digest={q("submitted_control_runtime_env_digest")}
        AND {request_value("schema")}='django-ray.cohort-probe-job' AND {request_value("schema_version", integer=True)}=2
        AND {request_value("challenge_id", integer=True)}=pc.id AND {request_value("challenge_revision", integer=True)}=r.challenge_revision
        AND {request_value("configuration_digest")}=pc.configuration_digest AND {request_value("runner_family")}='ray_job'
        AND {request_value("lease.worker_id")}=l.worker_id AND {request_value("lease.hostname")}=l.hostname AND {request_value("lease.pid", integer=True)}=l.pid
        AND {wire_time(request_value("lease.started_at"))}={database_time("l.started_at")}
        AND {wire_time(request_value("issued_at"))}={database_time("pc.issued_at")}
        AND {wire_time(request_value("expires_at"))}={database_time("pc.expires_at")}
        AND {request_value("expected_package_version")}=b.package_version
        AND {receipt_value("schema")}='django-ray.cohort-probe-job-receipt' AND {receipt_value("schema_version", integer=True)}=1
        AND {request_in_receipt}
        AND {receipt_value("request_digest")}=r.request_digest AND {receipt_value("submission_id")}=r.submission_id
        AND {receipt_value("native_job_id")}={q("native_job_id")} AND {receipt_value("observed_package_version")}=b.package_version
        AND {receipt_value("attestation.expectation_digest")}=p.expectation_digest
        AND {receipt_value("attestation.attestation_digest")}={q("endpoint_attestation_digest")}
        AND {receipt_value("attestation.membership_digest")}={q("endpoint_membership_digest")}
        AND {receipt_value("attestation.membership_digest")}=a.membership_digest
        AND {receipt_value("attestation.observed_at")}={q("endpoint_observed_at")}
        AND {receipt_value("attestation.expires_at")}={q("endpoint_expires_at")}
        AND {wire_time(receipt_value("attestation.observed_at"))}>={database_time("r.reserved_at")}
        AND {wire_time(receipt_value("attestation.observed_at"))}<={wire_time(receipt_value("collected_at"))}
        AND {wire_time(receipt_value("collected_at"))}<={database_time("r.received_at")}
        AND {database_time("NEW.claimed_at")}<{wire_time(receipt_value("attestation.expires_at"))}
        AND {expectation_matches} AND {runtime_matches}
    )"""
    insertion = f"""
      NEW.disposition!='OPEN' OR NEW.revision!=1 OR NEW.prepared_at IS NOT NULL OR NEW.dispatched_at IS NOT NULL
      OR NEW.held_at IS NOT NULL OR NEW.resolved_at IS NOT NULL OR ({original_owner})
      OR NOT EXISTS (
        SELECT 1 FROM {binding} b JOIN {execution} e ON e.id=b.execution_id
        JOIN {intent} i ON i.execution_id=e.id JOIN {lease} l ON l.worker_id=NEW.owner_lease_id
        WHERE b.execution_id=NEW.binding_id AND b.schema_version=2 AND e.execution_protocol_version=3
          AND e.state='QUEUED' AND e.task_id={j("identity.task_id")}
          AND e.attempt_number=NEW.attempt_number AND e.execution_generation+1=NEW.execution_generation
          AND b.runner_family={j("binding.runner_family")} AND b.package_version={j("binding.package_version")}
          AND (b.target_policy_id {("IS NOT DISTINCT FROM" if pg else "IS")} {j("binding.target_policy_id", integer=True)})
          AND b.package_version={j("manager.package_version")} AND i.package_version=b.package_version
          AND i.package_version=({intent_value("package_version")}) AND i.backend_alias=({intent_value("backend_alias")})
          AND i.configuration_digest=({intent_value("configuration_digest")})
          AND i.runtime_env_identity_digest=({intent_value("runtime_env_identity_digest")})
          AND i.selection_policy=({intent_value("selection_policy")})
          AND l.django_ray_version=b.package_version AND l.hostname=NEW.owner_lease_hostname AND l.pid=NEW.owner_lease_pid
          AND l.started_at=NEW.owner_lease_started_at AND l.is_active={"TRUE" if pg else "1"} AND l.stopped_at IS NULL
          AND l.capability_schema_version=1 AND l.legacy_admission_token_id IS NULL
          AND l.min_supported_execution_protocol_version<=3 AND l.max_supported_execution_protocol_version>=3
          AND NEW.claimed_at>=l.started_at AND NEW.claimed_at>=b.created_at AND NEW.claimed_at>=i.created_at
          AND (e.runtime_env_profile {("IS NOT DISTINCT FROM" if pg else "IS")} {j("runtime_env_profile")})
          AND (e.runtime_env_hash {("IS NOT DISTINCT FROM" if pg else "IS")} {j("runtime_env_hash")})
          AND ((b.runner_family='sync' AND NEW.target_policy_id IS NULL AND NEW.claim_attestation_id IS NULL
            AND {j("target_expectation_digest")} IS NULL AND {j("claim_attestation_digest")} IS NULL
            AND {j("capability")} IS NULL AND {j("manager.ray_version")} IS NULL
            AND b.sync_python_implementation={j("manager.python.implementation")}
            AND b.sync_python_major={j("manager.python.major", integer=True)}
            AND b.sync_python_minor={j("manager.python.minor", integer=True)}
            AND b.sync_python_patch={j("manager.python.patch", integer=True)})
          OR (b.runner_family IN ('ray_core','ray_job') AND EXISTS (
            SELECT 1 FROM {policy} selected JOIN {policy} p ON p.target_id=selected.target_id
            JOIN {target} t ON t.target_key=p.target_id JOIN {attestation} a ON a.policy_id=p.id
            JOIN {capability} c ON c.target_id=t.target_key AND c.lease_id=l.worker_id
            WHERE selected.id=b.target_policy_id AND p.id=NEW.target_policy_id AND a.id=NEW.claim_attestation_id
              AND c.id={j("capability.capability_id", integer=True)} AND c.revision={j("capability.revision", integer=True)}
              AND c.schema_version={j("capability.schema_version", integer=True)}
              AND c.target_policy_id=p.id AND c.attestation_id=a.id AND c.runner_family=b.runner_family
              AND c.lease_hostname=l.hostname AND c.lease_pid=l.pid AND c.lease_started_at=l.started_at
              AND p.expectation_digest={j("target_expectation_digest")} AND a.attestation_digest={j("claim_attestation_digest")}
              AND a.expectation_digest=p.expectation_digest AND NEW.claimed_at>=a.recorded_at AND NEW.claimed_at<a.expires_at
              AND NEW.claimed_at>=c.advertised_at AND ({timestamp_matches("c.advertised_at", "capability.advertised_at")})
              AND c.manager_python_implementation={j("manager.python.implementation")}
              AND c.manager_python_major={j("manager.python.major", integer=True)}
              AND c.manager_python_minor={j("manager.python.minor", integer=True)}
              AND c.manager_python_patch={j("manager.python.patch", integer=True)}
              AND c.manager_ray_major={j("manager.ray_version.0", integer=True)}
              AND c.manager_ray_minor={j("manager.ray_version.1", integer=True)}
              AND c.manager_ray_patch={j("manager.ray_version.2", integer=True)}
              AND p.desired_state IN ('active','draining')
              AND (p.desired_state='active' OR EXISTS (SELECT 1 FROM {claim} prior WHERE prior.binding_id=NEW.binding_id AND prior.id!=NEW.id))
              AND p.revision=(SELECT MAX(p2.revision) FROM {policy} p2 WHERE p2.target_id=p.target_id)
              AND a.revision=(SELECT MAX(a2.revision) FROM {attestation} a2 WHERE a2.policy_id=p.id)
              AND (b.runner_family!='ray_job' OR {jobs_proof})
          )))
      ) OR EXISTS (SELECT 1 FROM {claim} c WHERE c.binding_id=NEW.binding_id AND c.id!=NEW.id AND c.disposition!='RESOLVED')
    """
    locks = (
        f"""PERFORM 1 FROM {lease} WHERE worker_id=NEW.owner_lease_id FOR UPDATE;
        IF NEW.target_policy_id IS NOT NULL THEN
          PERFORM 1 FROM {target} t JOIN {policy} p ON p.target_id=t.target_key WHERE p.id=NEW.target_policy_id FOR UPDATE OF t;
          PERFORM 1 FROM {policy} WHERE id=NEW.target_policy_id FOR UPDATE;
          PERFORM 1 FROM {attestation} WHERE id=NEW.claim_attestation_id FOR UPDATE;
          IF {j("binding.runner_family")}='ray_job' THEN
            PERFORM 1 FROM {challenge} WHERE id={q("challenge_id", integer=True)} FOR UPDATE;
            PERFORM 1 FROM {job_receipt} WHERE challenge_id={q("challenge_id", integer=True)} FOR UPDATE;
          END IF;
          PERFORM 1 FROM {capability} WHERE id={j("capability.capability_id", integer=True)} FOR UPDATE;
        END IF;
        PERFORM 1 FROM {execution} WHERE id=NEW.binding_id FOR UPDATE;"""
        if pg
        else ""
    )
    trigger("ray_cclaim_insert_0030", claim, "INSERT", f"({shape}) OR ({insertion})", locks=locks)

    mutation = f"""({changed(_FACTS)}) OR NEW.revision!=OLD.revision+1 OR OLD.disposition='RESOLVED'
      OR (OLD.disposition='HELD' AND NEW.disposition NOT IN ('HELD','RESOLVED'))
      OR (OLD.prepared_at IS NOT NULL AND ({changed(("prepared_request_digest", "prepared_at"))}))
      OR (OLD.dispatched_at IS NOT NULL AND ({changed(("dispatched_at",))}))
      OR (OLD.held_at IS NOT NULL AND ({changed(_HOLD)}))
      OR (OLD.resolved_at IS NOT NULL AND ({changed(_RESOLUTION)}))
      OR (OLD.disposition!='OPEN' AND ({changed(("prepared_request_digest", "prepared_at", "dispatched_at"))}))
      OR NOT EXISTS (
        SELECT 1 FROM {execution} e JOIN {lease} l ON l.worker_id=NEW.owner_lease_id
        WHERE e.id=NEW.binding_id AND e.execution_protocol_version=3 AND e.state IN ('RUNNING','CANCELLING')
          AND e.attempt_number=NEW.attempt_number AND e.execution_generation=NEW.execution_generation
          AND e.claimed_by_worker=NEW.owner_lease_id AND l.hostname=NEW.owner_lease_hostname AND l.pid=NEW.owner_lease_pid
          AND l.started_at=NEW.owner_lease_started_at AND l.is_active={"TRUE" if pg else "1"} AND l.stopped_at IS NULL
          AND l.django_ray_version={j("binding.package_version")}
          AND l.capability_schema_version=1 AND l.legacy_admission_token_id IS NULL
          AND l.min_supported_execution_protocol_version<=3 AND l.max_supported_execution_protocol_version>=3
      )"""
    mutation += f""" OR (({changed(_OWNER)}) AND (
        NEW.owner_lease_id=OLD.owner_lease_id
        OR EXISTS (SELECT 1 FROM {lease} previous WHERE previous.worker_id=OLD.owner_lease_id AND previous.is_active={"TRUE" if pg else "1"})
    ))"""
    trigger("ray_cclaim_update_0030", claim, "UPDATE", f"({shape}) OR ({mutation})")

    # Resolution is written while the original generation is still nonterminal.
    # Its lifecycle transition can then follow inside the same transaction.
    execution_guard = f"""OLD.execution_protocol_version=3 AND (
      (OLD.state IN ('RUNNING','CANCELLING') AND (
        NEW.execution_protocol_version!=3 OR NEW.attempt_number!=OLD.attempt_number OR NEW.execution_generation!=OLD.execution_generation
        OR NEW.state IN ('QUEUED','SUCCEEDED','FAILED','LOST','EXPIRED','CANCELLED')
      ) AND NOT EXISTS (SELECT 1 FROM {claim} c WHERE c.binding_id=OLD.id AND c.attempt_number=OLD.attempt_number
            AND c.execution_generation=OLD.execution_generation AND c.disposition='RESOLVED'))
      OR (OLD.state='QUEUED' AND NEW.state='RUNNING' AND NOT EXISTS (
        SELECT 1 FROM {claim} c WHERE c.binding_id=NEW.id AND c.attempt_number=NEW.attempt_number
          AND c.execution_generation=NEW.execution_generation AND NEW.execution_generation=OLD.execution_generation+1
          AND c.owner_lease_id=NEW.claimed_by_worker AND c.disposition='OPEN'
      ))
      OR (EXISTS (SELECT 1 FROM {claim} c WHERE c.binding_id=OLD.id AND c.attempt_number=OLD.attempt_number
           AND c.execution_generation=OLD.execution_generation AND c.disposition='HELD')
         AND (NEW.ray_job_id {unequal} OLD.ray_job_id OR NEW.ray_address {unequal} OLD.ray_address
           OR NEW.ray_job_request_reference {unequal} OLD.ray_job_request_reference))
    )"""
    if not pg:
        counters = f"typeof(NEW.attempt_number)!='integer' OR typeof(NEW.execution_generation)!='integer' OR NEW.attempt_number NOT BETWEEN 1 AND 2147483647 OR NEW.execution_generation NOT BETWEEN 0 AND {_MAX}"
        execution_guard += f" OR (NEW.execution_protocol_version=3 AND ({counters}))"
        trigger(
            "ray_cexecution_insert_0030",
            execution,
            "INSERT",
            f"NEW.execution_protocol_version=3 AND ({counters})",
        )
    trigger("ray_cexecution_update_0030", execution, "UPDATE", execution_guard)
    trigger(
        "ray_cclaim_delete_0030",
        claim,
        "DELETE",
        f"""OLD.disposition!='RESOLVED' AND EXISTS (
      SELECT 1 FROM {execution} e WHERE e.id=OLD.binding_id AND e.state IN ('RUNNING','CANCELLING')
        AND e.attempt_number=OLD.attempt_number AND e.execution_generation=OLD.execution_generation
    )""",
    )
    _external_fences(apps, editor, install=True)


def _remove(apps, editor):
    tables = _tables(apps, editor)
    claim = tables["RayTaskCohortClaim"]
    binding = tables["RayTaskTargetBinding"]
    if editor.connection.vendor == "postgresql":
        editor.execute(f"LOCK TABLE {binding}, {claim} IN ACCESS EXCLUSIVE MODE")
    elif editor.connection.vendor == "sqlite":
        editor.execute(f"UPDATE {binding} SET execution_id=execution_id WHERE 0")
        editor.execute(f"UPDATE {claim} SET revision=revision WHERE 0")
    else:
        raise RuntimeError("Cohort claim ledger requires SQLite or PostgreSQL")
    if (
        apps.get_model("django_ray", "RayTaskCohortClaim")
        .objects.using(editor.connection.alias)
        .exists()
        or apps.get_model("django_ray", "RayTaskTargetBinding")
        .objects.using(editor.connection.alias)
        .filter(schema_version=2)
        .exists()
    ):
        raise RuntimeError(
            "Cannot reverse cohort claim storage while protocol-3 bindings or claims remain"
        )
    for name, model in (
        ("ray_cbinding_insert_0030", "RayTaskTargetBinding"),
        ("ray_cbinding_update_0030", "RayTaskTargetBinding"),
        ("ray_cclaim_insert_0030", "RayTaskCohortClaim"),
        ("ray_cclaim_update_0030", "RayTaskCohortClaim"),
        ("ray_cexecution_update_0030", "RayTaskExecution"),
        ("ray_cclaim_delete_0030", "RayTaskCohortClaim"),
        ("ray_cexecution_insert_0030", "RayTaskExecution"),
    ):
        if editor.connection.vendor == "postgresql":
            editor.execute(f"DROP TRIGGER IF EXISTS {name} ON {tables[model]}")
            editor.execute(f"DROP FUNCTION IF EXISTS django_ray_{name}()")
        else:
            editor.execute(f"DROP TRIGGER IF EXISTS {name}")
    _external_fences(apps, editor, install=False)


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0029_cohort_job_receipts"),
    ]

    operations = [
        migrations.RunPython(_remove_old, _restore_old),
        migrations.CreateModel(
            name="RayTaskCohortClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField(editable=False)),
                ("execution_generation", models.PositiveBigIntegerField(editable=False)),
                ("facts_json", models.TextField(editable=False)),
                ("facts_digest", models.CharField(editable=False, max_length=71)),
                ("owner_lease_id", models.CharField(editable=False, max_length=255)),
                ("owner_lease_hostname", models.CharField(editable=False, max_length=255)),
                ("owner_lease_pid", models.PositiveIntegerField(editable=False)),
                ("owner_lease_started_at", models.DateTimeField(editable=False)),
                ("claimed_at", models.DateTimeField(editable=False)),
                ("disposition", models.CharField(db_default="OPEN", default="OPEN", max_length=8)),
                ("revision", models.PositiveBigIntegerField(db_default=1, default=1)),
                (
                    "prepared_request_digest",
                    models.CharField(editable=False, max_length=71, null=True),
                ),
                ("prepared_at", models.DateTimeField(editable=False, null=True)),
                ("dispatched_at", models.DateTimeField(editable=False, null=True)),
                ("hold_reason", models.CharField(editable=False, max_length=32, null=True)),
                ("hold_boundary", models.CharField(editable=False, max_length=8, null=True)),
                ("hold_application_invoked", models.BooleanField(editable=False, null=True)),
                (
                    "hold_evidence_digest",
                    models.CharField(editable=False, max_length=71, null=True),
                ),
                ("held_at", models.DateTimeField(editable=False, null=True)),
                ("resolution_kind", models.CharField(editable=False, max_length=32, null=True)),
                ("resolution_digest", models.CharField(editable=False, max_length=71, null=True)),
                ("resolved_at", models.DateTimeField(editable=False, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="raytasktargetbinding",
            name="ray_tbinding_schema_valid",
        ),
        migrations.AddField(
            model_name="raytasktargetbinding",
            name="package_version",
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="raytasktargetbinding",
            name="runner_family",
            field=models.CharField(editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="raytasktargetbinding",
            name="sync_python_implementation",
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="raytasktargetbinding",
            name="sync_python_major",
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="raytasktargetbinding",
            name="sync_python_minor",
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="raytasktargetbinding",
            name="sync_python_patch",
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="raytasktargetbinding",
            name="schema_version",
            field=models.PositiveSmallIntegerField(
                db_default=1,
                default=1,
                editable=False,
                help_text="Schema version for this dormant task target binding",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="raytasktargetbinding",
            name="target_policy",
            field=models.ForeignKey(
                editable=False,
                help_text="Immutable Ray target policy revision selected for this task",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="task_target_bindings",
                to="django_ray.raytargetpolicyrevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytasktargetbinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("package_version__isnull", True),
                        ("runner_family__isnull", True),
                        ("schema_version", 1),
                        ("sync_python_implementation__isnull", True),
                        ("sync_python_major__isnull", True),
                        ("sync_python_minor__isnull", True),
                        ("sync_python_patch__isnull", True),
                        ("target_policy__isnull", False),
                    ),
                    models.Q(
                        ("package_version__isnull", False),
                        ("runner_family", "sync"),
                        ("schema_version", 2),
                        ("sync_python_implementation__isnull", False),
                        ("sync_python_major__gte", 1),
                        ("sync_python_minor__gte", 0),
                        ("sync_python_patch__gte", 0),
                        ("target_policy__isnull", True),
                    ),
                    models.Q(
                        ("package_version__isnull", False),
                        ("runner_family__in", ("ray_core", "ray_job")),
                        ("schema_version", 2),
                        ("sync_python_implementation__isnull", True),
                        ("sync_python_major__isnull", True),
                        ("sync_python_minor__isnull", True),
                        ("sync_python_patch__isnull", True),
                        ("target_policy__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ray_tbinding_schema_valid",
            ),
        ),
        migrations.AddField(
            model_name="raytaskcohortclaim",
            name="binding",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohort_claims",
                to="django_ray.raytasktargetbinding",
            ),
        ),
        migrations.AddField(
            model_name="raytaskcohortclaim",
            name="claim_attestation",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohort_claims",
                to="django_ray.raytargetattestationrevision",
            ),
        ),
        migrations.AddField(
            model_name="raytaskcohortclaim",
            name="target_policy",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohort_claims",
                to="django_ray.raytargetpolicyrevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytaskcohortclaim",
            constraint=models.UniqueConstraint(
                fields=("binding", "attempt_number", "execution_generation"),
                name="ray_cclaim_generation_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="raytaskcohortclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attempt_number__gte", 1),
                    ("attempt_number__lte", 2147483647),
                    ("disposition__in", ("OPEN", "HELD", "RESOLVED")),
                    ("execution_generation__gte", 1),
                    ("revision__gte", 1),
                ),
                name="ray_cclaim_counters_valid",
            ),
        ),
        migrations.RunPython(_install, _remove),
    ]
