# Generated by Django 6.1.1 on 2026-09-12 08:11

import hashlib
from datetime import UTC, datetime

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models

_MAX = 9223372036854775807
_NAMESPACE = 1684697721
_KEY = 368


def _seed(apps, editor):
    now = datetime.now(UTC)
    apps.get_model("django_ray", "RayMaintenanceAudit").objects.using(
        editor.connection.alias
    ).create(
        revision=1,
        previous_revision=0,
        pause_enqueues=False,
        pause_claims=False,
        scope_count=0,
        scopes_json="[]",
        scopes_digest=hashlib.sha256(b"django-ray:maintenance-scopes:v1\x00[]").hexdigest(),
        actor="migration",
        reason="initial",
        created_at=now,
    )
    apps.get_model("django_ray", "RayMaintenancePolicy").objects.using(
        editor.connection.alias
    ).create(
        singleton_key=1,
        schema_version=1,
        revision=1,
        pause_enqueues=False,
        pause_claims=False,
        updated_at=now,
    )


def _tables(apps, editor):
    return {
        name: editor.quote_name(apps.get_model("django_ray", name)._meta.db_table)
        for name in (
            "RayMaintenancePolicy",
            "RayMaintenanceAudit",
            "RayMaintenanceScope",
            "RayTaskExecution",
            "RayTaskTargetBinding",
            "RayTaskCohortClaim",
            "RayTargetPolicyRevision",
        )
    }


def _install(apps, editor):
    tables = _tables(apps, editor)
    pg = editor.connection.vendor == "postgresql"
    if not pg and editor.connection.vendor != "sqlite":
        raise RuntimeError("Maintenance admission requires SQLite or PostgreSQL")
    policy, audit, scope, execution, binding, claim, target_policy = (
        tables[name]
        for name in (
            "RayMaintenancePolicy",
            "RayMaintenanceAudit",
            "RayMaintenanceScope",
            "RayTaskExecution",
            "RayTaskTargetBinding",
            "RayTaskCohortClaim",
            "RayTargetPolicyRevision",
        )
    )
    unequal = "IS DISTINCT FROM" if pg else "IS NOT"
    true = "TRUE" if pg else "1"

    if pg:
        # BEFORE ROW runs after the UPDATE/DELETE tuple lock. Acquire the
        # writer barrier at statement entry as well, so raw SQL cannot invert
        # a supported service's exclusive-barrier -> policy-row lock order.
        for suffix, table in (("policy", policy), ("audit", audit), ("scope", scope)):
            name = f"ray_maint_{suffix}_barrier_0031"
            editor.execute(f"""CREATE FUNCTION django_ray_{name}() RETURNS trigger AS $$
              BEGIN
                IF current_setting('transaction_isolation') != 'read committed' THEN
                  RAISE EXCEPTION 'maintenance admission requires read committed';
                END IF;
                PERFORM pg_advisory_xact_lock({_NAMESPACE}, {_KEY});
                RETURN NULL;
              END; $$ LANGUAGE plpgsql""")
            editor.execute(
                f"CREATE TRIGGER {name} BEFORE INSERT OR UPDATE OR DELETE ON {table} FOR EACH STATEMENT EXECUTE FUNCTION django_ray_{name}()"
            )

    def trigger(name, table, event, condition, *, exclusive=False, admission_event=None):
        if pg:
            # Acquire inside the volatile function before its fresh SPI reads.
            # Exclusive writers never acquire execution/lease/target row locks.
            lock = "pg_advisory_xact_lock" if exclusive else "pg_advisory_xact_lock_shared"
            editor.execute(f"""CREATE FUNCTION django_ray_{name}() RETURNS trigger AS $$
            BEGIN
              {f"IF NOT ({admission_event}) THEN RETURN NEW; END IF;" if admission_event else ""}
              IF current_setting('transaction_isolation') != 'read committed' THEN
                RAISE EXCEPTION 'maintenance admission requires read committed';
              END IF;
              PERFORM {lock}({_NAMESPACE}, {_KEY});
              IF {condition} THEN RAISE EXCEPTION 'maintenance admission rejected'; END IF;
              RETURN {"OLD" if event == "DELETE" else "NEW"};
            END; $$ LANGUAGE plpgsql""")
            editor.execute(
                f"CREATE TRIGGER {name} BEFORE {event} ON {table} FOR EACH ROW EXECUTE FUNCTION django_ray_{name}()"
            )
        else:
            editor.execute(f"""CREATE TRIGGER {name} BEFORE {event} ON {table}
              WHEN {condition} BEGIN SELECT RAISE(ABORT, 'maintenance admission rejected'); END""")

    coherent = f"""EXISTS (SELECT 1 FROM {policy} p JOIN {audit} a ON a.revision=p.revision
      WHERE p.singleton_key=1 AND p.schema_version=1 AND a.previous_revision=p.revision-1
      AND a.pause_enqueues=p.pause_enqueues AND a.pause_claims=p.pause_claims
      AND a.created_at=p.updated_at AND a.scope_count=(SELECT COUNT(*) FROM {scope} s WHERE s.audit_id=p.revision))"""

    def denied(operation, queue, protocol, target):
        field = "pause_enqueues" if operation == "enqueue" else "pause_claims"
        return f"""(NOT ({coherent}) OR EXISTS (SELECT 1 FROM {policy} p WHERE p.singleton_key=1 AND (
          p.{field}={true} OR EXISTS (SELECT 1 FROM {scope} s WHERE s.audit_id=p.revision AND s.{field}={true}
            AND ((s.kind='queue' AND s.queue_name={queue}) OR (s.kind='protocol' AND s.protocol_version={protocol})
              OR (s.kind='target' AND s.target_id={target}))))))"""

    target = f"(SELECT p.target_id FROM {binding} b JOIN {target_policy} p ON p.id=b.target_policy_id WHERE b.execution_id=NEW.id)"
    enqueued = denied("enqueue", "NEW.queue_name", "NEW.execution_protocol_version", target)
    claimed = denied("claim", "NEW.queue_name", "NEW.execution_protocol_version", target)
    trigger(
        "ray_maint_execution_insert_0031",
        execution,
        "INSERT",
        f"(NEW.state='QUEUED' AND {enqueued}) OR (NEW.state IN ('RUNNING','CANCELLING') AND {claimed})",
    )
    # Requeues and queue/protocol movement re-enter producer admission. Owned
    # completion/cancellation, heartbeats and same-generation adoption do not.
    queue_reentry = f"""NEW.state='QUEUED' AND (OLD.state!='QUEUED' OR NEW.queue_name {unequal} OLD.queue_name
        OR NEW.execution_protocol_version {unequal} OLD.execution_protocol_version
        OR NEW.attempt_number {unequal} OLD.attempt_number)"""
    new_claim = """NEW.state IN ('QUEUED','RUNNING','CANCELLING') AND (
        NEW.execution_generation>OLD.execution_generation OR (OLD.state='QUEUED' AND NEW.state='RUNNING'))"""
    trigger(
        "ray_maint_execution_update_0031",
        execution,
        "UPDATE",
        f"(({queue_reentry}) AND {enqueued}) OR (({new_claim}) AND {claimed})",
        admission_event=f"({queue_reentry}) OR ({new_claim})",
    )
    claim_target = f"(SELECT p.target_id FROM {target_policy} p WHERE p.id=NEW.target_policy_id)"
    claim_queue = f"(SELECT e.queue_name FROM {execution} e WHERE e.id=NEW.binding_id)"
    claim_protocol = (
        f"(SELECT e.execution_protocol_version FROM {execution} e WHERE e.id=NEW.binding_id)"
    )
    trigger(
        "ray_maint_claim_insert_0031",
        claim,
        "INSERT",
        denied("claim", claim_queue, claim_protocol, claim_target),
    )

    # Scope content is tied to the retained audit JSON before the new revision
    # becomes active. Removing rows cannot open admission: coherence fails closed.
    def item(field):
        if pg:
            return f"(a.scopes_json::jsonb -> (NEW.position-1) ->> '{field}')"
        return f"json_extract(a.scopes_json, '$[' || (NEW.position-1) || '].{field}')"

    def expected_bool(field):
        return f"CAST({item(field)} AS boolean)" if pg else item(field)

    scope_content = f"""NOT EXISTS (SELECT 1 FROM {audit} a JOIN {policy} p ON p.singleton_key=1
      WHERE a.revision=NEW.audit_id AND a.revision=p.revision+1 AND NEW.position<=a.scope_count
        AND {item("kind")}=NEW.kind AND {item("queue_name")} {("IS NOT DISTINCT FROM" if pg else "IS")} NEW.queue_name
        AND {("CAST(" + item("protocol_version") + " AS bigint)") if pg else item("protocol_version")} {("IS NOT DISTINCT FROM" if pg else "IS")} NEW.protocol_version
        AND {item("target_id")} {("IS NOT DISTINCT FROM" if pg else "IS")} NEW.target_id
        AND {expected_bool("pause_enqueues")}=NEW.pause_enqueues AND {expected_bool("pause_claims")}=NEW.pause_claims)
      OR EXISTS (SELECT 1 FROM {scope} s WHERE s.audit_id=NEW.audit_id AND s.kind=NEW.kind AND (
        (NEW.kind='queue' AND s.queue_name=NEW.queue_name) OR (NEW.kind='protocol' AND s.protocol_version=NEW.protocol_version)
        OR (NEW.kind='target' AND s.target_id=NEW.target_id)))"""
    if not pg:
        scope_content += " OR typeof(NEW.position)!='integer' OR (NEW.protocol_version IS NOT NULL AND typeof(NEW.protocol_version)!='integer') OR NEW.pause_enqueues NOT IN (0,1) OR NEW.pause_claims NOT IN (0,1)"
    trigger("ray_maint_scope_insert_0031", scope, "INSERT", scope_content, exclusive=True)
    trigger("ray_maint_scope_update_0031", scope, "UPDATE", "TRUE" if pg else "1", exclusive=True)
    trigger("ray_maint_audit_update_0031", audit, "UPDATE", "TRUE" if pg else "1", exclusive=True)
    # Destructive DB maintenance cannot race a held admission fence. Missing
    # current rows are unavailable, never reconstructed into positive policy.
    for suffix, table in (("scope", scope), ("audit", audit), ("policy", policy)):
        trigger(
            f"ray_maint_{suffix}_delete_0031",
            table,
            "DELETE",
            "FALSE" if pg else "0",
            exclusive=True,
        )
    audit_shape = f"""NEW.revision NOT BETWEEN 1 AND {_MAX} OR NEW.previous_revision!=NEW.revision-1
      OR NEW.scope_count NOT BETWEEN 0 AND 64 OR LENGTH(NEW.scopes_json)>131072
      OR LENGTH(NEW.scopes_digest)!=64 OR LENGTH(NEW.actor) NOT BETWEEN 1 AND 128 OR LENGTH(NEW.reason) NOT BETWEEN 1 AND 128
      OR (NEW.revision=1 AND (EXISTS (SELECT 1 FROM {policy}) OR NEW.scope_count!=0 OR NEW.scopes_json!='[]' OR NEW.pause_enqueues={true} OR NEW.pause_claims={true}))
      OR (NEW.revision>1 AND NOT EXISTS (SELECT 1 FROM {policy} p WHERE p.singleton_key=1 AND p.revision=NEW.previous_revision AND NEW.created_at>=p.updated_at))"""
    if pg:
        audit_shape += " OR jsonb_typeof(NEW.scopes_json::jsonb)!='array' OR jsonb_array_length(NEW.scopes_json::jsonb)!=NEW.scope_count"
    else:
        audit_shape += " OR NOT json_valid(NEW.scopes_json) OR json_type(NEW.scopes_json)!='array' OR json_array_length(NEW.scopes_json)!=NEW.scope_count OR typeof(NEW.revision)!='integer' OR typeof(NEW.previous_revision)!='integer' OR typeof(NEW.scope_count)!='integer' OR NEW.pause_enqueues NOT IN (0,1) OR NEW.pause_claims NOT IN (0,1)"
    trigger("ray_maint_audit_insert_0031", audit, "INSERT", audit_shape, exclusive=True)
    published = f"""NEW.singleton_key!=1 OR NEW.schema_version!=1 OR NEW.revision NOT BETWEEN 1 AND {_MAX}
      OR NOT EXISTS (SELECT 1 FROM {audit} a WHERE a.revision=NEW.revision
        AND a.pause_enqueues=NEW.pause_enqueues AND a.pause_claims=NEW.pause_claims AND a.created_at=NEW.updated_at
        AND a.scope_count=(SELECT COUNT(*) FROM {scope} s WHERE s.audit_id=a.revision))"""
    if not pg:
        published += " OR typeof(NEW.revision)!='integer' OR NEW.pause_enqueues NOT IN (0,1) OR NEW.pause_claims NOT IN (0,1)"
    trigger(
        "ray_maint_policy_insert_0031",
        policy,
        "INSERT",
        f"({published}) OR NEW.revision!=1 OR EXISTS (SELECT 1 FROM {audit} a WHERE a.revision>1)",
        exclusive=True,
    )
    changed = " OR ".join(
        f"NEW.{field} {unequal} OLD.{field}"
        for field in (
            "singleton_key",
            "schema_version",
            "revision",
            "pause_enqueues",
            "pause_claims",
            "updated_at",
        )
    )
    trigger(
        "ray_maint_policy_update_0031",
        policy,
        "UPDATE",
        f"({changed}) AND (({published}) OR NEW.revision!=OLD.revision+1 OR NEW.updated_at<OLD.updated_at)",
        exclusive=True,
    )


def _remove(apps, editor):
    tables = _tables(apps, editor)
    if editor.connection.vendor == "postgresql":
        editor.execute(f"SELECT pg_advisory_xact_lock({_NAMESPACE}, {_KEY})")
    elif editor.connection.vendor == "sqlite":
        editor.execute(f"UPDATE {tables['RayMaintenancePolicy']} SET revision=revision")
    else:
        raise RuntimeError("Maintenance admission requires SQLite or PostgreSQL")
    # A stopped-writer upgrade may remove an unused seed. Never erase an audit
    # or silently reopen an installed pause during migration rollback.
    if (
        apps.get_model("django_ray", "RayMaintenanceAudit")
        .objects.using(editor.connection.alias)
        .exclude(revision=1)
        .exists()
        or apps.get_model("django_ray", "RayMaintenanceScope")
        .objects.using(editor.connection.alias)
        .exists()
        or apps.get_model("django_ray", "RayMaintenancePolicy")
        .objects.using(editor.connection.alias)
        .exclude(revision=1, schema_version=1, pause_enqueues=False, pause_claims=False)
        .exists()
    ):
        raise RuntimeError("Cannot reverse maintenance admission with retained policy history")
    for suffix, model in (
        ("execution_insert", "RayTaskExecution"),
        ("execution_update", "RayTaskExecution"),
        ("claim_insert", "RayTaskCohortClaim"),
        ("scope_insert", "RayMaintenanceScope"),
        ("scope_update", "RayMaintenanceScope"),
        ("audit_insert", "RayMaintenanceAudit"),
        ("audit_update", "RayMaintenanceAudit"),
        ("policy_insert", "RayMaintenancePolicy"),
        ("policy_update", "RayMaintenancePolicy"),
        ("scope_delete", "RayMaintenanceScope"),
        ("audit_delete", "RayMaintenanceAudit"),
        ("policy_delete", "RayMaintenancePolicy"),
        ("scope_barrier", "RayMaintenanceScope"),
        ("audit_barrier", "RayMaintenanceAudit"),
        ("policy_barrier", "RayMaintenancePolicy"),
    ):
        name = f"ray_maint_{suffix}_0031"
        if editor.connection.vendor == "postgresql":
            editor.execute(f"DROP TRIGGER IF EXISTS {name} ON {tables[model]}")
            editor.execute(f"DROP FUNCTION IF EXISTS django_ray_{name}()")
        else:
            editor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0030_cohort_claims"),
    ]

    operations = [
        migrations.CreateModel(
            name="RayMaintenanceAudit",
            fields=[
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("previous_revision", models.PositiveBigIntegerField(editable=False)),
                ("pause_enqueues", models.BooleanField(editable=False)),
                ("pause_claims", models.BooleanField(editable=False)),
                ("scope_count", models.PositiveSmallIntegerField(editable=False)),
                ("scopes_json", models.TextField(editable=False)),
                ("scopes_digest", models.CharField(editable=False, max_length=64)),
                ("actor", models.CharField(editable=False, max_length=128)),
                ("reason", models.CharField(editable=False, max_length=128)),
                ("created_at", models.DateTimeField(editable=False)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "previous_revision",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("revision"), "-", models.Value(1)
                                ),
                            ),
                            ("revision__gte", 1),
                        ),
                        name="ray_maint_audit_revision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("scope_count__lte", 64)), name="ray_maint_audit_scopes"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RayMaintenancePolicy",
            fields=[
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField(default=1, editable=False)),
                ("revision", models.PositiveBigIntegerField(default=1, editable=False)),
                ("pause_enqueues", models.BooleanField(default=False, editable=False)),
                ("pause_claims", models.BooleanField(default=False, editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("revision__gte", 1), ("schema_version", 1), ("singleton_key", 1)
                        ),
                        name="ray_maint_policy_shape",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RayMaintenanceScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(editable=False)),
                ("kind", models.CharField(editable=False, max_length=8)),
                ("queue_name", models.CharField(editable=False, max_length=100, null=True)),
                ("protocol_version", models.PositiveSmallIntegerField(editable=False, null=True)),
                ("pause_enqueues", models.BooleanField(editable=False)),
                ("pause_claims", models.BooleanField(editable=False)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scopes",
                        to="django_ray.raymaintenanceaudit",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_scopes",
                        to="django_ray.raytarget",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("audit", "position"), name="ray_maint_scope_position"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 1), ("position__lte", 64)),
                        name="ray_maint_scope_bound",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                models.Q(
                                    ("kind", "queue"),
                                    ("protocol_version__isnull", True),
                                    ("queue_name__isnull", False),
                                    ("target__isnull", True),
                                ),
                                models.Q(
                                    ("kind", "protocol"),
                                    ("protocol_version__gte", 1),
                                    ("protocol_version__lte", 32767),
                                    ("queue_name__isnull", True),
                                    ("target__isnull", True),
                                ),
                                models.Q(
                                    ("kind", "target"),
                                    ("pause_claims", True),
                                    ("pause_enqueues", False),
                                    ("protocol_version__isnull", True),
                                    ("queue_name__isnull", True),
                                    ("target__isnull", False),
                                ),
                                _connector="OR",
                            ),
                            models.Q(
                                ("pause_enqueues", True), ("pause_claims", True), _connector="OR"
                            ),
                        ),
                        name="ray_maint_scope_shape",
                    ),
                ],
            },
        ),
        migrations.RunPython(_seed, migrations.RunPython.noop),
        migrations.RunPython(_install, _remove),
    ]
