# Generated by Django 6.1.1 on 2026-09-12 09:13

from django.db import migrations, models

_MAX = 9223372036854775807
_NAMESPACE = 1684697721
_KEY = 368


def _tables(apps, editor):
    return {
        name: editor.quote_name(apps.get_model("django_ray", name)._meta.db_table)
        for name in (
            "RayTaskQuarantine",
            "RayWorkerRetirement",
            "RayTaskExecution",
            "TaskWorkerLease",
            "RayTaskCohortClaim",
            "RayWorkerTargetCapability",
            "RayMaintenancePolicy",
        )
    }


def _install(apps, editor):
    tables = _tables(apps, editor)
    pg = editor.connection.vendor == "postgresql"
    if not pg and editor.connection.vendor != "sqlite":
        raise RuntimeError("Maintenance controls require SQLite or PostgreSQL")
    quarantine, retirement, execution, lease, claim, capability, policy = (
        tables[name]
        for name in (
            "RayTaskQuarantine",
            "RayWorkerRetirement",
            "RayTaskExecution",
            "TaskWorkerLease",
            "RayTaskCohortClaim",
            "RayWorkerTargetCapability",
            "RayMaintenancePolicy",
        )
    )
    unequal = "IS DISTINCT FROM" if pg else "IS NOT"

    def trigger(name, table, event, condition, *, parent=None, barrier=False, relevant=None):
        if pg:
            editor.execute(f"""CREATE FUNCTION django_ray_{name}() RETURNS trigger AS $$
            BEGIN
              {f"IF NOT ({relevant}) THEN RETURN NEW; END IF;" if relevant else ""}
              {f"IF current_setting('transaction_isolation') != 'read committed' THEN RAISE EXCEPTION 'maintenance controls require read committed'; END IF; PERFORM pg_advisory_xact_lock_shared({_NAMESPACE}, {_KEY});" if barrier else ""}
              {f"PERFORM 1 FROM {parent} FOR UPDATE;" if parent else ""}
              IF {condition} THEN RAISE EXCEPTION 'maintenance control rejected'; END IF;
              RETURN {"OLD" if event == "DELETE" else "NEW"};
            END; $$ LANGUAGE plpgsql""")
            editor.execute(
                f"CREATE TRIGGER {name} BEFORE {event} ON {table} FOR EACH ROW EXECUTE FUNCTION django_ray_{name}()"
            )
        else:
            editor.execute(f"""CREATE TRIGGER {name} BEFORE {event} ON {table}
              WHEN {condition} BEGIN SELECT RAISE(ABORT, 'maintenance control rejected'); END""")

    def same_worker(left, right):
        return " AND ".join(
            f"{left}.{field}={right}.{field}"
            for field in ("worker_id", "hostname", "pid", "started_at")
        )

    def active_quarantine(task):
        return f"""EXISTS (SELECT 1 FROM {quarantine} q WHERE q.task_execution_pk={task}.id
          AND q.state='QUARANTINED' AND NOT EXISTS (SELECT 1 FROM {quarantine} later
            WHERE later.task_execution_pk=q.task_execution_pk AND later.revision>q.revision))"""

    def retiring(worker):
        return f"""EXISTS (SELECT 1 FROM {lease} l JOIN {retirement} r ON {same_worker("r", "l")}
          WHERE l.worker_id={worker})"""

    def label(field):
        if pg:
            return f"NEW.{field} !~ '^[!-~]{{1,128}}$'"
        return f"typeof(NEW.{field})!='text' OR instr(NEW.{field},char(0))!=0 OR LENGTH(NEW.{field}) NOT BETWEEN 1 AND 128 OR NEW.{field} GLOB '*[^!-~]*'"

    common = f"({label('actor')}) OR ({label('reason')}) OR NOT EXISTS (SELECT 1 FROM {policy} WHERE singleton_key=1 AND schema_version=1)"
    current_revision = f"COALESCE((SELECT MAX(q.revision) FROM {quarantine} q WHERE q.task_execution_pk=NEW.task_execution_pk),0)"
    previous = f"SELECT 1 FROM {quarantine} q WHERE q.task_execution_pk=NEW.task_execution_pk AND q.revision=NEW.revision-1"
    exact_task = " AND ".join(
        f"e.{field}=NEW.{field}" for field in ("task_id", "attempt_number", "execution_generation")
    )
    quarantine_shape = f"""{common} OR NEW.revision NOT BETWEEN 1 AND {_MAX}
      OR NEW.task_execution_pk<1 OR NEW.attempt_number NOT BETWEEN 1 AND 2147483647
      OR NEW.execution_generation NOT BETWEEN 0 AND {_MAX}
      OR NEW.revision!=({current_revision})+1
      OR NOT EXISTS (SELECT 1 FROM {execution} e WHERE e.id=NEW.task_execution_pk AND {exact_task} AND NEW.created_at>=e.created_at)
      OR (NEW.revision=1 AND NEW.state!='QUARANTINED')
      OR (NEW.revision>1 AND NOT EXISTS ({previous} AND q.state!=NEW.state AND NEW.created_at>=q.created_at))
      OR NEW.state NOT IN ('QUARANTINED','RELEASED')"""
    retirement_shape = f"""{common} OR NOT EXISTS (SELECT 1 FROM {lease} l WHERE {same_worker("l", "NEW")} AND NEW.created_at>=l.started_at)
      OR (NEW.revision=1 AND (NEW.state!='REQUESTED' OR NEW.cleanup_evidence_digest IS NOT NULL OR NEW.cleanup_confirmed_at IS NOT NULL
          OR EXISTS (SELECT 1 FROM {retirement} r WHERE {same_worker("r", "NEW")})))
      OR (NEW.revision=2 AND (NEW.state!='RETIRED' OR NEW.cleanup_evidence_digest IS NULL OR NEW.cleanup_confirmed_at IS NULL
          OR NEW.cleanup_confirmed_at>NEW.created_at
          OR NOT EXISTS (SELECT 1 FROM {retirement} r WHERE {same_worker("r", "NEW")} AND r.revision=1
              AND NEW.created_at>=r.created_at AND NEW.cleanup_confirmed_at>=r.created_at)
          OR EXISTS (SELECT 1 FROM {execution} e WHERE e.claimed_by_worker=NEW.worker_id AND e.state IN ('RUNNING','CANCELLING'))
          OR EXISTS (SELECT 1 FROM {claim} c WHERE c.owner_lease_id=NEW.worker_id AND c.owner_lease_hostname=NEW.hostname
              AND c.owner_lease_pid=NEW.pid AND c.owner_lease_started_at=NEW.started_at AND c.disposition!='RESOLVED')
          OR EXISTS (SELECT 1 FROM {capability} c WHERE c.lease_id=NEW.worker_id)))
      OR NEW.revision NOT IN (1,2)"""
    if pg:
        retirement_shape += " OR (NEW.cleanup_evidence_digest IS NOT NULL AND NEW.cleanup_evidence_digest !~ '^sha256:[0-9a-f]{64}$')"
    else:
        quarantine_shape += " OR " + " OR ".join(
            f"typeof(NEW.{field})!='integer'"
            for field in (
                "revision",
                "task_execution_pk",
                "attempt_number",
                "execution_generation",
            )
        )
        retirement_shape += " OR typeof(NEW.revision)!='integer' OR typeof(NEW.pid)!='integer'"
        retirement_shape += " OR (NEW.cleanup_evidence_digest IS NOT NULL AND (typeof(NEW.cleanup_evidence_digest)!='text' OR instr(NEW.cleanup_evidence_digest,char(0))!=0 OR LENGTH(NEW.cleanup_evidence_digest)!=71 OR SUBSTR(NEW.cleanup_evidence_digest,1,7)!='sha256:' OR SUBSTR(NEW.cleanup_evidence_digest,8) GLOB '*[^0-9a-f]*'))"
    trigger(
        "ray_control_quarantine_insert_0032",
        quarantine,
        "INSERT",
        quarantine_shape,
        parent=f"{execution} e WHERE e.id=NEW.task_execution_pk",
        barrier=True,
    )
    trigger(
        "ray_control_retirement_insert_0032",
        retirement,
        "INSERT",
        retirement_shape,
        parent=f"{lease} l WHERE {same_worker('l', 'NEW')}",
        barrier=True,
    )
    for name, table in (("quarantine", quarantine), ("retirement", retirement)):
        trigger(f"ray_control_{name}_update_0032", table, "UPDATE", "TRUE" if pg else "1")
    # Parent retention can remove released history without a permanent FK. Audit
    # maintenance may remove the orphan snapshot later, never reopen a live row.
    trigger(
        "ray_control_quarantine_delete_0032",
        quarantine,
        "DELETE",
        f"EXISTS (SELECT 1 FROM {execution} e WHERE e.id=OLD.task_execution_pk AND e.task_id=OLD.task_id)",
    )
    trigger(
        "ray_control_retirement_delete_0032",
        retirement,
        "DELETE",
        f"EXISTS (SELECT 1 FROM {lease} l WHERE {same_worker('l', 'OLD')})",
    )

    identity_changed = f"""NEW.task_id {unequal} OLD.task_id OR NEW.attempt_number {unequal} OLD.attempt_number
      OR NEW.execution_generation {unequal} OLD.execution_generation"""
    requeued = "NEW.state='QUEUED' AND OLD.state!='QUEUED'"
    claimed = "OLD.state='QUEUED' AND NEW.state='RUNNING'"
    owner_changed = f"NEW.claimed_by_worker {unequal} OLD.claimed_by_worker"
    new_ownership = f"NEW.state IN ('RUNNING','CANCELLING') AND (({identity_changed}) OR ({claimed}) OR ({owner_changed}))"
    # Fresh SPI reads run after PostgreSQL obtains the execution tuple. The
    # control insert owns that same tuple before appending its decision.
    trigger(
        "ray_control_execution_update_0032",
        execution,
        "UPDATE",
        f"(({active_quarantine('OLD')}) AND (({identity_changed}) OR ({requeued}) OR ({claimed}))) OR (({new_ownership}) AND {retiring('NEW.claimed_by_worker')})",
        relevant=f"({identity_changed}) OR ({requeued}) OR ({claimed}) OR ({owner_changed})",
    )
    trigger(
        "ray_control_execution_insert_0032",
        execution,
        "INSERT",
        f"NEW.state IN ('RUNNING','CANCELLING') AND {retiring('NEW.claimed_by_worker')}",
    )
    trigger("ray_control_execution_delete_0032", execution, "DELETE", active_quarantine("OLD"))
    # Existing lease retention remains available. Its scalar REQUESTED history
    # survives deletion and cannot become proof that cleanup or retirement ran.
    trigger(
        "ray_control_claim_insert_0032",
        claim,
        "INSERT",
        f"{retiring('NEW.owner_lease_id')} OR EXISTS (SELECT 1 FROM {execution} e WHERE e.id=NEW.binding_id AND ({active_quarantine('e')}))",
    )
    # Adoption changes ownership, not immutable admission facts. Quarantine is
    # intentionally absent here; retiring destinations may not acquire work.
    owner_fields = (
        "owner_lease_id",
        "owner_lease_hostname",
        "owner_lease_pid",
        "owner_lease_started_at",
    )
    adoption = " OR ".join(f"NEW.{field} {unequal} OLD.{field}" for field in owner_fields)
    trigger(
        "ray_control_claim_update_0032",
        claim,
        "UPDATE",
        f"({adoption}) AND {retiring('NEW.owner_lease_id')}",
        relevant=adoption,
    )


def _remove(apps, editor):
    tables = _tables(apps, editor)
    if editor.connection.vendor == "postgresql":
        editor.execute(f"SELECT pg_advisory_xact_lock({_NAMESPACE},{_KEY})")
        editor.execute(
            f"LOCK TABLE {tables['RayTaskQuarantine']}, {tables['RayWorkerRetirement']} IN ACCESS EXCLUSIVE MODE"
        )
    elif editor.connection.vendor == "sqlite":
        editor.execute(f"UPDATE {tables['RayMaintenancePolicy']} SET revision=revision")
    else:
        raise RuntimeError("Maintenance controls require SQLite or PostgreSQL")
    if any(
        apps.get_model("django_ray", name).objects.using(editor.connection.alias).exists()
        for name in ("RayTaskQuarantine", "RayWorkerRetirement")
    ):
        raise RuntimeError("Cannot reverse maintenance controls with retained history")
    for name, model in (
        ("quarantine_insert", "RayTaskQuarantine"),
        ("quarantine_update", "RayTaskQuarantine"),
        ("quarantine_delete", "RayTaskQuarantine"),
        ("retirement_insert", "RayWorkerRetirement"),
        ("retirement_update", "RayWorkerRetirement"),
        ("retirement_delete", "RayWorkerRetirement"),
        ("execution_insert", "RayTaskExecution"),
        ("execution_update", "RayTaskExecution"),
        ("execution_delete", "RayTaskExecution"),
        ("claim_insert", "RayTaskCohortClaim"),
        ("claim_update", "RayTaskCohortClaim"),
    ):
        name = f"ray_control_{name}_0032"
        if editor.connection.vendor == "postgresql":
            editor.execute(f"DROP TRIGGER IF EXISTS {name} ON {tables[model]}")
            editor.execute(f"DROP FUNCTION IF EXISTS django_ray_{name}()")
        else:
            editor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0031_maintenance_admission"),
    ]

    operations = [
        migrations.CreateModel(
            name="RayTaskQuarantine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_execution_pk", models.PositiveBigIntegerField(editable=False)),
                ("task_id", models.CharField(editable=False, max_length=255)),
                ("attempt_number", models.PositiveIntegerField(editable=False)),
                ("execution_generation", models.PositiveBigIntegerField(editable=False)),
                ("revision", models.PositiveBigIntegerField(editable=False)),
                ("state", models.CharField(editable=False, max_length=11)),
                ("actor", models.CharField(editable=False, max_length=128)),
                ("reason", models.CharField(editable=False, max_length=128)),
                ("created_at", models.DateTimeField(editable=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["task_execution_pk", "-revision"], name="ray_quarantine_latest"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task_execution_pk", "revision"),
                        name="ray_quarantine_execution_rev",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("attempt_number__gte", 1),
                            ("attempt_number__lte", 2147483647),
                            ("revision__gte", 1),
                            ("state__in", ("QUARANTINED", "RELEASED")),
                            ("task_execution_pk__gte", 1),
                        ),
                        name="ray_quarantine_shape",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RayWorkerRetirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("worker_id", models.CharField(editable=False, max_length=255)),
                ("hostname", models.CharField(editable=False, max_length=255)),
                ("pid", models.PositiveIntegerField(editable=False)),
                ("started_at", models.DateTimeField(editable=False)),
                ("revision", models.PositiveSmallIntegerField(editable=False)),
                ("state", models.CharField(editable=False, max_length=9)),
                ("actor", models.CharField(editable=False, max_length=128)),
                ("reason", models.CharField(editable=False, max_length=128)),
                ("created_at", models.DateTimeField(editable=False)),
                (
                    "cleanup_evidence_digest",
                    models.CharField(editable=False, max_length=71, null=True),
                ),
                ("cleanup_confirmed_at", models.DateTimeField(editable=False, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("worker_id", "hostname", "pid", "started_at", "revision"),
                        name="ray_retirement_incarnation_rev",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("cleanup_confirmed_at__isnull", True),
                                ("cleanup_evidence_digest__isnull", True),
                                ("revision", 1),
                                ("state", "REQUESTED"),
                            ),
                            models.Q(
                                ("cleanup_confirmed_at__isnull", False),
                                ("cleanup_evidence_digest__isnull", False),
                                ("revision", 2),
                                ("state", "RETIRED"),
                            ),
                            _connector="OR",
                        ),
                        name="ray_retirement_shape",
                    ),
                ],
            },
        ),
        migrations.RunPython(_install, _remove),
    ]
