# Generated by Django 6.1.1 on 2026-09-12 09:51

import django.db.models.deletion
from django.db import migrations, models

_MAX = 9223372036854775807
_OWNER = ("owner_lease_id", "owner_lease_hostname", "owner_lease_pid", "owner_lease_started_at")
_IMMUTABLE = (
    "claim_id",
    "execution_id",
    "queue_name",
    "claim_facts_digest",
    "request_digest",
    "contract_digest",
    "completion_digest",
    "expectation_json",
    "expectation_digest",
    "missing_expectation_reason",
    "created_at",
)


def _tables(apps, editor):
    return {
        name: editor.quote_name(apps.get_model("django_ray", name)._meta.db_table)
        for name in (
            "RayCohortJobCleanup",
            "RayTaskCohortClaim",
            "RayTaskExecution",
            "RayTaskTargetBinding",
            "TaskWorkerLease",
            "RayWorkerRetirement",
        )
    }


def _install(apps, editor):
    tables = _tables(apps, editor)
    cleanup, claim, task, binding, lease, retirement = (
        tables[name]
        for name in (
            "RayCohortJobCleanup",
            "RayTaskCohortClaim",
            "RayTaskExecution",
            "RayTaskTargetBinding",
            "TaskWorkerLease",
            "RayWorkerRetirement",
        )
    )
    pg = editor.connection.vendor == "postgresql"
    if not pg and editor.connection.vendor != "sqlite":
        raise RuntimeError("Cohort Job cleanup requires SQLite or PostgreSQL")
    unequal = "IS DISTINCT FROM" if pg else "IS NOT"
    true = "TRUE" if pg else "1"
    # Protocol 3 has not shipped. Do not reinterpret pre-release completed Jobs
    # history as proof that its outer drivers have exited.
    with editor.connection.cursor() as cursor:
        cursor.execute(
            f"SELECT EXISTS(SELECT 1 FROM {claim} c JOIN {binding} b ON b.execution_id=c.binding_id WHERE b.schema_version=2 AND b.runner_family='ray_job' AND c.disposition='RESOLVED' AND c.resolution_kind='application_completed')"
        )
        if cursor.fetchone()[0]:
            raise RuntimeError(
                "Cannot install cohort Job cleanup over pre-release resolved Jobs history; exact driver cleanup evidence is unavailable"
            )

    def trigger(name, table, event, condition):
        if pg:
            editor.execute(f"""CREATE FUNCTION django_ray_{name}() RETURNS trigger AS $$ BEGIN
                IF {condition} THEN RAISE EXCEPTION 'cohort Job cleanup rejected'; END IF;
                RETURN {"OLD" if event == "DELETE" else "NEW"}; END; $$ LANGUAGE plpgsql""")
            editor.execute(
                f"CREATE TRIGGER {name} BEFORE {event} ON {table} FOR EACH ROW EXECUTE FUNCTION django_ray_{name}()"
            )
        else:
            editor.execute(
                f"CREATE TRIGGER {name} BEFORE {event} ON {table} WHEN {condition} BEGIN SELECT RAISE(ABORT, 'cohort Job cleanup rejected'); END"
            )

    def digest(field):
        if pg:
            return f"NEW.{field} IS NULL OR NEW.{field} !~ '^sha256:[0-9a-f]{{64}}$'"
        return f"NEW.{field} IS NULL OR typeof(NEW.{field})!='text' OR instr(NEW.{field},char(0))!=0 OR length(NEW.{field})!=71 OR substr(NEW.{field},1,7)!='sha256:' OR substr(NEW.{field},8) GLOB '*[^0-9a-f]*'"

    def owner(left, right):
        return " AND ".join(f"{left}.{field}={right}.{field}" for field in _OWNER)

    live_owner = f"""EXISTS(SELECT 1 FROM {lease} l JOIN {claim} c ON c.id=NEW.claim_id
        JOIN {binding} b ON b.execution_id=c.binding_id
        WHERE l.worker_id=NEW.owner_lease_id AND l.hostname=NEW.owner_lease_hostname
        AND l.pid=NEW.owner_lease_pid AND l.started_at=NEW.owner_lease_started_at
        AND l.is_active={true} AND l.stopped_at IS NULL AND l.django_ray_version=b.package_version
        AND l.min_supported_execution_protocol_version<=3 AND l.max_supported_execution_protocol_version>=3)"""
    chronology = "NEW.created_at IS NULL OR NEW.updated_at IS NULL OR NEW.updated_at<NEW.created_at"
    shape = f"({chronology}) OR NEW.revision NOT BETWEEN 1 AND {_MAX} OR NOT ({live_owner})"
    shape += " OR " + " OR ".join(
        f"({digest(field)})"
        for field in (
            "claim_facts_digest",
            "request_digest",
            "contract_digest",
            "completion_digest",
        )
    )
    shape += f" OR (NEW.expectation_digest IS NOT NULL AND ({digest('expectation_digest')}))"
    if pg:
        shape += (
            " OR length(NEW.queue_name) NOT BETWEEN 1 AND 100 OR length(btrim(NEW.queue_name))=0"
        )
        shape += (
            " OR (NEW.expectation_json IS NOT NULL AND octet_length(NEW.expectation_json)>16384)"
        )
    else:
        shape += " OR typeof(NEW.revision)!='integer' OR typeof(NEW.owner_lease_pid)!='integer'"
        shape += " OR typeof(NEW.queue_name)!='text' OR instr(NEW.queue_name,char(0))!=0 OR length(NEW.queue_name) NOT BETWEEN 1 AND 100 OR length(trim(NEW.queue_name))=0"
        shape += " OR (NEW.expectation_json IS NOT NULL AND (typeof(NEW.expectation_json)!='text' OR instr(NEW.expectation_json,char(0))!=0 OR length(CAST(NEW.expectation_json AS BLOB))>16384 OR NOT json_valid(NEW.expectation_json)))"
    insert = f"""{shape} OR NEW.revision!=1 OR NEW.state!='OPEN' OR NEW.updated_at!=NEW.created_at
        OR NOT EXISTS(SELECT 1 FROM {claim} c JOIN {task} e ON e.id=c.binding_id
            JOIN {binding} b ON b.execution_id=c.binding_id WHERE c.id=NEW.claim_id
            AND NEW.execution_id=e.id AND NEW.queue_name=e.queue_name
            AND b.schema_version=2 AND b.runner_family='ray_job'
            AND c.disposition IN ('OPEN','HELD') AND c.dispatched_at IS NOT NULL AND NEW.created_at>=c.dispatched_at
            AND c.facts_digest=NEW.claim_facts_digest AND c.prepared_request_digest=NEW.request_digest
            AND {owner("c", "NEW")} AND e.claimed_by_worker=NEW.owner_lease_id
            AND e.attempt_number=c.attempt_number AND e.execution_generation=c.execution_generation
            AND e.state IN ('RUNNING','CANCELLING'))"""
    trigger("ray_jobcleanup_insert_0033", cleanup, "INSERT", insert)
    changed = " OR ".join(f"NEW.{field} {unequal} OLD.{field}" for field in _IMMUTABLE)
    owner_changed = " OR ".join(f"NEW.{field} {unequal} OLD.{field}" for field in _OWNER)
    complete = f"""EXISTS(SELECT 1 FROM {claim} c WHERE c.id=NEW.claim_id AND c.disposition='RESOLVED'
        AND c.resolution_kind='application_completed' AND c.resolution_digest=NEW.completion_digest
        AND c.facts_digest=NEW.claim_facts_digest AND NEW.inspection_began_at>=c.resolved_at)"""
    close_shape = f"""NEW.expectation_json IS NULL OR NEW.inspection_began_at IS NULL OR NEW.closed_at IS NULL
        OR NEW.terminal_status IS NULL OR NEW.terminal_status NOT IN ('SUCCEEDED','FAILED','STOPPED')
        OR NEW.inspection_began_at<OLD.updated_at OR NEW.closed_at<NEW.inspection_began_at
        OR NEW.updated_at!=NEW.closed_at OR ({owner_changed}) OR NOT ({complete}) OR ({digest("observation_digest")})"""
    if pg:
        close_shape += " OR NEW.native_job_id IS NULL OR NEW.native_job_id !~ '^[0-9a-f]{8}$' OR NEW.native_job_id='ffffffff'"
    else:
        close_shape += " OR NEW.native_job_id IS NULL OR typeof(NEW.native_job_id)!='text' OR instr(NEW.native_job_id,char(0))!=0 OR length(NEW.native_job_id)!=8 OR NEW.native_job_id GLOB '*[^0-9a-f]*' OR NEW.native_job_id='ffffffff'"
    update = f"""{shape} OR ({changed}) OR OLD.state!='OPEN' OR NEW.revision!=OLD.revision+1 OR NEW.updated_at<OLD.updated_at
        OR (NEW.state='OPEN' AND (NOT ({owner_changed}) OR NEW.owner_lease_id=OLD.owner_lease_id
            OR EXISTS(SELECT 1 FROM {lease} previous WHERE previous.worker_id=OLD.owner_lease_id AND previous.is_active={true})
            OR EXISTS(SELECT 1 FROM {retirement} r WHERE r.worker_id=NEW.owner_lease_id AND r.hostname=NEW.owner_lease_hostname
                AND r.pid=NEW.owner_lease_pid AND r.started_at=NEW.owner_lease_started_at)))
        OR (NEW.state='CLOSED' AND ({close_shape})) OR NEW.state NOT IN ('OPEN','CLOSED')"""
    trigger("ray_jobcleanup_update_0033", cleanup, "UPDATE", update)
    trigger("ray_jobcleanup_delete_0033", cleanup, "DELETE", "OLD.state='OPEN'")
    pending = f"EXISTS(SELECT 1 FROM {cleanup} pending WHERE pending.execution_id=OLD.id AND pending.state='OPEN')"
    trigger("ray_jobcleanup_task_delete_0033", task, "DELETE", pending)
    trigger(
        "ray_jobcleanup_task_update_0033",
        task,
        "UPDATE",
        f"({pending}) AND ((OLD.state='QUEUED' AND NEW.state='RUNNING') OR NEW.execution_generation {unequal} OLD.execution_generation)",
    )
    trigger(
        "ray_jobcleanup_claim_insert_0033",
        claim,
        "INSERT",
        f"EXISTS(SELECT 1 FROM {cleanup} pending WHERE pending.execution_id=NEW.binding_id AND pending.state='OPEN')",
    )
    trigger(
        "ray_jobcleanup_claim_delete_0033",
        claim,
        "DELETE",
        f"EXISTS(SELECT 1 FROM {cleanup} pending WHERE pending.claim_id=OLD.id AND pending.state='OPEN')",
    )
    resolution = f"""OLD.disposition!='RESOLVED' AND NEW.disposition='RESOLVED' AND NEW.resolution_kind='application_completed'
        AND EXISTS(SELECT 1 FROM {binding} b WHERE b.execution_id=NEW.binding_id AND b.schema_version=2 AND b.runner_family='ray_job')
        AND NOT EXISTS(SELECT 1 FROM {cleanup} pending WHERE pending.claim_id=NEW.id AND pending.state='OPEN'
            AND pending.completion_digest=NEW.resolution_digest AND pending.claim_facts_digest=NEW.facts_digest
            AND pending.request_digest=NEW.prepared_request_digest AND pending.created_at<=NEW.resolved_at)"""
    trigger("ray_jobcleanup_claim_resolve_0033", claim, "UPDATE", resolution)
    trigger(
        "ray_jobcleanup_retirement_insert_0033",
        retirement,
        "INSERT",
        f"NEW.revision=2 AND EXISTS(SELECT 1 FROM {cleanup} pending WHERE pending.state='OPEN' AND pending.owner_lease_id=NEW.worker_id AND pending.owner_lease_hostname=NEW.hostname AND pending.owner_lease_pid=NEW.pid AND pending.owner_lease_started_at=NEW.started_at)",
    )


def _remove(apps, editor):
    tables = _tables(apps, editor)
    if editor.connection.vendor == "postgresql":
        editor.execute(f"LOCK TABLE {tables['RayCohortJobCleanup']} IN ACCESS EXCLUSIVE MODE")
    elif editor.connection.vendor == "sqlite":
        editor.execute(f"DELETE FROM {tables['RayCohortJobCleanup']} WHERE 1=0")
    if (
        apps.get_model("django_ray", "RayCohortJobCleanup")
        .objects.using(editor.connection.alias)
        .exists()
    ):
        raise RuntimeError("Cannot reverse cohort Job cleanup with retained history")
    for name, model in (
        ("insert", "RayCohortJobCleanup"),
        ("update", "RayCohortJobCleanup"),
        ("delete", "RayCohortJobCleanup"),
        ("task_delete", "RayTaskExecution"),
        ("task_update", "RayTaskExecution"),
        ("claim_insert", "RayTaskCohortClaim"),
        ("claim_delete", "RayTaskCohortClaim"),
        ("claim_resolve", "RayTaskCohortClaim"),
        ("retirement_insert", "RayWorkerRetirement"),
    ):
        name = f"ray_jobcleanup_{name}_0033"
        if editor.connection.vendor == "postgresql":
            editor.execute(f"DROP TRIGGER IF EXISTS {name} ON {tables[model]}")
            editor.execute(f"DROP FUNCTION IF EXISTS django_ray_{name}()")
        else:
            editor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):
    dependencies = [
        ("django_ray", "0032_maintenance_controls"),
    ]

    operations = [
        migrations.CreateModel(
            name="RayCohortJobCleanup",
            fields=[
                (
                    "claim",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="job_cleanup",
                        serialize=False,
                        to="django_ray.raytaskcohortclaim",
                    ),
                ),
                ("queue_name", models.CharField(editable=False, max_length=100)),
                ("claim_facts_digest", models.CharField(editable=False, max_length=71)),
                ("request_digest", models.CharField(editable=False, max_length=71)),
                ("contract_digest", models.CharField(editable=False, max_length=71)),
                ("completion_digest", models.CharField(editable=False, max_length=71)),
                ("expectation_json", models.TextField(editable=False, null=True)),
                ("expectation_digest", models.CharField(editable=False, max_length=71, null=True)),
                (
                    "missing_expectation_reason",
                    models.CharField(editable=False, max_length=32, null=True),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("owner_lease_id", models.CharField(editable=False, max_length=255)),
                ("owner_lease_hostname", models.CharField(editable=False, max_length=255)),
                ("owner_lease_pid", models.PositiveIntegerField(editable=False)),
                ("owner_lease_started_at", models.DateTimeField(editable=False)),
                (
                    "revision",
                    models.PositiveBigIntegerField(db_default=1, default=1, editable=False),
                ),
                (
                    "state",
                    models.CharField(
                        db_default="OPEN", default="OPEN", editable=False, max_length=6
                    ),
                ),
                ("inspection_began_at", models.DateTimeField(editable=False, null=True)),
                ("closed_at", models.DateTimeField(editable=False, null=True)),
                ("terminal_status", models.CharField(editable=False, max_length=9, null=True)),
                ("native_job_id", models.CharField(editable=False, max_length=8, null=True)),
                ("observation_digest", models.CharField(editable=False, max_length=71, null=True)),
                (
                    "execution",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_cleanups",
                        to="django_ray.raytaskexecution",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["execution", "state"], name="ray_jobcleanup_execution"),
                    models.Index(fields=["owner_lease_id", "state"], name="ray_jobcleanup_owner"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("expectation_digest__isnull", False),
                                ("expectation_json__isnull", False),
                                ("missing_expectation_reason__isnull", True),
                            ),
                            models.Q(
                                ("expectation_digest__isnull", True),
                                ("expectation_json__isnull", True),
                                ("missing_expectation_reason", "missing_expectation"),
                                ("missing_expectation_reason__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ray_jobcleanup_expectation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("closed_at__isnull", True),
                                ("inspection_began_at__isnull", True),
                                ("native_job_id__isnull", True),
                                ("observation_digest__isnull", True),
                                ("state", "OPEN"),
                                ("terminal_status__isnull", True),
                            ),
                            models.Q(
                                ("closed_at__isnull", False),
                                ("inspection_began_at__isnull", False),
                                ("native_job_id__isnull", False),
                                ("observation_digest__isnull", False),
                                ("state", "CLOSED"),
                                ("terminal_status__in", ("SUCCEEDED", "FAILED", "STOPPED")),
                            ),
                            _connector="OR",
                        ),
                        name="ray_jobcleanup_disposition",
                    ),
                ],
            },
        ),
        migrations.RunPython(_install, _remove),
    ]
