apiVersion: v1
kind: ResourceQuota
metadata:
  name: kuberay-co-resident-budget
  namespace: kuberay-system
spec:
  hard:
    requests.cpu: 200m
    requests.memory: 1Gi
    requests.ephemeral-storage: 256Mi
    limits.cpu: 200m
    limits.memory: 1Gi
    limits.ephemeral-storage: 512Mi
    requests.storage: 1Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: kuberay-co-resident-defaults
  namespace: kuberay-system
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 512Mi
        ephemeral-storage: 64Mi
      default:
        cpu: 100m
        memory: 512Mi
        ephemeral-storage: 256Mi
      max:
        cpu: 100m
        memory: 512Mi
        ephemeral-storage: 256Mi
