# Django-Ray ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-ray-config
  namespace: django-ray
data:
  DJANGO_SETTINGS_MODULE: "testproject.settings"
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
  # Ray configuration
  RAY_ADDRESS: "ray://ray-head-svc:10001"
  DJANGO_RAY_WORKING_DIR_URI: "file:///runtime-env/django-ray-source.zip"
  RAY_DASHBOARD_HOST: "0.0.0.0"
  RAY_DASHBOARD_URL: "http://localhost:30265"
  RAY_STATE_API_ADDRESS: "http://ray-head-svc:8265"
  # Database configuration (override in production)
  DATABASE_ENGINE: "django.db.backends.postgresql"
  DATABASE_NAME: "django_ray"
  DATABASE_HOST: "postgres-svc"
  DATABASE_PORT: "5432"

